/**
 * AUTO-GENERATED FILE.
 *
 * Do not edit this file manually.
 *
 * Generated by:
 * scripts/generate-photo-data.mjs
 */

export type GeneratedPhotoWork = {
	id: string;
	image: string;
	imageSmall: string;
	imageMedium: string;
	imageLarge: string;
	date: string;
	order: number;
};

export const generatedPhotoWorks: GeneratedPhotoWork[] = [
  {
    "id": "20260918-036",
    "image": "/photos/pics/20260918-036.png",
    "imageSmall": "/photos/optimized/20260918-036-480.webp",
    "imageMedium": "/photos/optimized/20260918-036-960.webp",
    "imageLarge": "/photos/optimized/20260918-036-1600.webp",
    "date": "2026-09-18",
    "order": 1
  },
  {
    "id": "20260918-035",
    "image": "/photos/pics/20260918-035.png",
    "imageSmall": "/photos/optimized/20260918-035-480.webp",
    "imageMedium": "/photos/optimized/20260918-035-960.webp",
    "imageLarge": "/photos/optimized/20260918-035-1600.webp",
    "date": "2026-09-18",
    "order": 2
  },
  {
    "id": "20260918-034",
    "image": "/photos/pics/20260918-034.png",
    "imageSmall": "/photos/optimized/20260918-034-480.webp",
    "imageMedium": "/photos/optimized/20260918-034-960.webp",
    "imageLarge": "/photos/optimized/20260918-034-1600.webp",
    "date": "2026-09-18",
    "order": 3
  },
  {
    "id": "20260918-033",
    "image": "/photos/pics/20260918-033.png",
    "imageSmall": "/photos/optimized/20260918-033-480.webp",
    "imageMedium": "/photos/optimized/20260918-033-960.webp",
    "imageLarge": "/photos/optimized/20260918-033-1600.webp",
    "date": "2026-09-18",
    "order": 4
  },
  {
    "id": "20260918-032",
    "image": "/photos/pics/20260918-032.png",
    "imageSmall": "/photos/optimized/20260918-032-480.webp",
    "imageMedium": "/photos/optimized/20260918-032-960.webp",
    "imageLarge": "/photos/optimized/20260918-032-1600.webp",
    "date": "2026-09-18",
    "order": 5
  },
  {
    "id": "20260918-031",
    "image": "/photos/pics/20260918-031.png",
    "imageSmall": "/photos/optimized/20260918-031-480.webp",
    "imageMedium": "/photos/optimized/20260918-031-960.webp",
    "imageLarge": "/photos/optimized/20260918-031-1600.webp",
    "date": "2026-09-18",
    "order": 6
  },
  {
    "id": "20260918-030",
    "image": "/photos/pics/20260918-030.png",
    "imageSmall": "/photos/optimized/20260918-030-480.webp",
    "imageMedium": "/photos/optimized/20260918-030-960.webp",
    "imageLarge": "/photos/optimized/20260918-030-1600.webp",
    "date": "2026-09-18",
    "order": 7
  },
  {
    "id": "20260918-029",
    "image": "/photos/pics/20260918-029.png",
    "imageSmall": "/photos/optimized/20260918-029-480.webp",
    "imageMedium": "/photos/optimized/20260918-029-960.webp",
    "imageLarge": "/photos/optimized/20260918-029-1600.webp",
    "date": "2026-09-18",
    "order": 8
  },
  {
    "id": "20260918-028",
    "image": "/photos/pics/20260918-028.png",
    "imageSmall": "/photos/optimized/20260918-028-480.webp",
    "imageMedium": "/photos/optimized/20260918-028-960.webp",
    "imageLarge": "/photos/optimized/20260918-028-1600.webp",
    "date": "2026-09-18",
    "order": 9
  },
  {
    "id": "20260918-027",
    "image": "/photos/pics/20260918-027.png",
    "imageSmall": "/photos/optimized/20260918-027-480.webp",
    "imageMedium": "/photos/optimized/20260918-027-960.webp",
    "imageLarge": "/photos/optimized/20260918-027-1600.webp",
    "date": "2026-09-18",
    "order": 10
  },
  {
    "id": "20260918-026",
    "image": "/photos/pics/20260918-026.png",
    "imageSmall": "/photos/optimized/20260918-026-480.webp",
    "imageMedium": "/photos/optimized/20260918-026-960.webp",
    "imageLarge": "/photos/optimized/20260918-026-1600.webp",
    "date": "2026-09-18",
    "order": 11
  },
  {
    "id": "20260918-025",
    "image": "/photos/pics/20260918-025.png",
    "imageSmall": "/photos/optimized/20260918-025-480.webp",
    "imageMedium": "/photos/optimized/20260918-025-960.webp",
    "imageLarge": "/photos/optimized/20260918-025-1600.webp",
    "date": "2026-09-18",
    "order": 12
  },
  {
    "id": "20260918-024",
    "image": "/photos/pics/20260918-024.png",
    "imageSmall": "/photos/optimized/20260918-024-480.webp",
    "imageMedium": "/photos/optimized/20260918-024-960.webp",
    "imageLarge": "/photos/optimized/20260918-024-1600.webp",
    "date": "2026-09-18",
    "order": 13
  },
  {
    "id": "20260918-023",
    "image": "/photos/pics/20260918-023.png",
    "imageSmall": "/photos/optimized/20260918-023-480.webp",
    "imageMedium": "/photos/optimized/20260918-023-960.webp",
    "imageLarge": "/photos/optimized/20260918-023-1600.webp",
    "date": "2026-09-18",
    "order": 14
  },
  {
    "id": "20260918-022",
    "image": "/photos/pics/20260918-022.png",
    "imageSmall": "/photos/optimized/20260918-022-480.webp",
    "imageMedium": "/photos/optimized/20260918-022-960.webp",
    "imageLarge": "/photos/optimized/20260918-022-1600.webp",
    "date": "2026-09-18",
    "order": 15
  },
  {
    "id": "20260918-021",
    "image": "/photos/pics/20260918-021.png",
    "imageSmall": "/photos/optimized/20260918-021-480.webp",
    "imageMedium": "/photos/optimized/20260918-021-960.webp",
    "imageLarge": "/photos/optimized/20260918-021-1600.webp",
    "date": "2026-09-18",
    "order": 16
  },
  {
    "id": "20260918-020",
    "image": "/photos/pics/20260918-020.png",
    "imageSmall": "/photos/optimized/20260918-020-480.webp",
    "imageMedium": "/photos/optimized/20260918-020-960.webp",
    "imageLarge": "/photos/optimized/20260918-020-1600.webp",
    "date": "2026-09-18",
    "order": 17
  },
  {
    "id": "20260918-019",
    "image": "/photos/pics/20260918-019.png",
    "imageSmall": "/photos/optimized/20260918-019-480.webp",
    "imageMedium": "/photos/optimized/20260918-019-960.webp",
    "imageLarge": "/photos/optimized/20260918-019-1600.webp",
    "date": "2026-09-18",
    "order": 18
  },
  {
    "id": "20260918-018",
    "image": "/photos/pics/20260918-018.png",
    "imageSmall": "/photos/optimized/20260918-018-480.webp",
    "imageMedium": "/photos/optimized/20260918-018-960.webp",
    "imageLarge": "/photos/optimized/20260918-018-1600.webp",
    "date": "2026-09-18",
    "order": 19
  },
  {
    "id": "20260918-017",
    "image": "/photos/pics/20260918-017.png",
    "imageSmall": "/photos/optimized/20260918-017-480.webp",
    "imageMedium": "/photos/optimized/20260918-017-960.webp",
    "imageLarge": "/photos/optimized/20260918-017-1600.webp",
    "date": "2026-09-18",
    "order": 20
  },
  {
    "id": "20260918-016",
    "image": "/photos/pics/20260918-016.png",
    "imageSmall": "/photos/optimized/20260918-016-480.webp",
    "imageMedium": "/photos/optimized/20260918-016-960.webp",
    "imageLarge": "/photos/optimized/20260918-016-1600.webp",
    "date": "2026-09-18",
    "order": 21
  },
  {
    "id": "20260918-015",
    "image": "/photos/pics/20260918-015.png",
    "imageSmall": "/photos/optimized/20260918-015-480.webp",
    "imageMedium": "/photos/optimized/20260918-015-960.webp",
    "imageLarge": "/photos/optimized/20260918-015-1600.webp",
    "date": "2026-09-18",
    "order": 22
  },
  {
    "id": "20260918-014",
    "image": "/photos/pics/20260918-014.png",
    "imageSmall": "/photos/optimized/20260918-014-480.webp",
    "imageMedium": "/photos/optimized/20260918-014-960.webp",
    "imageLarge": "/photos/optimized/20260918-014-1600.webp",
    "date": "2026-09-18",
    "order": 23
  },
  {
    "id": "20260918-013",
    "image": "/photos/pics/20260918-013.png",
    "imageSmall": "/photos/optimized/20260918-013-480.webp",
    "imageMedium": "/photos/optimized/20260918-013-960.webp",
    "imageLarge": "/photos/optimized/20260918-013-1600.webp",
    "date": "2026-09-18",
    "order": 24
  },
  {
    "id": "20260918-012",
    "image": "/photos/pics/20260918-012.png",
    "imageSmall": "/photos/optimized/20260918-012-480.webp",
    "imageMedium": "/photos/optimized/20260918-012-960.webp",
    "imageLarge": "/photos/optimized/20260918-012-1600.webp",
    "date": "2026-09-18",
    "order": 25
  },
  {
    "id": "20260918-011",
    "image": "/photos/pics/20260918-011.png",
    "imageSmall": "/photos/optimized/20260918-011-480.webp",
    "imageMedium": "/photos/optimized/20260918-011-960.webp",
    "imageLarge": "/photos/optimized/20260918-011-1600.webp",
    "date": "2026-09-18",
    "order": 26
  },
  {
    "id": "20260918-010",
    "image": "/photos/pics/20260918-010.png",
    "imageSmall": "/photos/optimized/20260918-010-480.webp",
    "imageMedium": "/photos/optimized/20260918-010-960.webp",
    "imageLarge": "/photos/optimized/20260918-010-1600.webp",
    "date": "2026-09-18",
    "order": 27
  },
  {
    "id": "20260918-009",
    "image": "/photos/pics/20260918-009.png",
    "imageSmall": "/photos/optimized/20260918-009-480.webp",
    "imageMedium": "/photos/optimized/20260918-009-960.webp",
    "imageLarge": "/photos/optimized/20260918-009-1600.webp",
    "date": "2026-09-18",
    "order": 28
  },
  {
    "id": "20260918-008",
    "image": "/photos/pics/20260918-008.png",
    "imageSmall": "/photos/optimized/20260918-008-480.webp",
    "imageMedium": "/photos/optimized/20260918-008-960.webp",
    "imageLarge": "/photos/optimized/20260918-008-1600.webp",
    "date": "2026-09-18",
    "order": 29
  },
  {
    "id": "20260918-007",
    "image": "/photos/pics/20260918-007.png",
    "imageSmall": "/photos/optimized/20260918-007-480.webp",
    "imageMedium": "/photos/optimized/20260918-007-960.webp",
    "imageLarge": "/photos/optimized/20260918-007-1600.webp",
    "date": "2026-09-18",
    "order": 30
  },
  {
    "id": "20260918-006",
    "image": "/photos/pics/20260918-006.png",
    "imageSmall": "/photos/optimized/20260918-006-480.webp",
    "imageMedium": "/photos/optimized/20260918-006-960.webp",
    "imageLarge": "/photos/optimized/20260918-006-1600.webp",
    "date": "2026-09-18",
    "order": 31
  },
  {
    "id": "20260918-005",
    "image": "/photos/pics/20260918-005.png",
    "imageSmall": "/photos/optimized/20260918-005-480.webp",
    "imageMedium": "/photos/optimized/20260918-005-960.webp",
    "imageLarge": "/photos/optimized/20260918-005-1600.webp",
    "date": "2026-09-18",
    "order": 32
  },
  {
    "id": "20260918-004",
    "image": "/photos/pics/20260918-004.png",
    "imageSmall": "/photos/optimized/20260918-004-480.webp",
    "imageMedium": "/photos/optimized/20260918-004-960.webp",
    "imageLarge": "/photos/optimized/20260918-004-1600.webp",
    "date": "2026-09-18",
    "order": 33
  },
  {
    "id": "20260918-003",
    "image": "/photos/pics/20260918-003.png",
    "imageSmall": "/photos/optimized/20260918-003-480.webp",
    "imageMedium": "/photos/optimized/20260918-003-960.webp",
    "imageLarge": "/photos/optimized/20260918-003-1600.webp",
    "date": "2026-09-18",
    "order": 34
  },
  {
    "id": "20260918-002",
    "image": "/photos/pics/20260918-002.png",
    "imageSmall": "/photos/optimized/20260918-002-480.webp",
    "imageMedium": "/photos/optimized/20260918-002-960.webp",
    "imageLarge": "/photos/optimized/20260918-002-1600.webp",
    "date": "2026-09-18",
    "order": 35
  },
  {
    "id": "20260918-001",
    "image": "/photos/pics/20260918-001.png",
    "imageSmall": "/photos/optimized/20260918-001-480.webp",
    "imageMedium": "/photos/optimized/20260918-001-960.webp",
    "imageLarge": "/photos/optimized/20260918-001-1600.webp",
    "date": "2026-09-18",
    "order": 36
  },
  {
    "id": "20260917-028",
    "image": "/photos/pics/20260917-028.png",
    "imageSmall": "/photos/optimized/20260917-028-480.webp",
    "imageMedium": "/photos/optimized/20260917-028-960.webp",
    "imageLarge": "/photos/optimized/20260917-028-1600.webp",
    "date": "2026-09-17",
    "order": 37
  },
  {
    "id": "20260917-027",
    "image": "/photos/pics/20260917-027.png",
    "imageSmall": "/photos/optimized/20260917-027-480.webp",
    "imageMedium": "/photos/optimized/20260917-027-960.webp",
    "imageLarge": "/photos/optimized/20260917-027-1600.webp",
    "date": "2026-09-17",
    "order": 38
  },
  {
    "id": "20260917-026",
    "image": "/photos/pics/20260917-026.png",
    "imageSmall": "/photos/optimized/20260917-026-480.webp",
    "imageMedium": "/photos/optimized/20260917-026-960.webp",
    "imageLarge": "/photos/optimized/20260917-026-1600.webp",
    "date": "2026-09-17",
    "order": 39
  },
  {
    "id": "20260917-025",
    "image": "/photos/pics/20260917-025.png",
    "imageSmall": "/photos/optimized/20260917-025-480.webp",
    "imageMedium": "/photos/optimized/20260917-025-960.webp",
    "imageLarge": "/photos/optimized/20260917-025-1600.webp",
    "date": "2026-09-17",
    "order": 40
  },
  {
    "id": "20260917-024",
    "image": "/photos/pics/20260917-024.png",
    "imageSmall": "/photos/optimized/20260917-024-480.webp",
    "imageMedium": "/photos/optimized/20260917-024-960.webp",
    "imageLarge": "/photos/optimized/20260917-024-1600.webp",
    "date": "2026-09-17",
    "order": 41
  },
  {
    "id": "20260917-023",
    "image": "/photos/pics/20260917-023.png",
    "imageSmall": "/photos/optimized/20260917-023-480.webp",
    "imageMedium": "/photos/optimized/20260917-023-960.webp",
    "imageLarge": "/photos/optimized/20260917-023-1600.webp",
    "date": "2026-09-17",
    "order": 42
  },
  {
    "id": "20260917-022",
    "image": "/photos/pics/20260917-022.png",
    "imageSmall": "/photos/optimized/20260917-022-480.webp",
    "imageMedium": "/photos/optimized/20260917-022-960.webp",
    "imageLarge": "/photos/optimized/20260917-022-1600.webp",
    "date": "2026-09-17",
    "order": 43
  },
  {
    "id": "20260917-021",
    "image": "/photos/pics/20260917-021.png",
    "imageSmall": "/photos/optimized/20260917-021-480.webp",
    "imageMedium": "/photos/optimized/20260917-021-960.webp",
    "imageLarge": "/photos/optimized/20260917-021-1600.webp",
    "date": "2026-09-17",
    "order": 44
  },
  {
    "id": "20260917-020",
    "image": "/photos/pics/20260917-020.png",
    "imageSmall": "/photos/optimized/20260917-020-480.webp",
    "imageMedium": "/photos/optimized/20260917-020-960.webp",
    "imageLarge": "/photos/optimized/20260917-020-1600.webp",
    "date": "2026-09-17",
    "order": 45
  },
  {
    "id": "20260917-019",
    "image": "/photos/pics/20260917-019.png",
    "imageSmall": "/photos/optimized/20260917-019-480.webp",
    "imageMedium": "/photos/optimized/20260917-019-960.webp",
    "imageLarge": "/photos/optimized/20260917-019-1600.webp",
    "date": "2026-09-17",
    "order": 46
  },
  {
    "id": "20260917-018",
    "image": "/photos/pics/20260917-018.png",
    "imageSmall": "/photos/optimized/20260917-018-480.webp",
    "imageMedium": "/photos/optimized/20260917-018-960.webp",
    "imageLarge": "/photos/optimized/20260917-018-1600.webp",
    "date": "2026-09-17",
    "order": 47
  },
  {
    "id": "20260917-017",
    "image": "/photos/pics/20260917-017.png",
    "imageSmall": "/photos/optimized/20260917-017-480.webp",
    "imageMedium": "/photos/optimized/20260917-017-960.webp",
    "imageLarge": "/photos/optimized/20260917-017-1600.webp",
    "date": "2026-09-17",
    "order": 48
  },
  {
    "id": "20260917-016",
    "image": "/photos/pics/20260917-016.png",
    "imageSmall": "/photos/optimized/20260917-016-480.webp",
    "imageMedium": "/photos/optimized/20260917-016-960.webp",
    "imageLarge": "/photos/optimized/20260917-016-1600.webp",
    "date": "2026-09-17",
    "order": 49
  },
  {
    "id": "20260917-015",
    "image": "/photos/pics/20260917-015.png",
    "imageSmall": "/photos/optimized/20260917-015-480.webp",
    "imageMedium": "/photos/optimized/20260917-015-960.webp",
    "imageLarge": "/photos/optimized/20260917-015-1600.webp",
    "date": "2026-09-17",
    "order": 50
  },
  {
    "id": "20260917-014",
    "image": "/photos/pics/20260917-014.png",
    "imageSmall": "/photos/optimized/20260917-014-480.webp",
    "imageMedium": "/photos/optimized/20260917-014-960.webp",
    "imageLarge": "/photos/optimized/20260917-014-1600.webp",
    "date": "2026-09-17",
    "order": 51
  },
  {
    "id": "20260917-013",
    "image": "/photos/pics/20260917-013.png",
    "imageSmall": "/photos/optimized/20260917-013-480.webp",
    "imageMedium": "/photos/optimized/20260917-013-960.webp",
    "imageLarge": "/photos/optimized/20260917-013-1600.webp",
    "date": "2026-09-17",
    "order": 52
  },
  {
    "id": "20260917-012",
    "image": "/photos/pics/20260917-012.png",
    "imageSmall": "/photos/optimized/20260917-012-480.webp",
    "imageMedium": "/photos/optimized/20260917-012-960.webp",
    "imageLarge": "/photos/optimized/20260917-012-1600.webp",
    "date": "2026-09-17",
    "order": 53
  },
  {
    "id": "20260917-011",
    "image": "/photos/pics/20260917-011.png",
    "imageSmall": "/photos/optimized/20260917-011-480.webp",
    "imageMedium": "/photos/optimized/20260917-011-960.webp",
    "imageLarge": "/photos/optimized/20260917-011-1600.webp",
    "date": "2026-09-17",
    "order": 54
  },
  {
    "id": "20260917-010",
    "image": "/photos/pics/20260917-010.png",
    "imageSmall": "/photos/optimized/20260917-010-480.webp",
    "imageMedium": "/photos/optimized/20260917-010-960.webp",
    "imageLarge": "/photos/optimized/20260917-010-1600.webp",
    "date": "2026-09-17",
    "order": 55
  },
  {
    "id": "20260917-009",
    "image": "/photos/pics/20260917-009.png",
    "imageSmall": "/photos/optimized/20260917-009-480.webp",
    "imageMedium": "/photos/optimized/20260917-009-960.webp",
    "imageLarge": "/photos/optimized/20260917-009-1600.webp",
    "date": "2026-09-17",
    "order": 56
  },
  {
    "id": "20260917-008",
    "image": "/photos/pics/20260917-008.png",
    "imageSmall": "/photos/optimized/20260917-008-480.webp",
    "imageMedium": "/photos/optimized/20260917-008-960.webp",
    "imageLarge": "/photos/optimized/20260917-008-1600.webp",
    "date": "2026-09-17",
    "order": 57
  },
  {
    "id": "20260917-007",
    "image": "/photos/pics/20260917-007.png",
    "imageSmall": "/photos/optimized/20260917-007-480.webp",
    "imageMedium": "/photos/optimized/20260917-007-960.webp",
    "imageLarge": "/photos/optimized/20260917-007-1600.webp",
    "date": "2026-09-17",
    "order": 58
  },
  {
    "id": "20260917-006",
    "image": "/photos/pics/20260917-006.png",
    "imageSmall": "/photos/optimized/20260917-006-480.webp",
    "imageMedium": "/photos/optimized/20260917-006-960.webp",
    "imageLarge": "/photos/optimized/20260917-006-1600.webp",
    "date": "2026-09-17",
    "order": 59
  },
  {
    "id": "20260917-005",
    "image": "/photos/pics/20260917-005.png",
    "imageSmall": "/photos/optimized/20260917-005-480.webp",
    "imageMedium": "/photos/optimized/20260917-005-960.webp",
    "imageLarge": "/photos/optimized/20260917-005-1600.webp",
    "date": "2026-09-17",
    "order": 60
  },
  {
    "id": "20260917-004",
    "image": "/photos/pics/20260917-004.png",
    "imageSmall": "/photos/optimized/20260917-004-480.webp",
    "imageMedium": "/photos/optimized/20260917-004-960.webp",
    "imageLarge": "/photos/optimized/20260917-004-1600.webp",
    "date": "2026-09-17",
    "order": 61
  },
  {
    "id": "20260917-003",
    "image": "/photos/pics/20260917-003.png",
    "imageSmall": "/photos/optimized/20260917-003-480.webp",
    "imageMedium": "/photos/optimized/20260917-003-960.webp",
    "imageLarge": "/photos/optimized/20260917-003-1600.webp",
    "date": "2026-09-17",
    "order": 62
  },
  {
    "id": "20260917-002",
    "image": "/photos/pics/20260917-002.png",
    "imageSmall": "/photos/optimized/20260917-002-480.webp",
    "imageMedium": "/photos/optimized/20260917-002-960.webp",
    "imageLarge": "/photos/optimized/20260917-002-1600.webp",
    "date": "2026-09-17",
    "order": 63
  },
  {
    "id": "20260917-001",
    "image": "/photos/pics/20260917-001.png",
    "imageSmall": "/photos/optimized/20260917-001-480.webp",
    "imageMedium": "/photos/optimized/20260917-001-960.webp",
    "imageLarge": "/photos/optimized/20260917-001-1600.webp",
    "date": "2026-09-17",
    "order": 64
  },
  {
    "id": "20260916-028",
    "image": "/photos/pics/20260916-028.png",
    "imageSmall": "/photos/optimized/20260916-028-480.webp",
    "imageMedium": "/photos/optimized/20260916-028-960.webp",
    "imageLarge": "/photos/optimized/20260916-028-1600.webp",
    "date": "2026-09-16",
    "order": 65
  },
  {
    "id": "20260916-027",
    "image": "/photos/pics/20260916-027.png",
    "imageSmall": "/photos/optimized/20260916-027-480.webp",
    "imageMedium": "/photos/optimized/20260916-027-960.webp",
    "imageLarge": "/photos/optimized/20260916-027-1600.webp",
    "date": "2026-09-16",
    "order": 66
  },
  {
    "id": "20260916-026",
    "image": "/photos/pics/20260916-026.png",
    "imageSmall": "/photos/optimized/20260916-026-480.webp",
    "imageMedium": "/photos/optimized/20260916-026-960.webp",
    "imageLarge": "/photos/optimized/20260916-026-1600.webp",
    "date": "2026-09-16",
    "order": 67
  },
  {
    "id": "20260916-025",
    "image": "/photos/pics/20260916-025.png",
    "imageSmall": "/photos/optimized/20260916-025-480.webp",
    "imageMedium": "/photos/optimized/20260916-025-960.webp",
    "imageLarge": "/photos/optimized/20260916-025-1600.webp",
    "date": "2026-09-16",
    "order": 68
  },
  {
    "id": "20260916-024",
    "image": "/photos/pics/20260916-024.png",
    "imageSmall": "/photos/optimized/20260916-024-480.webp",
    "imageMedium": "/photos/optimized/20260916-024-960.webp",
    "imageLarge": "/photos/optimized/20260916-024-1600.webp",
    "date": "2026-09-16",
    "order": 69
  },
  {
    "id": "20260916-023",
    "image": "/photos/pics/20260916-023.png",
    "imageSmall": "/photos/optimized/20260916-023-480.webp",
    "imageMedium": "/photos/optimized/20260916-023-960.webp",
    "imageLarge": "/photos/optimized/20260916-023-1600.webp",
    "date": "2026-09-16",
    "order": 70
  },
  {
    "id": "20260916-022",
    "image": "/photos/pics/20260916-022.png",
    "imageSmall": "/photos/optimized/20260916-022-480.webp",
    "imageMedium": "/photos/optimized/20260916-022-960.webp",
    "imageLarge": "/photos/optimized/20260916-022-1600.webp",
    "date": "2026-09-16",
    "order": 71
  },
  {
    "id": "20260916-021",
    "image": "/photos/pics/20260916-021.png",
    "imageSmall": "/photos/optimized/20260916-021-480.webp",
    "imageMedium": "/photos/optimized/20260916-021-960.webp",
    "imageLarge": "/photos/optimized/20260916-021-1600.webp",
    "date": "2026-09-16",
    "order": 72
  },
  {
    "id": "20260916-020",
    "image": "/photos/pics/20260916-020.png",
    "imageSmall": "/photos/optimized/20260916-020-480.webp",
    "imageMedium": "/photos/optimized/20260916-020-960.webp",
    "imageLarge": "/photos/optimized/20260916-020-1600.webp",
    "date": "2026-09-16",
    "order": 73
  },
  {
    "id": "20260916-019",
    "image": "/photos/pics/20260916-019.png",
    "imageSmall": "/photos/optimized/20260916-019-480.webp",
    "imageMedium": "/photos/optimized/20260916-019-960.webp",
    "imageLarge": "/photos/optimized/20260916-019-1600.webp",
    "date": "2026-09-16",
    "order": 74
  },
  {
    "id": "20260916-018",
    "image": "/photos/pics/20260916-018.png",
    "imageSmall": "/photos/optimized/20260916-018-480.webp",
    "imageMedium": "/photos/optimized/20260916-018-960.webp",
    "imageLarge": "/photos/optimized/20260916-018-1600.webp",
    "date": "2026-09-16",
    "order": 75
  },
  {
    "id": "20260916-017",
    "image": "/photos/pics/20260916-017.png",
    "imageSmall": "/photos/optimized/20260916-017-480.webp",
    "imageMedium": "/photos/optimized/20260916-017-960.webp",
    "imageLarge": "/photos/optimized/20260916-017-1600.webp",
    "date": "2026-09-16",
    "order": 76
  },
  {
    "id": "20260916-016",
    "image": "/photos/pics/20260916-016.png",
    "imageSmall": "/photos/optimized/20260916-016-480.webp",
    "imageMedium": "/photos/optimized/20260916-016-960.webp",
    "imageLarge": "/photos/optimized/20260916-016-1600.webp",
    "date": "2026-09-16",
    "order": 77
  },
  {
    "id": "20260916-015",
    "image": "/photos/pics/20260916-015.png",
    "imageSmall": "/photos/optimized/20260916-015-480.webp",
    "imageMedium": "/photos/optimized/20260916-015-960.webp",
    "imageLarge": "/photos/optimized/20260916-015-1600.webp",
    "date": "2026-09-16",
    "order": 78
  },
  {
    "id": "20260916-014",
    "image": "/photos/pics/20260916-014.png",
    "imageSmall": "/photos/optimized/20260916-014-480.webp",
    "imageMedium": "/photos/optimized/20260916-014-960.webp",
    "imageLarge": "/photos/optimized/20260916-014-1600.webp",
    "date": "2026-09-16",
    "order": 79
  },
  {
    "id": "20260916-013",
    "image": "/photos/pics/20260916-013.png",
    "imageSmall": "/photos/optimized/20260916-013-480.webp",
    "imageMedium": "/photos/optimized/20260916-013-960.webp",
    "imageLarge": "/photos/optimized/20260916-013-1600.webp",
    "date": "2026-09-16",
    "order": 80
  },
  {
    "id": "20260916-012",
    "image": "/photos/pics/20260916-012.png",
    "imageSmall": "/photos/optimized/20260916-012-480.webp",
    "imageMedium": "/photos/optimized/20260916-012-960.webp",
    "imageLarge": "/photos/optimized/20260916-012-1600.webp",
    "date": "2026-09-16",
    "order": 81
  },
  {
    "id": "20260916-011",
    "image": "/photos/pics/20260916-011.png",
    "imageSmall": "/photos/optimized/20260916-011-480.webp",
    "imageMedium": "/photos/optimized/20260916-011-960.webp",
    "imageLarge": "/photos/optimized/20260916-011-1600.webp",
    "date": "2026-09-16",
    "order": 82
  },
  {
    "id": "20260916-010",
    "image": "/photos/pics/20260916-010.png",
    "imageSmall": "/photos/optimized/20260916-010-480.webp",
    "imageMedium": "/photos/optimized/20260916-010-960.webp",
    "imageLarge": "/photos/optimized/20260916-010-1600.webp",
    "date": "2026-09-16",
    "order": 83
  },
  {
    "id": "20260916-009",
    "image": "/photos/pics/20260916-009.png",
    "imageSmall": "/photos/optimized/20260916-009-480.webp",
    "imageMedium": "/photos/optimized/20260916-009-960.webp",
    "imageLarge": "/photos/optimized/20260916-009-1600.webp",
    "date": "2026-09-16",
    "order": 84
  },
  {
    "id": "20260916-008",
    "image": "/photos/pics/20260916-008.png",
    "imageSmall": "/photos/optimized/20260916-008-480.webp",
    "imageMedium": "/photos/optimized/20260916-008-960.webp",
    "imageLarge": "/photos/optimized/20260916-008-1600.webp",
    "date": "2026-09-16",
    "order": 85
  },
  {
    "id": "20260916-007",
    "image": "/photos/pics/20260916-007.png",
    "imageSmall": "/photos/optimized/20260916-007-480.webp",
    "imageMedium": "/photos/optimized/20260916-007-960.webp",
    "imageLarge": "/photos/optimized/20260916-007-1600.webp",
    "date": "2026-09-16",
    "order": 86
  },
  {
    "id": "20260916-006",
    "image": "/photos/pics/20260916-006.png",
    "imageSmall": "/photos/optimized/20260916-006-480.webp",
    "imageMedium": "/photos/optimized/20260916-006-960.webp",
    "imageLarge": "/photos/optimized/20260916-006-1600.webp",
    "date": "2026-09-16",
    "order": 87
  },
  {
    "id": "20260916-005",
    "image": "/photos/pics/20260916-005.png",
    "imageSmall": "/photos/optimized/20260916-005-480.webp",
    "imageMedium": "/photos/optimized/20260916-005-960.webp",
    "imageLarge": "/photos/optimized/20260916-005-1600.webp",
    "date": "2026-09-16",
    "order": 88
  },
  {
    "id": "20260916-004",
    "image": "/photos/pics/20260916-004.png",
    "imageSmall": "/photos/optimized/20260916-004-480.webp",
    "imageMedium": "/photos/optimized/20260916-004-960.webp",
    "imageLarge": "/photos/optimized/20260916-004-1600.webp",
    "date": "2026-09-16",
    "order": 89
  },
  {
    "id": "20260916-003",
    "image": "/photos/pics/20260916-003.png",
    "imageSmall": "/photos/optimized/20260916-003-480.webp",
    "imageMedium": "/photos/optimized/20260916-003-960.webp",
    "imageLarge": "/photos/optimized/20260916-003-1600.webp",
    "date": "2026-09-16",
    "order": 90
  },
  {
    "id": "20260916-002",
    "image": "/photos/pics/20260916-002.png",
    "imageSmall": "/photos/optimized/20260916-002-480.webp",
    "imageMedium": "/photos/optimized/20260916-002-960.webp",
    "imageLarge": "/photos/optimized/20260916-002-1600.webp",
    "date": "2026-09-16",
    "order": 91
  },
  {
    "id": "20260916-001",
    "image": "/photos/pics/20260916-001.png",
    "imageSmall": "/photos/optimized/20260916-001-480.webp",
    "imageMedium": "/photos/optimized/20260916-001-960.webp",
    "imageLarge": "/photos/optimized/20260916-001-1600.webp",
    "date": "2026-09-16",
    "order": 92
  },
  {
    "id": "20260915-075",
    "image": "/photos/pics/20260915-075.png",
    "imageSmall": "/photos/optimized/20260915-075-480.webp",
    "imageMedium": "/photos/optimized/20260915-075-960.webp",
    "imageLarge": "/photos/optimized/20260915-075-1600.webp",
    "date": "2026-09-15",
    "order": 93
  },
  {
    "id": "20260915-074",
    "image": "/photos/pics/20260915-074.png",
    "imageSmall": "/photos/optimized/20260915-074-480.webp",
    "imageMedium": "/photos/optimized/20260915-074-960.webp",
    "imageLarge": "/photos/optimized/20260915-074-1600.webp",
    "date": "2026-09-15",
    "order": 94
  },
  {
    "id": "20260915-073",
    "image": "/photos/pics/20260915-073.png",
    "imageSmall": "/photos/optimized/20260915-073-480.webp",
    "imageMedium": "/photos/optimized/20260915-073-960.webp",
    "imageLarge": "/photos/optimized/20260915-073-1600.webp",
    "date": "2026-09-15",
    "order": 95
  },
  {
    "id": "20260915-072",
    "image": "/photos/pics/20260915-072.png",
    "imageSmall": "/photos/optimized/20260915-072-480.webp",
    "imageMedium": "/photos/optimized/20260915-072-960.webp",
    "imageLarge": "/photos/optimized/20260915-072-1600.webp",
    "date": "2026-09-15",
    "order": 96
  },
  {
    "id": "20260915-071",
    "image": "/photos/pics/20260915-071.png",
    "imageSmall": "/photos/optimized/20260915-071-480.webp",
    "imageMedium": "/photos/optimized/20260915-071-960.webp",
    "imageLarge": "/photos/optimized/20260915-071-1600.webp",
    "date": "2026-09-15",
    "order": 97
  },
  {
    "id": "20260915-070",
    "image": "/photos/pics/20260915-070.png",
    "imageSmall": "/photos/optimized/20260915-070-480.webp",
    "imageMedium": "/photos/optimized/20260915-070-960.webp",
    "imageLarge": "/photos/optimized/20260915-070-1600.webp",
    "date": "2026-09-15",
    "order": 98
  },
  {
    "id": "20260915-069",
    "image": "/photos/pics/20260915-069.png",
    "imageSmall": "/photos/optimized/20260915-069-480.webp",
    "imageMedium": "/photos/optimized/20260915-069-960.webp",
    "imageLarge": "/photos/optimized/20260915-069-1600.webp",
    "date": "2026-09-15",
    "order": 99
  },
  {
    "id": "20260915-068",
    "image": "/photos/pics/20260915-068.png",
    "imageSmall": "/photos/optimized/20260915-068-480.webp",
    "imageMedium": "/photos/optimized/20260915-068-960.webp",
    "imageLarge": "/photos/optimized/20260915-068-1600.webp",
    "date": "2026-09-15",
    "order": 100
  },
  {
    "id": "20260915-067",
    "image": "/photos/pics/20260915-067.png",
    "imageSmall": "/photos/optimized/20260915-067-480.webp",
    "imageMedium": "/photos/optimized/20260915-067-960.webp",
    "imageLarge": "/photos/optimized/20260915-067-1600.webp",
    "date": "2026-09-15",
    "order": 101
  },
  {
    "id": "20260915-066",
    "image": "/photos/pics/20260915-066.png",
    "imageSmall": "/photos/optimized/20260915-066-480.webp",
    "imageMedium": "/photos/optimized/20260915-066-960.webp",
    "imageLarge": "/photos/optimized/20260915-066-1600.webp",
    "date": "2026-09-15",
    "order": 102
  },
  {
    "id": "20260915-065",
    "image": "/photos/pics/20260915-065.png",
    "imageSmall": "/photos/optimized/20260915-065-480.webp",
    "imageMedium": "/photos/optimized/20260915-065-960.webp",
    "imageLarge": "/photos/optimized/20260915-065-1600.webp",
    "date": "2026-09-15",
    "order": 103
  },
  {
    "id": "20260915-064",
    "image": "/photos/pics/20260915-064.png",
    "imageSmall": "/photos/optimized/20260915-064-480.webp",
    "imageMedium": "/photos/optimized/20260915-064-960.webp",
    "imageLarge": "/photos/optimized/20260915-064-1600.webp",
    "date": "2026-09-15",
    "order": 104
  },
  {
    "id": "20260915-063",
    "image": "/photos/pics/20260915-063.png",
    "imageSmall": "/photos/optimized/20260915-063-480.webp",
    "imageMedium": "/photos/optimized/20260915-063-960.webp",
    "imageLarge": "/photos/optimized/20260915-063-1600.webp",
    "date": "2026-09-15",
    "order": 105
  },
  {
    "id": "20260915-062",
    "image": "/photos/pics/20260915-062.png",
    "imageSmall": "/photos/optimized/20260915-062-480.webp",
    "imageMedium": "/photos/optimized/20260915-062-960.webp",
    "imageLarge": "/photos/optimized/20260915-062-1600.webp",
    "date": "2026-09-15",
    "order": 106
  },
  {
    "id": "20260915-061",
    "image": "/photos/pics/20260915-061.png",
    "imageSmall": "/photos/optimized/20260915-061-480.webp",
    "imageMedium": "/photos/optimized/20260915-061-960.webp",
    "imageLarge": "/photos/optimized/20260915-061-1600.webp",
    "date": "2026-09-15",
    "order": 107
  },
  {
    "id": "20260915-060",
    "image": "/photos/pics/20260915-060.png",
    "imageSmall": "/photos/optimized/20260915-060-480.webp",
    "imageMedium": "/photos/optimized/20260915-060-960.webp",
    "imageLarge": "/photos/optimized/20260915-060-1600.webp",
    "date": "2026-09-15",
    "order": 108
  },
  {
    "id": "20260915-059",
    "image": "/photos/pics/20260915-059.png",
    "imageSmall": "/photos/optimized/20260915-059-480.webp",
    "imageMedium": "/photos/optimized/20260915-059-960.webp",
    "imageLarge": "/photos/optimized/20260915-059-1600.webp",
    "date": "2026-09-15",
    "order": 109
  },
  {
    "id": "20260915-058",
    "image": "/photos/pics/20260915-058.png",
    "imageSmall": "/photos/optimized/20260915-058-480.webp",
    "imageMedium": "/photos/optimized/20260915-058-960.webp",
    "imageLarge": "/photos/optimized/20260915-058-1600.webp",
    "date": "2026-09-15",
    "order": 110
  },
  {
    "id": "20260915-057",
    "image": "/photos/pics/20260915-057.png",
    "imageSmall": "/photos/optimized/20260915-057-480.webp",
    "imageMedium": "/photos/optimized/20260915-057-960.webp",
    "imageLarge": "/photos/optimized/20260915-057-1600.webp",
    "date": "2026-09-15",
    "order": 111
  },
  {
    "id": "20260915-056",
    "image": "/photos/pics/20260915-056.png",
    "imageSmall": "/photos/optimized/20260915-056-480.webp",
    "imageMedium": "/photos/optimized/20260915-056-960.webp",
    "imageLarge": "/photos/optimized/20260915-056-1600.webp",
    "date": "2026-09-15",
    "order": 112
  },
  {
    "id": "20260915-055",
    "image": "/photos/pics/20260915-055.png",
    "imageSmall": "/photos/optimized/20260915-055-480.webp",
    "imageMedium": "/photos/optimized/20260915-055-960.webp",
    "imageLarge": "/photos/optimized/20260915-055-1600.webp",
    "date": "2026-09-15",
    "order": 113
  },
  {
    "id": "20260915-054",
    "image": "/photos/pics/20260915-054.png",
    "imageSmall": "/photos/optimized/20260915-054-480.webp",
    "imageMedium": "/photos/optimized/20260915-054-960.webp",
    "imageLarge": "/photos/optimized/20260915-054-1600.webp",
    "date": "2026-09-15",
    "order": 114
  },
  {
    "id": "20260915-053",
    "image": "/photos/pics/20260915-053.png",
    "imageSmall": "/photos/optimized/20260915-053-480.webp",
    "imageMedium": "/photos/optimized/20260915-053-960.webp",
    "imageLarge": "/photos/optimized/20260915-053-1600.webp",
    "date": "2026-09-15",
    "order": 115
  },
  {
    "id": "20260915-052",
    "image": "/photos/pics/20260915-052.png",
    "imageSmall": "/photos/optimized/20260915-052-480.webp",
    "imageMedium": "/photos/optimized/20260915-052-960.webp",
    "imageLarge": "/photos/optimized/20260915-052-1600.webp",
    "date": "2026-09-15",
    "order": 116
  },
  {
    "id": "20260915-051",
    "image": "/photos/pics/20260915-051.png",
    "imageSmall": "/photos/optimized/20260915-051-480.webp",
    "imageMedium": "/photos/optimized/20260915-051-960.webp",
    "imageLarge": "/photos/optimized/20260915-051-1600.webp",
    "date": "2026-09-15",
    "order": 117
  },
  {
    "id": "20260915-050",
    "image": "/photos/pics/20260915-050.png",
    "imageSmall": "/photos/optimized/20260915-050-480.webp",
    "imageMedium": "/photos/optimized/20260915-050-960.webp",
    "imageLarge": "/photos/optimized/20260915-050-1600.webp",
    "date": "2026-09-15",
    "order": 118
  },
  {
    "id": "20260915-049",
    "image": "/photos/pics/20260915-049.png",
    "imageSmall": "/photos/optimized/20260915-049-480.webp",
    "imageMedium": "/photos/optimized/20260915-049-960.webp",
    "imageLarge": "/photos/optimized/20260915-049-1600.webp",
    "date": "2026-09-15",
    "order": 119
  },
  {
    "id": "20260915-048",
    "image": "/photos/pics/20260915-048.png",
    "imageSmall": "/photos/optimized/20260915-048-480.webp",
    "imageMedium": "/photos/optimized/20260915-048-960.webp",
    "imageLarge": "/photos/optimized/20260915-048-1600.webp",
    "date": "2026-09-15",
    "order": 120
  },
  {
    "id": "20260915-047",
    "image": "/photos/pics/20260915-047.png",
    "imageSmall": "/photos/optimized/20260915-047-480.webp",
    "imageMedium": "/photos/optimized/20260915-047-960.webp",
    "imageLarge": "/photos/optimized/20260915-047-1600.webp",
    "date": "2026-09-15",
    "order": 121
  },
  {
    "id": "20260915-046",
    "image": "/photos/pics/20260915-046.png",
    "imageSmall": "/photos/optimized/20260915-046-480.webp",
    "imageMedium": "/photos/optimized/20260915-046-960.webp",
    "imageLarge": "/photos/optimized/20260915-046-1600.webp",
    "date": "2026-09-15",
    "order": 122
  },
  {
    "id": "20260915-045",
    "image": "/photos/pics/20260915-045.png",
    "imageSmall": "/photos/optimized/20260915-045-480.webp",
    "imageMedium": "/photos/optimized/20260915-045-960.webp",
    "imageLarge": "/photos/optimized/20260915-045-1600.webp",
    "date": "2026-09-15",
    "order": 123
  },
  {
    "id": "20260915-044",
    "image": "/photos/pics/20260915-044.png",
    "imageSmall": "/photos/optimized/20260915-044-480.webp",
    "imageMedium": "/photos/optimized/20260915-044-960.webp",
    "imageLarge": "/photos/optimized/20260915-044-1600.webp",
    "date": "2026-09-15",
    "order": 124
  },
  {
    "id": "20260915-043",
    "image": "/photos/pics/20260915-043.png",
    "imageSmall": "/photos/optimized/20260915-043-480.webp",
    "imageMedium": "/photos/optimized/20260915-043-960.webp",
    "imageLarge": "/photos/optimized/20260915-043-1600.webp",
    "date": "2026-09-15",
    "order": 125
  },
  {
    "id": "20260915-042",
    "image": "/photos/pics/20260915-042.png",
    "imageSmall": "/photos/optimized/20260915-042-480.webp",
    "imageMedium": "/photos/optimized/20260915-042-960.webp",
    "imageLarge": "/photos/optimized/20260915-042-1600.webp",
    "date": "2026-09-15",
    "order": 126
  },
  {
    "id": "20260915-041",
    "image": "/photos/pics/20260915-041.png",
    "imageSmall": "/photos/optimized/20260915-041-480.webp",
    "imageMedium": "/photos/optimized/20260915-041-960.webp",
    "imageLarge": "/photos/optimized/20260915-041-1600.webp",
    "date": "2026-09-15",
    "order": 127
  },
  {
    "id": "20260915-040",
    "image": "/photos/pics/20260915-040.png",
    "imageSmall": "/photos/optimized/20260915-040-480.webp",
    "imageMedium": "/photos/optimized/20260915-040-960.webp",
    "imageLarge": "/photos/optimized/20260915-040-1600.webp",
    "date": "2026-09-15",
    "order": 128
  },
  {
    "id": "20260915-039",
    "image": "/photos/pics/20260915-039.png",
    "imageSmall": "/photos/optimized/20260915-039-480.webp",
    "imageMedium": "/photos/optimized/20260915-039-960.webp",
    "imageLarge": "/photos/optimized/20260915-039-1600.webp",
    "date": "2026-09-15",
    "order": 129
  },
  {
    "id": "20260915-038",
    "image": "/photos/pics/20260915-038.png",
    "imageSmall": "/photos/optimized/20260915-038-480.webp",
    "imageMedium": "/photos/optimized/20260915-038-960.webp",
    "imageLarge": "/photos/optimized/20260915-038-1600.webp",
    "date": "2026-09-15",
    "order": 130
  },
  {
    "id": "20260915-037",
    "image": "/photos/pics/20260915-037.png",
    "imageSmall": "/photos/optimized/20260915-037-480.webp",
    "imageMedium": "/photos/optimized/20260915-037-960.webp",
    "imageLarge": "/photos/optimized/20260915-037-1600.webp",
    "date": "2026-09-15",
    "order": 131
  },
  {
    "id": "20260915-036",
    "image": "/photos/pics/20260915-036.png",
    "imageSmall": "/photos/optimized/20260915-036-480.webp",
    "imageMedium": "/photos/optimized/20260915-036-960.webp",
    "imageLarge": "/photos/optimized/20260915-036-1600.webp",
    "date": "2026-09-15",
    "order": 132
  },
  {
    "id": "20260915-035",
    "image": "/photos/pics/20260915-035.png",
    "imageSmall": "/photos/optimized/20260915-035-480.webp",
    "imageMedium": "/photos/optimized/20260915-035-960.webp",
    "imageLarge": "/photos/optimized/20260915-035-1600.webp",
    "date": "2026-09-15",
    "order": 133
  },
  {
    "id": "20260915-034",
    "image": "/photos/pics/20260915-034.png",
    "imageSmall": "/photos/optimized/20260915-034-480.webp",
    "imageMedium": "/photos/optimized/20260915-034-960.webp",
    "imageLarge": "/photos/optimized/20260915-034-1600.webp",
    "date": "2026-09-15",
    "order": 134
  },
  {
    "id": "20260915-033",
    "image": "/photos/pics/20260915-033.png",
    "imageSmall": "/photos/optimized/20260915-033-480.webp",
    "imageMedium": "/photos/optimized/20260915-033-960.webp",
    "imageLarge": "/photos/optimized/20260915-033-1600.webp",
    "date": "2026-09-15",
    "order": 135
  },
  {
    "id": "20260915-032",
    "image": "/photos/pics/20260915-032.png",
    "imageSmall": "/photos/optimized/20260915-032-480.webp",
    "imageMedium": "/photos/optimized/20260915-032-960.webp",
    "imageLarge": "/photos/optimized/20260915-032-1600.webp",
    "date": "2026-09-15",
    "order": 136
  },
  {
    "id": "20260915-031",
    "image": "/photos/pics/20260915-031.png",
    "imageSmall": "/photos/optimized/20260915-031-480.webp",
    "imageMedium": "/photos/optimized/20260915-031-960.webp",
    "imageLarge": "/photos/optimized/20260915-031-1600.webp",
    "date": "2026-09-15",
    "order": 137
  },
  {
    "id": "20260915-030",
    "image": "/photos/pics/20260915-030.png",
    "imageSmall": "/photos/optimized/20260915-030-480.webp",
    "imageMedium": "/photos/optimized/20260915-030-960.webp",
    "imageLarge": "/photos/optimized/20260915-030-1600.webp",
    "date": "2026-09-15",
    "order": 138
  },
  {
    "id": "20260915-029",
    "image": "/photos/pics/20260915-029.png",
    "imageSmall": "/photos/optimized/20260915-029-480.webp",
    "imageMedium": "/photos/optimized/20260915-029-960.webp",
    "imageLarge": "/photos/optimized/20260915-029-1600.webp",
    "date": "2026-09-15",
    "order": 139
  },
  {
    "id": "20260915-028",
    "image": "/photos/pics/20260915-028.png",
    "imageSmall": "/photos/optimized/20260915-028-480.webp",
    "imageMedium": "/photos/optimized/20260915-028-960.webp",
    "imageLarge": "/photos/optimized/20260915-028-1600.webp",
    "date": "2026-09-15",
    "order": 140
  },
  {
    "id": "20260915-027",
    "image": "/photos/pics/20260915-027.png",
    "imageSmall": "/photos/optimized/20260915-027-480.webp",
    "imageMedium": "/photos/optimized/20260915-027-960.webp",
    "imageLarge": "/photos/optimized/20260915-027-1600.webp",
    "date": "2026-09-15",
    "order": 141
  },
  {
    "id": "20260915-026",
    "image": "/photos/pics/20260915-026.png",
    "imageSmall": "/photos/optimized/20260915-026-480.webp",
    "imageMedium": "/photos/optimized/20260915-026-960.webp",
    "imageLarge": "/photos/optimized/20260915-026-1600.webp",
    "date": "2026-09-15",
    "order": 142
  },
  {
    "id": "20260915-025",
    "image": "/photos/pics/20260915-025.png",
    "imageSmall": "/photos/optimized/20260915-025-480.webp",
    "imageMedium": "/photos/optimized/20260915-025-960.webp",
    "imageLarge": "/photos/optimized/20260915-025-1600.webp",
    "date": "2026-09-15",
    "order": 143
  },
  {
    "id": "20260915-024",
    "image": "/photos/pics/20260915-024.png",
    "imageSmall": "/photos/optimized/20260915-024-480.webp",
    "imageMedium": "/photos/optimized/20260915-024-960.webp",
    "imageLarge": "/photos/optimized/20260915-024-1600.webp",
    "date": "2026-09-15",
    "order": 144
  },
  {
    "id": "20260915-023",
    "image": "/photos/pics/20260915-023.png",
    "imageSmall": "/photos/optimized/20260915-023-480.webp",
    "imageMedium": "/photos/optimized/20260915-023-960.webp",
    "imageLarge": "/photos/optimized/20260915-023-1600.webp",
    "date": "2026-09-15",
    "order": 145
  },
  {
    "id": "20260915-022",
    "image": "/photos/pics/20260915-022.png",
    "imageSmall": "/photos/optimized/20260915-022-480.webp",
    "imageMedium": "/photos/optimized/20260915-022-960.webp",
    "imageLarge": "/photos/optimized/20260915-022-1600.webp",
    "date": "2026-09-15",
    "order": 146
  },
  {
    "id": "20260915-021",
    "image": "/photos/pics/20260915-021.png",
    "imageSmall": "/photos/optimized/20260915-021-480.webp",
    "imageMedium": "/photos/optimized/20260915-021-960.webp",
    "imageLarge": "/photos/optimized/20260915-021-1600.webp",
    "date": "2026-09-15",
    "order": 147
  },
  {
    "id": "20260915-020",
    "image": "/photos/pics/20260915-020.png",
    "imageSmall": "/photos/optimized/20260915-020-480.webp",
    "imageMedium": "/photos/optimized/20260915-020-960.webp",
    "imageLarge": "/photos/optimized/20260915-020-1600.webp",
    "date": "2026-09-15",
    "order": 148
  },
  {
    "id": "20260915-019",
    "image": "/photos/pics/20260915-019.png",
    "imageSmall": "/photos/optimized/20260915-019-480.webp",
    "imageMedium": "/photos/optimized/20260915-019-960.webp",
    "imageLarge": "/photos/optimized/20260915-019-1600.webp",
    "date": "2026-09-15",
    "order": 149
  },
  {
    "id": "20260915-018",
    "image": "/photos/pics/20260915-018.png",
    "imageSmall": "/photos/optimized/20260915-018-480.webp",
    "imageMedium": "/photos/optimized/20260915-018-960.webp",
    "imageLarge": "/photos/optimized/20260915-018-1600.webp",
    "date": "2026-09-15",
    "order": 150
  },
  {
    "id": "20260915-017",
    "image": "/photos/pics/20260915-017.png",
    "imageSmall": "/photos/optimized/20260915-017-480.webp",
    "imageMedium": "/photos/optimized/20260915-017-960.webp",
    "imageLarge": "/photos/optimized/20260915-017-1600.webp",
    "date": "2026-09-15",
    "order": 151
  },
  {
    "id": "20260915-016",
    "image": "/photos/pics/20260915-016.png",
    "imageSmall": "/photos/optimized/20260915-016-480.webp",
    "imageMedium": "/photos/optimized/20260915-016-960.webp",
    "imageLarge": "/photos/optimized/20260915-016-1600.webp",
    "date": "2026-09-15",
    "order": 152
  },
  {
    "id": "20260915-015",
    "image": "/photos/pics/20260915-015.png",
    "imageSmall": "/photos/optimized/20260915-015-480.webp",
    "imageMedium": "/photos/optimized/20260915-015-960.webp",
    "imageLarge": "/photos/optimized/20260915-015-1600.webp",
    "date": "2026-09-15",
    "order": 153
  },
  {
    "id": "20260915-014",
    "image": "/photos/pics/20260915-014.png",
    "imageSmall": "/photos/optimized/20260915-014-480.webp",
    "imageMedium": "/photos/optimized/20260915-014-960.webp",
    "imageLarge": "/photos/optimized/20260915-014-1600.webp",
    "date": "2026-09-15",
    "order": 154
  },
  {
    "id": "20260915-013",
    "image": "/photos/pics/20260915-013.png",
    "imageSmall": "/photos/optimized/20260915-013-480.webp",
    "imageMedium": "/photos/optimized/20260915-013-960.webp",
    "imageLarge": "/photos/optimized/20260915-013-1600.webp",
    "date": "2026-09-15",
    "order": 155
  },
  {
    "id": "20260915-012",
    "image": "/photos/pics/20260915-012.png",
    "imageSmall": "/photos/optimized/20260915-012-480.webp",
    "imageMedium": "/photos/optimized/20260915-012-960.webp",
    "imageLarge": "/photos/optimized/20260915-012-1600.webp",
    "date": "2026-09-15",
    "order": 156
  },
  {
    "id": "20260915-011",
    "image": "/photos/pics/20260915-011.png",
    "imageSmall": "/photos/optimized/20260915-011-480.webp",
    "imageMedium": "/photos/optimized/20260915-011-960.webp",
    "imageLarge": "/photos/optimized/20260915-011-1600.webp",
    "date": "2026-09-15",
    "order": 157
  },
  {
    "id": "20260915-010",
    "image": "/photos/pics/20260915-010.png",
    "imageSmall": "/photos/optimized/20260915-010-480.webp",
    "imageMedium": "/photos/optimized/20260915-010-960.webp",
    "imageLarge": "/photos/optimized/20260915-010-1600.webp",
    "date": "2026-09-15",
    "order": 158
  },
  {
    "id": "20260915-009",
    "image": "/photos/pics/20260915-009.png",
    "imageSmall": "/photos/optimized/20260915-009-480.webp",
    "imageMedium": "/photos/optimized/20260915-009-960.webp",
    "imageLarge": "/photos/optimized/20260915-009-1600.webp",
    "date": "2026-09-15",
    "order": 159
  },
  {
    "id": "20260915-008",
    "image": "/photos/pics/20260915-008.png",
    "imageSmall": "/photos/optimized/20260915-008-480.webp",
    "imageMedium": "/photos/optimized/20260915-008-960.webp",
    "imageLarge": "/photos/optimized/20260915-008-1600.webp",
    "date": "2026-09-15",
    "order": 160
  },
  {
    "id": "20260915-007",
    "image": "/photos/pics/20260915-007.png",
    "imageSmall": "/photos/optimized/20260915-007-480.webp",
    "imageMedium": "/photos/optimized/20260915-007-960.webp",
    "imageLarge": "/photos/optimized/20260915-007-1600.webp",
    "date": "2026-09-15",
    "order": 161
  },
  {
    "id": "20260915-006",
    "image": "/photos/pics/20260915-006.png",
    "imageSmall": "/photos/optimized/20260915-006-480.webp",
    "imageMedium": "/photos/optimized/20260915-006-960.webp",
    "imageLarge": "/photos/optimized/20260915-006-1600.webp",
    "date": "2026-09-15",
    "order": 162
  },
  {
    "id": "20260915-005",
    "image": "/photos/pics/20260915-005.png",
    "imageSmall": "/photos/optimized/20260915-005-480.webp",
    "imageMedium": "/photos/optimized/20260915-005-960.webp",
    "imageLarge": "/photos/optimized/20260915-005-1600.webp",
    "date": "2026-09-15",
    "order": 163
  },
  {
    "id": "20260915-004",
    "image": "/photos/pics/20260915-004.png",
    "imageSmall": "/photos/optimized/20260915-004-480.webp",
    "imageMedium": "/photos/optimized/20260915-004-960.webp",
    "imageLarge": "/photos/optimized/20260915-004-1600.webp",
    "date": "2026-09-15",
    "order": 164
  },
  {
    "id": "20260915-003",
    "image": "/photos/pics/20260915-003.png",
    "imageSmall": "/photos/optimized/20260915-003-480.webp",
    "imageMedium": "/photos/optimized/20260915-003-960.webp",
    "imageLarge": "/photos/optimized/20260915-003-1600.webp",
    "date": "2026-09-15",
    "order": 165
  },
  {
    "id": "20260915-002",
    "image": "/photos/pics/20260915-002.png",
    "imageSmall": "/photos/optimized/20260915-002-480.webp",
    "imageMedium": "/photos/optimized/20260915-002-960.webp",
    "imageLarge": "/photos/optimized/20260915-002-1600.webp",
    "date": "2026-09-15",
    "order": 166
  },
  {
    "id": "20260915-001",
    "image": "/photos/pics/20260915-001.png",
    "imageSmall": "/photos/optimized/20260915-001-480.webp",
    "imageMedium": "/photos/optimized/20260915-001-960.webp",
    "imageLarge": "/photos/optimized/20260915-001-1600.webp",
    "date": "2026-09-15",
    "order": 167
  },
  {
    "id": "20260914-036",
    "image": "/photos/pics/20260914-036.png",
    "imageSmall": "/photos/optimized/20260914-036-480.webp",
    "imageMedium": "/photos/optimized/20260914-036-960.webp",
    "imageLarge": "/photos/optimized/20260914-036-1600.webp",
    "date": "2026-09-14",
    "order": 168
  },
  {
    "id": "20260914-035",
    "image": "/photos/pics/20260914-035.png",
    "imageSmall": "/photos/optimized/20260914-035-480.webp",
    "imageMedium": "/photos/optimized/20260914-035-960.webp",
    "imageLarge": "/photos/optimized/20260914-035-1600.webp",
    "date": "2026-09-14",
    "order": 169
  },
  {
    "id": "20260914-034",
    "image": "/photos/pics/20260914-034.png",
    "imageSmall": "/photos/optimized/20260914-034-480.webp",
    "imageMedium": "/photos/optimized/20260914-034-960.webp",
    "imageLarge": "/photos/optimized/20260914-034-1600.webp",
    "date": "2026-09-14",
    "order": 170
  },
  {
    "id": "20260914-033",
    "image": "/photos/pics/20260914-033.png",
    "imageSmall": "/photos/optimized/20260914-033-480.webp",
    "imageMedium": "/photos/optimized/20260914-033-960.webp",
    "imageLarge": "/photos/optimized/20260914-033-1600.webp",
    "date": "2026-09-14",
    "order": 171
  },
  {
    "id": "20260914-032",
    "image": "/photos/pics/20260914-032.png",
    "imageSmall": "/photos/optimized/20260914-032-480.webp",
    "imageMedium": "/photos/optimized/20260914-032-960.webp",
    "imageLarge": "/photos/optimized/20260914-032-1600.webp",
    "date": "2026-09-14",
    "order": 172
  },
  {
    "id": "20260914-031",
    "image": "/photos/pics/20260914-031.png",
    "imageSmall": "/photos/optimized/20260914-031-480.webp",
    "imageMedium": "/photos/optimized/20260914-031-960.webp",
    "imageLarge": "/photos/optimized/20260914-031-1600.webp",
    "date": "2026-09-14",
    "order": 173
  },
  {
    "id": "20260914-030",
    "image": "/photos/pics/20260914-030.png",
    "imageSmall": "/photos/optimized/20260914-030-480.webp",
    "imageMedium": "/photos/optimized/20260914-030-960.webp",
    "imageLarge": "/photos/optimized/20260914-030-1600.webp",
    "date": "2026-09-14",
    "order": 174
  },
  {
    "id": "20260914-029",
    "image": "/photos/pics/20260914-029.png",
    "imageSmall": "/photos/optimized/20260914-029-480.webp",
    "imageMedium": "/photos/optimized/20260914-029-960.webp",
    "imageLarge": "/photos/optimized/20260914-029-1600.webp",
    "date": "2026-09-14",
    "order": 175
  },
  {
    "id": "20260914-028",
    "image": "/photos/pics/20260914-028.png",
    "imageSmall": "/photos/optimized/20260914-028-480.webp",
    "imageMedium": "/photos/optimized/20260914-028-960.webp",
    "imageLarge": "/photos/optimized/20260914-028-1600.webp",
    "date": "2026-09-14",
    "order": 176
  },
  {
    "id": "20260914-027",
    "image": "/photos/pics/20260914-027.png",
    "imageSmall": "/photos/optimized/20260914-027-480.webp",
    "imageMedium": "/photos/optimized/20260914-027-960.webp",
    "imageLarge": "/photos/optimized/20260914-027-1600.webp",
    "date": "2026-09-14",
    "order": 177
  },
  {
    "id": "20260914-026",
    "image": "/photos/pics/20260914-026.png",
    "imageSmall": "/photos/optimized/20260914-026-480.webp",
    "imageMedium": "/photos/optimized/20260914-026-960.webp",
    "imageLarge": "/photos/optimized/20260914-026-1600.webp",
    "date": "2026-09-14",
    "order": 178
  },
  {
    "id": "20260914-025",
    "image": "/photos/pics/20260914-025.png",
    "imageSmall": "/photos/optimized/20260914-025-480.webp",
    "imageMedium": "/photos/optimized/20260914-025-960.webp",
    "imageLarge": "/photos/optimized/20260914-025-1600.webp",
    "date": "2026-09-14",
    "order": 179
  },
  {
    "id": "20260914-024",
    "image": "/photos/pics/20260914-024.png",
    "imageSmall": "/photos/optimized/20260914-024-480.webp",
    "imageMedium": "/photos/optimized/20260914-024-960.webp",
    "imageLarge": "/photos/optimized/20260914-024-1600.webp",
    "date": "2026-09-14",
    "order": 180
  },
  {
    "id": "20260914-023",
    "image": "/photos/pics/20260914-023.png",
    "imageSmall": "/photos/optimized/20260914-023-480.webp",
    "imageMedium": "/photos/optimized/20260914-023-960.webp",
    "imageLarge": "/photos/optimized/20260914-023-1600.webp",
    "date": "2026-09-14",
    "order": 181
  },
  {
    "id": "20260914-022",
    "image": "/photos/pics/20260914-022.png",
    "imageSmall": "/photos/optimized/20260914-022-480.webp",
    "imageMedium": "/photos/optimized/20260914-022-960.webp",
    "imageLarge": "/photos/optimized/20260914-022-1600.webp",
    "date": "2026-09-14",
    "order": 182
  },
  {
    "id": "20260914-021",
    "image": "/photos/pics/20260914-021.png",
    "imageSmall": "/photos/optimized/20260914-021-480.webp",
    "imageMedium": "/photos/optimized/20260914-021-960.webp",
    "imageLarge": "/photos/optimized/20260914-021-1600.webp",
    "date": "2026-09-14",
    "order": 183
  },
  {
    "id": "20260914-020",
    "image": "/photos/pics/20260914-020.png",
    "imageSmall": "/photos/optimized/20260914-020-480.webp",
    "imageMedium": "/photos/optimized/20260914-020-960.webp",
    "imageLarge": "/photos/optimized/20260914-020-1600.webp",
    "date": "2026-09-14",
    "order": 184
  },
  {
    "id": "20260914-019",
    "image": "/photos/pics/20260914-019.png",
    "imageSmall": "/photos/optimized/20260914-019-480.webp",
    "imageMedium": "/photos/optimized/20260914-019-960.webp",
    "imageLarge": "/photos/optimized/20260914-019-1600.webp",
    "date": "2026-09-14",
    "order": 185
  },
  {
    "id": "20260914-018",
    "image": "/photos/pics/20260914-018.png",
    "imageSmall": "/photos/optimized/20260914-018-480.webp",
    "imageMedium": "/photos/optimized/20260914-018-960.webp",
    "imageLarge": "/photos/optimized/20260914-018-1600.webp",
    "date": "2026-09-14",
    "order": 186
  },
  {
    "id": "20260914-017",
    "image": "/photos/pics/20260914-017.png",
    "imageSmall": "/photos/optimized/20260914-017-480.webp",
    "imageMedium": "/photos/optimized/20260914-017-960.webp",
    "imageLarge": "/photos/optimized/20260914-017-1600.webp",
    "date": "2026-09-14",
    "order": 187
  },
  {
    "id": "20260914-016",
    "image": "/photos/pics/20260914-016.png",
    "imageSmall": "/photos/optimized/20260914-016-480.webp",
    "imageMedium": "/photos/optimized/20260914-016-960.webp",
    "imageLarge": "/photos/optimized/20260914-016-1600.webp",
    "date": "2026-09-14",
    "order": 188
  },
  {
    "id": "20260914-015",
    "image": "/photos/pics/20260914-015.png",
    "imageSmall": "/photos/optimized/20260914-015-480.webp",
    "imageMedium": "/photos/optimized/20260914-015-960.webp",
    "imageLarge": "/photos/optimized/20260914-015-1600.webp",
    "date": "2026-09-14",
    "order": 189
  },
  {
    "id": "20260914-014",
    "image": "/photos/pics/20260914-014.png",
    "imageSmall": "/photos/optimized/20260914-014-480.webp",
    "imageMedium": "/photos/optimized/20260914-014-960.webp",
    "imageLarge": "/photos/optimized/20260914-014-1600.webp",
    "date": "2026-09-14",
    "order": 190
  },
  {
    "id": "20260914-013",
    "image": "/photos/pics/20260914-013.png",
    "imageSmall": "/photos/optimized/20260914-013-480.webp",
    "imageMedium": "/photos/optimized/20260914-013-960.webp",
    "imageLarge": "/photos/optimized/20260914-013-1600.webp",
    "date": "2026-09-14",
    "order": 191
  },
  {
    "id": "20260914-012",
    "image": "/photos/pics/20260914-012.png",
    "imageSmall": "/photos/optimized/20260914-012-480.webp",
    "imageMedium": "/photos/optimized/20260914-012-960.webp",
    "imageLarge": "/photos/optimized/20260914-012-1600.webp",
    "date": "2026-09-14",
    "order": 192
  },
  {
    "id": "20260914-011",
    "image": "/photos/pics/20260914-011.png",
    "imageSmall": "/photos/optimized/20260914-011-480.webp",
    "imageMedium": "/photos/optimized/20260914-011-960.webp",
    "imageLarge": "/photos/optimized/20260914-011-1600.webp",
    "date": "2026-09-14",
    "order": 193
  },
  {
    "id": "20260914-010",
    "image": "/photos/pics/20260914-010.png",
    "imageSmall": "/photos/optimized/20260914-010-480.webp",
    "imageMedium": "/photos/optimized/20260914-010-960.webp",
    "imageLarge": "/photos/optimized/20260914-010-1600.webp",
    "date": "2026-09-14",
    "order": 194
  },
  {
    "id": "20260914-009",
    "image": "/photos/pics/20260914-009.png",
    "imageSmall": "/photos/optimized/20260914-009-480.webp",
    "imageMedium": "/photos/optimized/20260914-009-960.webp",
    "imageLarge": "/photos/optimized/20260914-009-1600.webp",
    "date": "2026-09-14",
    "order": 195
  },
  {
    "id": "20260914-008",
    "image": "/photos/pics/20260914-008.png",
    "imageSmall": "/photos/optimized/20260914-008-480.webp",
    "imageMedium": "/photos/optimized/20260914-008-960.webp",
    "imageLarge": "/photos/optimized/20260914-008-1600.webp",
    "date": "2026-09-14",
    "order": 196
  },
  {
    "id": "20260914-007",
    "image": "/photos/pics/20260914-007.png",
    "imageSmall": "/photos/optimized/20260914-007-480.webp",
    "imageMedium": "/photos/optimized/20260914-007-960.webp",
    "imageLarge": "/photos/optimized/20260914-007-1600.webp",
    "date": "2026-09-14",
    "order": 197
  },
  {
    "id": "20260914-006",
    "image": "/photos/pics/20260914-006.png",
    "imageSmall": "/photos/optimized/20260914-006-480.webp",
    "imageMedium": "/photos/optimized/20260914-006-960.webp",
    "imageLarge": "/photos/optimized/20260914-006-1600.webp",
    "date": "2026-09-14",
    "order": 198
  },
  {
    "id": "20260914-005",
    "image": "/photos/pics/20260914-005.png",
    "imageSmall": "/photos/optimized/20260914-005-480.webp",
    "imageMedium": "/photos/optimized/20260914-005-960.webp",
    "imageLarge": "/photos/optimized/20260914-005-1600.webp",
    "date": "2026-09-14",
    "order": 199
  },
  {
    "id": "20260914-004",
    "image": "/photos/pics/20260914-004.png",
    "imageSmall": "/photos/optimized/20260914-004-480.webp",
    "imageMedium": "/photos/optimized/20260914-004-960.webp",
    "imageLarge": "/photos/optimized/20260914-004-1600.webp",
    "date": "2026-09-14",
    "order": 200
  },
  {
    "id": "20260914-003",
    "image": "/photos/pics/20260914-003.png",
    "imageSmall": "/photos/optimized/20260914-003-480.webp",
    "imageMedium": "/photos/optimized/20260914-003-960.webp",
    "imageLarge": "/photos/optimized/20260914-003-1600.webp",
    "date": "2026-09-14",
    "order": 201
  },
  {
    "id": "20260914-002",
    "image": "/photos/pics/20260914-002.png",
    "imageSmall": "/photos/optimized/20260914-002-480.webp",
    "imageMedium": "/photos/optimized/20260914-002-960.webp",
    "imageLarge": "/photos/optimized/20260914-002-1600.webp",
    "date": "2026-09-14",
    "order": 202
  },
  {
    "id": "20260914-001",
    "image": "/photos/pics/20260914-001.png",
    "imageSmall": "/photos/optimized/20260914-001-480.webp",
    "imageMedium": "/photos/optimized/20260914-001-960.webp",
    "imageLarge": "/photos/optimized/20260914-001-1600.webp",
    "date": "2026-09-14",
    "order": 203
  },
  {
    "id": "20260913-047",
    "image": "/photos/pics/20260913-047.png",
    "imageSmall": "/photos/optimized/20260913-047-480.webp",
    "imageMedium": "/photos/optimized/20260913-047-960.webp",
    "imageLarge": "/photos/optimized/20260913-047-1600.webp",
    "date": "2026-09-13",
    "order": 204
  },
  {
    "id": "20260913-046",
    "image": "/photos/pics/20260913-046.png",
    "imageSmall": "/photos/optimized/20260913-046-480.webp",
    "imageMedium": "/photos/optimized/20260913-046-960.webp",
    "imageLarge": "/photos/optimized/20260913-046-1600.webp",
    "date": "2026-09-13",
    "order": 205
  },
  {
    "id": "20260913-045",
    "image": "/photos/pics/20260913-045.png",
    "imageSmall": "/photos/optimized/20260913-045-480.webp",
    "imageMedium": "/photos/optimized/20260913-045-960.webp",
    "imageLarge": "/photos/optimized/20260913-045-1600.webp",
    "date": "2026-09-13",
    "order": 206
  },
  {
    "id": "20260913-044",
    "image": "/photos/pics/20260913-044.png",
    "imageSmall": "/photos/optimized/20260913-044-480.webp",
    "imageMedium": "/photos/optimized/20260913-044-960.webp",
    "imageLarge": "/photos/optimized/20260913-044-1600.webp",
    "date": "2026-09-13",
    "order": 207
  },
  {
    "id": "20260913-043",
    "image": "/photos/pics/20260913-043.png",
    "imageSmall": "/photos/optimized/20260913-043-480.webp",
    "imageMedium": "/photos/optimized/20260913-043-960.webp",
    "imageLarge": "/photos/optimized/20260913-043-1600.webp",
    "date": "2026-09-13",
    "order": 208
  },
  {
    "id": "20260913-042",
    "image": "/photos/pics/20260913-042.png",
    "imageSmall": "/photos/optimized/20260913-042-480.webp",
    "imageMedium": "/photos/optimized/20260913-042-960.webp",
    "imageLarge": "/photos/optimized/20260913-042-1600.webp",
    "date": "2026-09-13",
    "order": 209
  },
  {
    "id": "20260913-041",
    "image": "/photos/pics/20260913-041.png",
    "imageSmall": "/photos/optimized/20260913-041-480.webp",
    "imageMedium": "/photos/optimized/20260913-041-960.webp",
    "imageLarge": "/photos/optimized/20260913-041-1600.webp",
    "date": "2026-09-13",
    "order": 210
  },
  {
    "id": "20260913-040",
    "image": "/photos/pics/20260913-040.png",
    "imageSmall": "/photos/optimized/20260913-040-480.webp",
    "imageMedium": "/photos/optimized/20260913-040-960.webp",
    "imageLarge": "/photos/optimized/20260913-040-1600.webp",
    "date": "2026-09-13",
    "order": 211
  },
  {
    "id": "20260913-039",
    "image": "/photos/pics/20260913-039.png",
    "imageSmall": "/photos/optimized/20260913-039-480.webp",
    "imageMedium": "/photos/optimized/20260913-039-960.webp",
    "imageLarge": "/photos/optimized/20260913-039-1600.webp",
    "date": "2026-09-13",
    "order": 212
  },
  {
    "id": "20260913-038",
    "image": "/photos/pics/20260913-038.png",
    "imageSmall": "/photos/optimized/20260913-038-480.webp",
    "imageMedium": "/photos/optimized/20260913-038-960.webp",
    "imageLarge": "/photos/optimized/20260913-038-1600.webp",
    "date": "2026-09-13",
    "order": 213
  },
  {
    "id": "20260913-037",
    "image": "/photos/pics/20260913-037.png",
    "imageSmall": "/photos/optimized/20260913-037-480.webp",
    "imageMedium": "/photos/optimized/20260913-037-960.webp",
    "imageLarge": "/photos/optimized/20260913-037-1600.webp",
    "date": "2026-09-13",
    "order": 214
  },
  {
    "id": "20260913-036",
    "image": "/photos/pics/20260913-036.png",
    "imageSmall": "/photos/optimized/20260913-036-480.webp",
    "imageMedium": "/photos/optimized/20260913-036-960.webp",
    "imageLarge": "/photos/optimized/20260913-036-1600.webp",
    "date": "2026-09-13",
    "order": 215
  },
  {
    "id": "20260913-035",
    "image": "/photos/pics/20260913-035.png",
    "imageSmall": "/photos/optimized/20260913-035-480.webp",
    "imageMedium": "/photos/optimized/20260913-035-960.webp",
    "imageLarge": "/photos/optimized/20260913-035-1600.webp",
    "date": "2026-09-13",
    "order": 216
  },
  {
    "id": "20260913-034",
    "image": "/photos/pics/20260913-034.png",
    "imageSmall": "/photos/optimized/20260913-034-480.webp",
    "imageMedium": "/photos/optimized/20260913-034-960.webp",
    "imageLarge": "/photos/optimized/20260913-034-1600.webp",
    "date": "2026-09-13",
    "order": 217
  },
  {
    "id": "20260913-033",
    "image": "/photos/pics/20260913-033.png",
    "imageSmall": "/photos/optimized/20260913-033-480.webp",
    "imageMedium": "/photos/optimized/20260913-033-960.webp",
    "imageLarge": "/photos/optimized/20260913-033-1600.webp",
    "date": "2026-09-13",
    "order": 218
  },
  {
    "id": "20260913-032",
    "image": "/photos/pics/20260913-032.png",
    "imageSmall": "/photos/optimized/20260913-032-480.webp",
    "imageMedium": "/photos/optimized/20260913-032-960.webp",
    "imageLarge": "/photos/optimized/20260913-032-1600.webp",
    "date": "2026-09-13",
    "order": 219
  },
  {
    "id": "20260913-031",
    "image": "/photos/pics/20260913-031.png",
    "imageSmall": "/photos/optimized/20260913-031-480.webp",
    "imageMedium": "/photos/optimized/20260913-031-960.webp",
    "imageLarge": "/photos/optimized/20260913-031-1600.webp",
    "date": "2026-09-13",
    "order": 220
  },
  {
    "id": "20260913-030",
    "image": "/photos/pics/20260913-030.png",
    "imageSmall": "/photos/optimized/20260913-030-480.webp",
    "imageMedium": "/photos/optimized/20260913-030-960.webp",
    "imageLarge": "/photos/optimized/20260913-030-1600.webp",
    "date": "2026-09-13",
    "order": 221
  },
  {
    "id": "20260913-029",
    "image": "/photos/pics/20260913-029.png",
    "imageSmall": "/photos/optimized/20260913-029-480.webp",
    "imageMedium": "/photos/optimized/20260913-029-960.webp",
    "imageLarge": "/photos/optimized/20260913-029-1600.webp",
    "date": "2026-09-13",
    "order": 222
  },
  {
    "id": "20260913-028",
    "image": "/photos/pics/20260913-028.png",
    "imageSmall": "/photos/optimized/20260913-028-480.webp",
    "imageMedium": "/photos/optimized/20260913-028-960.webp",
    "imageLarge": "/photos/optimized/20260913-028-1600.webp",
    "date": "2026-09-13",
    "order": 223
  },
  {
    "id": "20260913-027",
    "image": "/photos/pics/20260913-027.png",
    "imageSmall": "/photos/optimized/20260913-027-480.webp",
    "imageMedium": "/photos/optimized/20260913-027-960.webp",
    "imageLarge": "/photos/optimized/20260913-027-1600.webp",
    "date": "2026-09-13",
    "order": 224
  },
  {
    "id": "20260913-026",
    "image": "/photos/pics/20260913-026.png",
    "imageSmall": "/photos/optimized/20260913-026-480.webp",
    "imageMedium": "/photos/optimized/20260913-026-960.webp",
    "imageLarge": "/photos/optimized/20260913-026-1600.webp",
    "date": "2026-09-13",
    "order": 225
  },
  {
    "id": "20260913-025",
    "image": "/photos/pics/20260913-025.png",
    "imageSmall": "/photos/optimized/20260913-025-480.webp",
    "imageMedium": "/photos/optimized/20260913-025-960.webp",
    "imageLarge": "/photos/optimized/20260913-025-1600.webp",
    "date": "2026-09-13",
    "order": 226
  },
  {
    "id": "20260913-024",
    "image": "/photos/pics/20260913-024.png",
    "imageSmall": "/photos/optimized/20260913-024-480.webp",
    "imageMedium": "/photos/optimized/20260913-024-960.webp",
    "imageLarge": "/photos/optimized/20260913-024-1600.webp",
    "date": "2026-09-13",
    "order": 227
  },
  {
    "id": "20260913-023",
    "image": "/photos/pics/20260913-023.png",
    "imageSmall": "/photos/optimized/20260913-023-480.webp",
    "imageMedium": "/photos/optimized/20260913-023-960.webp",
    "imageLarge": "/photos/optimized/20260913-023-1600.webp",
    "date": "2026-09-13",
    "order": 228
  },
  {
    "id": "20260913-022",
    "image": "/photos/pics/20260913-022.png",
    "imageSmall": "/photos/optimized/20260913-022-480.webp",
    "imageMedium": "/photos/optimized/20260913-022-960.webp",
    "imageLarge": "/photos/optimized/20260913-022-1600.webp",
    "date": "2026-09-13",
    "order": 229
  },
  {
    "id": "20260913-021",
    "image": "/photos/pics/20260913-021.png",
    "imageSmall": "/photos/optimized/20260913-021-480.webp",
    "imageMedium": "/photos/optimized/20260913-021-960.webp",
    "imageLarge": "/photos/optimized/20260913-021-1600.webp",
    "date": "2026-09-13",
    "order": 230
  },
  {
    "id": "20260913-020",
    "image": "/photos/pics/20260913-020.png",
    "imageSmall": "/photos/optimized/20260913-020-480.webp",
    "imageMedium": "/photos/optimized/20260913-020-960.webp",
    "imageLarge": "/photos/optimized/20260913-020-1600.webp",
    "date": "2026-09-13",
    "order": 231
  },
  {
    "id": "20260913-019",
    "image": "/photos/pics/20260913-019.png",
    "imageSmall": "/photos/optimized/20260913-019-480.webp",
    "imageMedium": "/photos/optimized/20260913-019-960.webp",
    "imageLarge": "/photos/optimized/20260913-019-1600.webp",
    "date": "2026-09-13",
    "order": 232
  },
  {
    "id": "20260913-018",
    "image": "/photos/pics/20260913-018.png",
    "imageSmall": "/photos/optimized/20260913-018-480.webp",
    "imageMedium": "/photos/optimized/20260913-018-960.webp",
    "imageLarge": "/photos/optimized/20260913-018-1600.webp",
    "date": "2026-09-13",
    "order": 233
  },
  {
    "id": "20260913-017",
    "image": "/photos/pics/20260913-017.png",
    "imageSmall": "/photos/optimized/20260913-017-480.webp",
    "imageMedium": "/photos/optimized/20260913-017-960.webp",
    "imageLarge": "/photos/optimized/20260913-017-1600.webp",
    "date": "2026-09-13",
    "order": 234
  },
  {
    "id": "20260913-016",
    "image": "/photos/pics/20260913-016.png",
    "imageSmall": "/photos/optimized/20260913-016-480.webp",
    "imageMedium": "/photos/optimized/20260913-016-960.webp",
    "imageLarge": "/photos/optimized/20260913-016-1600.webp",
    "date": "2026-09-13",
    "order": 235
  },
  {
    "id": "20260913-015",
    "image": "/photos/pics/20260913-015.png",
    "imageSmall": "/photos/optimized/20260913-015-480.webp",
    "imageMedium": "/photos/optimized/20260913-015-960.webp",
    "imageLarge": "/photos/optimized/20260913-015-1600.webp",
    "date": "2026-09-13",
    "order": 236
  },
  {
    "id": "20260913-014",
    "image": "/photos/pics/20260913-014.png",
    "imageSmall": "/photos/optimized/20260913-014-480.webp",
    "imageMedium": "/photos/optimized/20260913-014-960.webp",
    "imageLarge": "/photos/optimized/20260913-014-1600.webp",
    "date": "2026-09-13",
    "order": 237
  },
  {
    "id": "20260913-013",
    "image": "/photos/pics/20260913-013.png",
    "imageSmall": "/photos/optimized/20260913-013-480.webp",
    "imageMedium": "/photos/optimized/20260913-013-960.webp",
    "imageLarge": "/photos/optimized/20260913-013-1600.webp",
    "date": "2026-09-13",
    "order": 238
  },
  {
    "id": "20260913-012",
    "image": "/photos/pics/20260913-012.png",
    "imageSmall": "/photos/optimized/20260913-012-480.webp",
    "imageMedium": "/photos/optimized/20260913-012-960.webp",
    "imageLarge": "/photos/optimized/20260913-012-1600.webp",
    "date": "2026-09-13",
    "order": 239
  },
  {
    "id": "20260913-011",
    "image": "/photos/pics/20260913-011.png",
    "imageSmall": "/photos/optimized/20260913-011-480.webp",
    "imageMedium": "/photos/optimized/20260913-011-960.webp",
    "imageLarge": "/photos/optimized/20260913-011-1600.webp",
    "date": "2026-09-13",
    "order": 240
  },
  {
    "id": "20260913-010",
    "image": "/photos/pics/20260913-010.png",
    "imageSmall": "/photos/optimized/20260913-010-480.webp",
    "imageMedium": "/photos/optimized/20260913-010-960.webp",
    "imageLarge": "/photos/optimized/20260913-010-1600.webp",
    "date": "2026-09-13",
    "order": 241
  },
  {
    "id": "20260913-009",
    "image": "/photos/pics/20260913-009.png",
    "imageSmall": "/photos/optimized/20260913-009-480.webp",
    "imageMedium": "/photos/optimized/20260913-009-960.webp",
    "imageLarge": "/photos/optimized/20260913-009-1600.webp",
    "date": "2026-09-13",
    "order": 242
  },
  {
    "id": "20260913-008",
    "image": "/photos/pics/20260913-008.png",
    "imageSmall": "/photos/optimized/20260913-008-480.webp",
    "imageMedium": "/photos/optimized/20260913-008-960.webp",
    "imageLarge": "/photos/optimized/20260913-008-1600.webp",
    "date": "2026-09-13",
    "order": 243
  },
  {
    "id": "20260913-007",
    "image": "/photos/pics/20260913-007.png",
    "imageSmall": "/photos/optimized/20260913-007-480.webp",
    "imageMedium": "/photos/optimized/20260913-007-960.webp",
    "imageLarge": "/photos/optimized/20260913-007-1600.webp",
    "date": "2026-09-13",
    "order": 244
  },
  {
    "id": "20260913-006",
    "image": "/photos/pics/20260913-006.png",
    "imageSmall": "/photos/optimized/20260913-006-480.webp",
    "imageMedium": "/photos/optimized/20260913-006-960.webp",
    "imageLarge": "/photos/optimized/20260913-006-1600.webp",
    "date": "2026-09-13",
    "order": 245
  },
  {
    "id": "20260913-005",
    "image": "/photos/pics/20260913-005.png",
    "imageSmall": "/photos/optimized/20260913-005-480.webp",
    "imageMedium": "/photos/optimized/20260913-005-960.webp",
    "imageLarge": "/photos/optimized/20260913-005-1600.webp",
    "date": "2026-09-13",
    "order": 246
  },
  {
    "id": "20260913-004",
    "image": "/photos/pics/20260913-004.png",
    "imageSmall": "/photos/optimized/20260913-004-480.webp",
    "imageMedium": "/photos/optimized/20260913-004-960.webp",
    "imageLarge": "/photos/optimized/20260913-004-1600.webp",
    "date": "2026-09-13",
    "order": 247
  },
  {
    "id": "20260913-003",
    "image": "/photos/pics/20260913-003.png",
    "imageSmall": "/photos/optimized/20260913-003-480.webp",
    "imageMedium": "/photos/optimized/20260913-003-960.webp",
    "imageLarge": "/photos/optimized/20260913-003-1600.webp",
    "date": "2026-09-13",
    "order": 248
  },
  {
    "id": "20260913-002",
    "image": "/photos/pics/20260913-002.png",
    "imageSmall": "/photos/optimized/20260913-002-480.webp",
    "imageMedium": "/photos/optimized/20260913-002-960.webp",
    "imageLarge": "/photos/optimized/20260913-002-1600.webp",
    "date": "2026-09-13",
    "order": 249
  },
  {
    "id": "20260913-001",
    "image": "/photos/pics/20260913-001.png",
    "imageSmall": "/photos/optimized/20260913-001-480.webp",
    "imageMedium": "/photos/optimized/20260913-001-960.webp",
    "imageLarge": "/photos/optimized/20260913-001-1600.webp",
    "date": "2026-09-13",
    "order": 250
  },
  {
    "id": "20260912-053",
    "image": "/photos/pics/20260912-053.png",
    "imageSmall": "/photos/optimized/20260912-053-480.webp",
    "imageMedium": "/photos/optimized/20260912-053-960.webp",
    "imageLarge": "/photos/optimized/20260912-053-1600.webp",
    "date": "2026-09-12",
    "order": 251
  },
  {
    "id": "20260912-052",
    "image": "/photos/pics/20260912-052.png",
    "imageSmall": "/photos/optimized/20260912-052-480.webp",
    "imageMedium": "/photos/optimized/20260912-052-960.webp",
    "imageLarge": "/photos/optimized/20260912-052-1600.webp",
    "date": "2026-09-12",
    "order": 252
  },
  {
    "id": "20260912-051",
    "image": "/photos/pics/20260912-051.png",
    "imageSmall": "/photos/optimized/20260912-051-480.webp",
    "imageMedium": "/photos/optimized/20260912-051-960.webp",
    "imageLarge": "/photos/optimized/20260912-051-1600.webp",
    "date": "2026-09-12",
    "order": 253
  },
  {
    "id": "20260912-050",
    "image": "/photos/pics/20260912-050.png",
    "imageSmall": "/photos/optimized/20260912-050-480.webp",
    "imageMedium": "/photos/optimized/20260912-050-960.webp",
    "imageLarge": "/photos/optimized/20260912-050-1600.webp",
    "date": "2026-09-12",
    "order": 254
  },
  {
    "id": "20260912-049",
    "image": "/photos/pics/20260912-049.png",
    "imageSmall": "/photos/optimized/20260912-049-480.webp",
    "imageMedium": "/photos/optimized/20260912-049-960.webp",
    "imageLarge": "/photos/optimized/20260912-049-1600.webp",
    "date": "2026-09-12",
    "order": 255
  },
  {
    "id": "20260912-048",
    "image": "/photos/pics/20260912-048.png",
    "imageSmall": "/photos/optimized/20260912-048-480.webp",
    "imageMedium": "/photos/optimized/20260912-048-960.webp",
    "imageLarge": "/photos/optimized/20260912-048-1600.webp",
    "date": "2026-09-12",
    "order": 256
  },
  {
    "id": "20260912-047",
    "image": "/photos/pics/20260912-047.png",
    "imageSmall": "/photos/optimized/20260912-047-480.webp",
    "imageMedium": "/photos/optimized/20260912-047-960.webp",
    "imageLarge": "/photos/optimized/20260912-047-1600.webp",
    "date": "2026-09-12",
    "order": 257
  },
  {
    "id": "20260912-046",
    "image": "/photos/pics/20260912-046.png",
    "imageSmall": "/photos/optimized/20260912-046-480.webp",
    "imageMedium": "/photos/optimized/20260912-046-960.webp",
    "imageLarge": "/photos/optimized/20260912-046-1600.webp",
    "date": "2026-09-12",
    "order": 258
  },
  {
    "id": "20260912-045",
    "image": "/photos/pics/20260912-045.png",
    "imageSmall": "/photos/optimized/20260912-045-480.webp",
    "imageMedium": "/photos/optimized/20260912-045-960.webp",
    "imageLarge": "/photos/optimized/20260912-045-1600.webp",
    "date": "2026-09-12",
    "order": 259
  },
  {
    "id": "20260912-044",
    "image": "/photos/pics/20260912-044.png",
    "imageSmall": "/photos/optimized/20260912-044-480.webp",
    "imageMedium": "/photos/optimized/20260912-044-960.webp",
    "imageLarge": "/photos/optimized/20260912-044-1600.webp",
    "date": "2026-09-12",
    "order": 260
  },
  {
    "id": "20260912-043",
    "image": "/photos/pics/20260912-043.png",
    "imageSmall": "/photos/optimized/20260912-043-480.webp",
    "imageMedium": "/photos/optimized/20260912-043-960.webp",
    "imageLarge": "/photos/optimized/20260912-043-1600.webp",
    "date": "2026-09-12",
    "order": 261
  },
  {
    "id": "20260912-042",
    "image": "/photos/pics/20260912-042.png",
    "imageSmall": "/photos/optimized/20260912-042-480.webp",
    "imageMedium": "/photos/optimized/20260912-042-960.webp",
    "imageLarge": "/photos/optimized/20260912-042-1600.webp",
    "date": "2026-09-12",
    "order": 262
  },
  {
    "id": "20260912-041",
    "image": "/photos/pics/20260912-041.png",
    "imageSmall": "/photos/optimized/20260912-041-480.webp",
    "imageMedium": "/photos/optimized/20260912-041-960.webp",
    "imageLarge": "/photos/optimized/20260912-041-1600.webp",
    "date": "2026-09-12",
    "order": 263
  },
  {
    "id": "20260912-040",
    "image": "/photos/pics/20260912-040.png",
    "imageSmall": "/photos/optimized/20260912-040-480.webp",
    "imageMedium": "/photos/optimized/20260912-040-960.webp",
    "imageLarge": "/photos/optimized/20260912-040-1600.webp",
    "date": "2026-09-12",
    "order": 264
  },
  {
    "id": "20260912-039",
    "image": "/photos/pics/20260912-039.png",
    "imageSmall": "/photos/optimized/20260912-039-480.webp",
    "imageMedium": "/photos/optimized/20260912-039-960.webp",
    "imageLarge": "/photos/optimized/20260912-039-1600.webp",
    "date": "2026-09-12",
    "order": 265
  },
  {
    "id": "20260912-038",
    "image": "/photos/pics/20260912-038.png",
    "imageSmall": "/photos/optimized/20260912-038-480.webp",
    "imageMedium": "/photos/optimized/20260912-038-960.webp",
    "imageLarge": "/photos/optimized/20260912-038-1600.webp",
    "date": "2026-09-12",
    "order": 266
  },
  {
    "id": "20260912-037",
    "image": "/photos/pics/20260912-037.png",
    "imageSmall": "/photos/optimized/20260912-037-480.webp",
    "imageMedium": "/photos/optimized/20260912-037-960.webp",
    "imageLarge": "/photos/optimized/20260912-037-1600.webp",
    "date": "2026-09-12",
    "order": 267
  },
  {
    "id": "20260912-036",
    "image": "/photos/pics/20260912-036.png",
    "imageSmall": "/photos/optimized/20260912-036-480.webp",
    "imageMedium": "/photos/optimized/20260912-036-960.webp",
    "imageLarge": "/photos/optimized/20260912-036-1600.webp",
    "date": "2026-09-12",
    "order": 268
  },
  {
    "id": "20260912-035",
    "image": "/photos/pics/20260912-035.png",
    "imageSmall": "/photos/optimized/20260912-035-480.webp",
    "imageMedium": "/photos/optimized/20260912-035-960.webp",
    "imageLarge": "/photos/optimized/20260912-035-1600.webp",
    "date": "2026-09-12",
    "order": 269
  },
  {
    "id": "20260912-034",
    "image": "/photos/pics/20260912-034.png",
    "imageSmall": "/photos/optimized/20260912-034-480.webp",
    "imageMedium": "/photos/optimized/20260912-034-960.webp",
    "imageLarge": "/photos/optimized/20260912-034-1600.webp",
    "date": "2026-09-12",
    "order": 270
  },
  {
    "id": "20260912-033",
    "image": "/photos/pics/20260912-033.png",
    "imageSmall": "/photos/optimized/20260912-033-480.webp",
    "imageMedium": "/photos/optimized/20260912-033-960.webp",
    "imageLarge": "/photos/optimized/20260912-033-1600.webp",
    "date": "2026-09-12",
    "order": 271
  },
  {
    "id": "20260912-032",
    "image": "/photos/pics/20260912-032.png",
    "imageSmall": "/photos/optimized/20260912-032-480.webp",
    "imageMedium": "/photos/optimized/20260912-032-960.webp",
    "imageLarge": "/photos/optimized/20260912-032-1600.webp",
    "date": "2026-09-12",
    "order": 272
  },
  {
    "id": "20260912-031",
    "image": "/photos/pics/20260912-031.png",
    "imageSmall": "/photos/optimized/20260912-031-480.webp",
    "imageMedium": "/photos/optimized/20260912-031-960.webp",
    "imageLarge": "/photos/optimized/20260912-031-1600.webp",
    "date": "2026-09-12",
    "order": 273
  },
  {
    "id": "20260912-030",
    "image": "/photos/pics/20260912-030.png",
    "imageSmall": "/photos/optimized/20260912-030-480.webp",
    "imageMedium": "/photos/optimized/20260912-030-960.webp",
    "imageLarge": "/photos/optimized/20260912-030-1600.webp",
    "date": "2026-09-12",
    "order": 274
  },
  {
    "id": "20260912-029",
    "image": "/photos/pics/20260912-029.png",
    "imageSmall": "/photos/optimized/20260912-029-480.webp",
    "imageMedium": "/photos/optimized/20260912-029-960.webp",
    "imageLarge": "/photos/optimized/20260912-029-1600.webp",
    "date": "2026-09-12",
    "order": 275
  },
  {
    "id": "20260912-028",
    "image": "/photos/pics/20260912-028.png",
    "imageSmall": "/photos/optimized/20260912-028-480.webp",
    "imageMedium": "/photos/optimized/20260912-028-960.webp",
    "imageLarge": "/photos/optimized/20260912-028-1600.webp",
    "date": "2026-09-12",
    "order": 276
  },
  {
    "id": "20260912-027",
    "image": "/photos/pics/20260912-027.png",
    "imageSmall": "/photos/optimized/20260912-027-480.webp",
    "imageMedium": "/photos/optimized/20260912-027-960.webp",
    "imageLarge": "/photos/optimized/20260912-027-1600.webp",
    "date": "2026-09-12",
    "order": 277
  },
  {
    "id": "20260912-026",
    "image": "/photos/pics/20260912-026.png",
    "imageSmall": "/photos/optimized/20260912-026-480.webp",
    "imageMedium": "/photos/optimized/20260912-026-960.webp",
    "imageLarge": "/photos/optimized/20260912-026-1600.webp",
    "date": "2026-09-12",
    "order": 278
  },
  {
    "id": "20260912-025",
    "image": "/photos/pics/20260912-025.png",
    "imageSmall": "/photos/optimized/20260912-025-480.webp",
    "imageMedium": "/photos/optimized/20260912-025-960.webp",
    "imageLarge": "/photos/optimized/20260912-025-1600.webp",
    "date": "2026-09-12",
    "order": 279
  },
  {
    "id": "20260912-024",
    "image": "/photos/pics/20260912-024.png",
    "imageSmall": "/photos/optimized/20260912-024-480.webp",
    "imageMedium": "/photos/optimized/20260912-024-960.webp",
    "imageLarge": "/photos/optimized/20260912-024-1600.webp",
    "date": "2026-09-12",
    "order": 280
  },
  {
    "id": "20260912-023",
    "image": "/photos/pics/20260912-023.png",
    "imageSmall": "/photos/optimized/20260912-023-480.webp",
    "imageMedium": "/photos/optimized/20260912-023-960.webp",
    "imageLarge": "/photos/optimized/20260912-023-1600.webp",
    "date": "2026-09-12",
    "order": 281
  },
  {
    "id": "20260912-022",
    "image": "/photos/pics/20260912-022.png",
    "imageSmall": "/photos/optimized/20260912-022-480.webp",
    "imageMedium": "/photos/optimized/20260912-022-960.webp",
    "imageLarge": "/photos/optimized/20260912-022-1600.webp",
    "date": "2026-09-12",
    "order": 282
  },
  {
    "id": "20260912-021",
    "image": "/photos/pics/20260912-021.png",
    "imageSmall": "/photos/optimized/20260912-021-480.webp",
    "imageMedium": "/photos/optimized/20260912-021-960.webp",
    "imageLarge": "/photos/optimized/20260912-021-1600.webp",
    "date": "2026-09-12",
    "order": 283
  },
  {
    "id": "20260912-020",
    "image": "/photos/pics/20260912-020.png",
    "imageSmall": "/photos/optimized/20260912-020-480.webp",
    "imageMedium": "/photos/optimized/20260912-020-960.webp",
    "imageLarge": "/photos/optimized/20260912-020-1600.webp",
    "date": "2026-09-12",
    "order": 284
  },
  {
    "id": "20260912-019",
    "image": "/photos/pics/20260912-019.png",
    "imageSmall": "/photos/optimized/20260912-019-480.webp",
    "imageMedium": "/photos/optimized/20260912-019-960.webp",
    "imageLarge": "/photos/optimized/20260912-019-1600.webp",
    "date": "2026-09-12",
    "order": 285
  },
  {
    "id": "20260912-018",
    "image": "/photos/pics/20260912-018.png",
    "imageSmall": "/photos/optimized/20260912-018-480.webp",
    "imageMedium": "/photos/optimized/20260912-018-960.webp",
    "imageLarge": "/photos/optimized/20260912-018-1600.webp",
    "date": "2026-09-12",
    "order": 286
  },
  {
    "id": "20260912-017",
    "image": "/photos/pics/20260912-017.png",
    "imageSmall": "/photos/optimized/20260912-017-480.webp",
    "imageMedium": "/photos/optimized/20260912-017-960.webp",
    "imageLarge": "/photos/optimized/20260912-017-1600.webp",
    "date": "2026-09-12",
    "order": 287
  },
  {
    "id": "20260912-016",
    "image": "/photos/pics/20260912-016.png",
    "imageSmall": "/photos/optimized/20260912-016-480.webp",
    "imageMedium": "/photos/optimized/20260912-016-960.webp",
    "imageLarge": "/photos/optimized/20260912-016-1600.webp",
    "date": "2026-09-12",
    "order": 288
  },
  {
    "id": "20260912-015",
    "image": "/photos/pics/20260912-015.png",
    "imageSmall": "/photos/optimized/20260912-015-480.webp",
    "imageMedium": "/photos/optimized/20260912-015-960.webp",
    "imageLarge": "/photos/optimized/20260912-015-1600.webp",
    "date": "2026-09-12",
    "order": 289
  },
  {
    "id": "20260912-014",
    "image": "/photos/pics/20260912-014.png",
    "imageSmall": "/photos/optimized/20260912-014-480.webp",
    "imageMedium": "/photos/optimized/20260912-014-960.webp",
    "imageLarge": "/photos/optimized/20260912-014-1600.webp",
    "date": "2026-09-12",
    "order": 290
  },
  {
    "id": "20260912-013",
    "image": "/photos/pics/20260912-013.png",
    "imageSmall": "/photos/optimized/20260912-013-480.webp",
    "imageMedium": "/photos/optimized/20260912-013-960.webp",
    "imageLarge": "/photos/optimized/20260912-013-1600.webp",
    "date": "2026-09-12",
    "order": 291
  },
  {
    "id": "20260912-012",
    "image": "/photos/pics/20260912-012.png",
    "imageSmall": "/photos/optimized/20260912-012-480.webp",
    "imageMedium": "/photos/optimized/20260912-012-960.webp",
    "imageLarge": "/photos/optimized/20260912-012-1600.webp",
    "date": "2026-09-12",
    "order": 292
  },
  {
    "id": "20260912-011",
    "image": "/photos/pics/20260912-011.png",
    "imageSmall": "/photos/optimized/20260912-011-480.webp",
    "imageMedium": "/photos/optimized/20260912-011-960.webp",
    "imageLarge": "/photos/optimized/20260912-011-1600.webp",
    "date": "2026-09-12",
    "order": 293
  },
  {
    "id": "20260912-010",
    "image": "/photos/pics/20260912-010.png",
    "imageSmall": "/photos/optimized/20260912-010-480.webp",
    "imageMedium": "/photos/optimized/20260912-010-960.webp",
    "imageLarge": "/photos/optimized/20260912-010-1600.webp",
    "date": "2026-09-12",
    "order": 294
  },
  {
    "id": "20260912-009",
    "image": "/photos/pics/20260912-009.png",
    "imageSmall": "/photos/optimized/20260912-009-480.webp",
    "imageMedium": "/photos/optimized/20260912-009-960.webp",
    "imageLarge": "/photos/optimized/20260912-009-1600.webp",
    "date": "2026-09-12",
    "order": 295
  },
  {
    "id": "20260912-008",
    "image": "/photos/pics/20260912-008.png",
    "imageSmall": "/photos/optimized/20260912-008-480.webp",
    "imageMedium": "/photos/optimized/20260912-008-960.webp",
    "imageLarge": "/photos/optimized/20260912-008-1600.webp",
    "date": "2026-09-12",
    "order": 296
  },
  {
    "id": "20260912-007",
    "image": "/photos/pics/20260912-007.png",
    "imageSmall": "/photos/optimized/20260912-007-480.webp",
    "imageMedium": "/photos/optimized/20260912-007-960.webp",
    "imageLarge": "/photos/optimized/20260912-007-1600.webp",
    "date": "2026-09-12",
    "order": 297
  },
  {
    "id": "20260912-006",
    "image": "/photos/pics/20260912-006.png",
    "imageSmall": "/photos/optimized/20260912-006-480.webp",
    "imageMedium": "/photos/optimized/20260912-006-960.webp",
    "imageLarge": "/photos/optimized/20260912-006-1600.webp",
    "date": "2026-09-12",
    "order": 298
  },
  {
    "id": "20260912-005",
    "image": "/photos/pics/20260912-005.png",
    "imageSmall": "/photos/optimized/20260912-005-480.webp",
    "imageMedium": "/photos/optimized/20260912-005-960.webp",
    "imageLarge": "/photos/optimized/20260912-005-1600.webp",
    "date": "2026-09-12",
    "order": 299
  },
  {
    "id": "20260912-004",
    "image": "/photos/pics/20260912-004.png",
    "imageSmall": "/photos/optimized/20260912-004-480.webp",
    "imageMedium": "/photos/optimized/20260912-004-960.webp",
    "imageLarge": "/photos/optimized/20260912-004-1600.webp",
    "date": "2026-09-12",
    "order": 300
  },
  {
    "id": "20260912-003",
    "image": "/photos/pics/20260912-003.png",
    "imageSmall": "/photos/optimized/20260912-003-480.webp",
    "imageMedium": "/photos/optimized/20260912-003-960.webp",
    "imageLarge": "/photos/optimized/20260912-003-1600.webp",
    "date": "2026-09-12",
    "order": 301
  },
  {
    "id": "20260912-002",
    "image": "/photos/pics/20260912-002.png",
    "imageSmall": "/photos/optimized/20260912-002-480.webp",
    "imageMedium": "/photos/optimized/20260912-002-960.webp",
    "imageLarge": "/photos/optimized/20260912-002-1600.webp",
    "date": "2026-09-12",
    "order": 302
  },
  {
    "id": "20260912-001",
    "image": "/photos/pics/20260912-001.png",
    "imageSmall": "/photos/optimized/20260912-001-480.webp",
    "imageMedium": "/photos/optimized/20260912-001-960.webp",
    "imageLarge": "/photos/optimized/20260912-001-1600.webp",
    "date": "2026-09-12",
    "order": 303
  },
  {
    "id": "20260911-003",
    "image": "/photos/pics/20260911-003.png",
    "imageSmall": "/photos/optimized/20260911-003-480.webp",
    "imageMedium": "/photos/optimized/20260911-003-960.webp",
    "imageLarge": "/photos/optimized/20260911-003-1600.webp",
    "date": "2026-09-11",
    "order": 304
  },
  {
    "id": "20260911-002",
    "image": "/photos/pics/20260911-002.png",
    "imageSmall": "/photos/optimized/20260911-002-480.webp",
    "imageMedium": "/photos/optimized/20260911-002-960.webp",
    "imageLarge": "/photos/optimized/20260911-002-1600.webp",
    "date": "2026-09-11",
    "order": 305
  },
  {
    "id": "20260911-001",
    "image": "/photos/pics/20260911-001.png",
    "imageSmall": "/photos/optimized/20260911-001-480.webp",
    "imageMedium": "/photos/optimized/20260911-001-960.webp",
    "imageLarge": "/photos/optimized/20260911-001-1600.webp",
    "date": "2026-09-11",
    "order": 306
  }
];
