/**
 * AUTO-GENERATED FILE.
 *
 * Do not edit this file manually.
 *
 * Generated by:
 * scripts/generate-photo-data.mjs
 */

export type GeneratedPhotoWork = {
	id: string;
	image: string;
	date: string;
	order: number;
};

export const generatedPhotoWorks: GeneratedPhotoWork[] = [
  {
    "id": "20260915-016",
    "image": "/photos/pics/20260915-016.png",
    "date": "2026-09-15",
    "order": 1
  },
  {
    "id": "20260915-015",
    "image": "/photos/pics/20260915-015.png",
    "date": "2026-09-15",
    "order": 2
  },
  {
    "id": "20260915-014",
    "image": "/photos/pics/20260915-014.png",
    "date": "2026-09-15",
    "order": 3
  },
  {
    "id": "20260915-013",
    "image": "/photos/pics/20260915-013.png",
    "date": "2026-09-15",
    "order": 4
  },
  {
    "id": "20260915-012",
    "image": "/photos/pics/20260915-012.png",
    "date": "2026-09-15",
    "order": 5
  },
  {
    "id": "20260915-011",
    "image": "/photos/pics/20260915-011.png",
    "date": "2026-09-15",
    "order": 6
  },
  {
    "id": "20260915-010",
    "image": "/photos/pics/20260915-010.png",
    "date": "2026-09-15",
    "order": 7
  },
  {
    "id": "20260915-009",
    "image": "/photos/pics/20260915-009.png",
    "date": "2026-09-15",
    "order": 8
  },
  {
    "id": "20260915-008",
    "image": "/photos/pics/20260915-008.png",
    "date": "2026-09-15",
    "order": 9
  },
  {
    "id": "20260915-007",
    "image": "/photos/pics/20260915-007.png",
    "date": "2026-09-15",
    "order": 10
  },
  {
    "id": "20260915-006",
    "image": "/photos/pics/20260915-006.png",
    "date": "2026-09-15",
    "order": 11
  },
  {
    "id": "20260915-005",
    "image": "/photos/pics/20260915-005.png",
    "date": "2026-09-15",
    "order": 12
  },
  {
    "id": "20260915-004",
    "image": "/photos/pics/20260915-004.png",
    "date": "2026-09-15",
    "order": 13
  },
  {
    "id": "20260915-003",
    "image": "/photos/pics/20260915-003.png",
    "date": "2026-09-15",
    "order": 14
  },
  {
    "id": "20260915-002",
    "image": "/photos/pics/20260915-002.png",
    "date": "2026-09-15",
    "order": 15
  },
  {
    "id": "20260915-001",
    "image": "/photos/pics/20260915-001.png",
    "date": "2026-09-15",
    "order": 16
  },
  {
    "id": "20260914-036",
    "image": "/photos/pics/20260914-036.png",
    "date": "2026-09-14",
    "order": 17
  },
  {
    "id": "20260914-035",
    "image": "/photos/pics/20260914-035.png",
    "date": "2026-09-14",
    "order": 18
  },
  {
    "id": "20260914-034",
    "image": "/photos/pics/20260914-034.png",
    "date": "2026-09-14",
    "order": 19
  },
  {
    "id": "20260914-033",
    "image": "/photos/pics/20260914-033.png",
    "date": "2026-09-14",
    "order": 20
  },
  {
    "id": "20260914-032",
    "image": "/photos/pics/20260914-032.png",
    "date": "2026-09-14",
    "order": 21
  },
  {
    "id": "20260914-031",
    "image": "/photos/pics/20260914-031.png",
    "date": "2026-09-14",
    "order": 22
  },
  {
    "id": "20260914-030",
    "image": "/photos/pics/20260914-030.png",
    "date": "2026-09-14",
    "order": 23
  },
  {
    "id": "20260914-029",
    "image": "/photos/pics/20260914-029.png",
    "date": "2026-09-14",
    "order": 24
  },
  {
    "id": "20260914-028",
    "image": "/photos/pics/20260914-028.png",
    "date": "2026-09-14",
    "order": 25
  },
  {
    "id": "20260914-027",
    "image": "/photos/pics/20260914-027.png",
    "date": "2026-09-14",
    "order": 26
  },
  {
    "id": "20260914-026",
    "image": "/photos/pics/20260914-026.png",
    "date": "2026-09-14",
    "order": 27
  },
  {
    "id": "20260914-025",
    "image": "/photos/pics/20260914-025.png",
    "date": "2026-09-14",
    "order": 28
  },
  {
    "id": "20260914-024",
    "image": "/photos/pics/20260914-024.png",
    "date": "2026-09-14",
    "order": 29
  },
  {
    "id": "20260914-023",
    "image": "/photos/pics/20260914-023.png",
    "date": "2026-09-14",
    "order": 30
  },
  {
    "id": "20260914-022",
    "image": "/photos/pics/20260914-022.png",
    "date": "2026-09-14",
    "order": 31
  },
  {
    "id": "20260914-021",
    "image": "/photos/pics/20260914-021.png",
    "date": "2026-09-14",
    "order": 32
  },
  {
    "id": "20260914-020",
    "image": "/photos/pics/20260914-020.png",
    "date": "2026-09-14",
    "order": 33
  },
  {
    "id": "20260914-019",
    "image": "/photos/pics/20260914-019.png",
    "date": "2026-09-14",
    "order": 34
  },
  {
    "id": "20260914-018",
    "image": "/photos/pics/20260914-018.png",
    "date": "2026-09-14",
    "order": 35
  },
  {
    "id": "20260914-017",
    "image": "/photos/pics/20260914-017.png",
    "date": "2026-09-14",
    "order": 36
  },
  {
    "id": "20260914-016",
    "image": "/photos/pics/20260914-016.png",
    "date": "2026-09-14",
    "order": 37
  },
  {
    "id": "20260914-015",
    "image": "/photos/pics/20260914-015.png",
    "date": "2026-09-14",
    "order": 38
  },
  {
    "id": "20260914-014",
    "image": "/photos/pics/20260914-014.png",
    "date": "2026-09-14",
    "order": 39
  },
  {
    "id": "20260914-013",
    "image": "/photos/pics/20260914-013.png",
    "date": "2026-09-14",
    "order": 40
  },
  {
    "id": "20260914-012",
    "image": "/photos/pics/20260914-012.png",
    "date": "2026-09-14",
    "order": 41
  },
  {
    "id": "20260914-011",
    "image": "/photos/pics/20260914-011.png",
    "date": "2026-09-14",
    "order": 42
  },
  {
    "id": "20260914-010",
    "image": "/photos/pics/20260914-010.png",
    "date": "2026-09-14",
    "order": 43
  },
  {
    "id": "20260914-009",
    "image": "/photos/pics/20260914-009.png",
    "date": "2026-09-14",
    "order": 44
  },
  {
    "id": "20260914-008",
    "image": "/photos/pics/20260914-008.png",
    "date": "2026-09-14",
    "order": 45
  },
  {
    "id": "20260914-007",
    "image": "/photos/pics/20260914-007.png",
    "date": "2026-09-14",
    "order": 46
  },
  {
    "id": "20260914-006",
    "image": "/photos/pics/20260914-006.png",
    "date": "2026-09-14",
    "order": 47
  },
  {
    "id": "20260914-005",
    "image": "/photos/pics/20260914-005.png",
    "date": "2026-09-14",
    "order": 48
  },
  {
    "id": "20260914-004",
    "image": "/photos/pics/20260914-004.png",
    "date": "2026-09-14",
    "order": 49
  },
  {
    "id": "20260914-003",
    "image": "/photos/pics/20260914-003.png",
    "date": "2026-09-14",
    "order": 50
  },
  {
    "id": "20260914-002",
    "image": "/photos/pics/20260914-002.png",
    "date": "2026-09-14",
    "order": 51
  },
  {
    "id": "20260914-001",
    "image": "/photos/pics/20260914-001.png",
    "date": "2026-09-14",
    "order": 52
  },
  {
    "id": "20260913-047",
    "image": "/photos/pics/20260913-047.png",
    "date": "2026-09-13",
    "order": 53
  },
  {
    "id": "20260913-046",
    "image": "/photos/pics/20260913-046.png",
    "date": "2026-09-13",
    "order": 54
  },
  {
    "id": "20260913-045",
    "image": "/photos/pics/20260913-045.png",
    "date": "2026-09-13",
    "order": 55
  },
  {
    "id": "20260913-044",
    "image": "/photos/pics/20260913-044.png",
    "date": "2026-09-13",
    "order": 56
  },
  {
    "id": "20260913-043",
    "image": "/photos/pics/20260913-043.png",
    "date": "2026-09-13",
    "order": 57
  },
  {
    "id": "20260913-042",
    "image": "/photos/pics/20260913-042.png",
    "date": "2026-09-13",
    "order": 58
  },
  {
    "id": "20260913-041",
    "image": "/photos/pics/20260913-041.png",
    "date": "2026-09-13",
    "order": 59
  },
  {
    "id": "20260913-040",
    "image": "/photos/pics/20260913-040.png",
    "date": "2026-09-13",
    "order": 60
  },
  {
    "id": "20260913-039",
    "image": "/photos/pics/20260913-039.png",
    "date": "2026-09-13",
    "order": 61
  },
  {
    "id": "20260913-038",
    "image": "/photos/pics/20260913-038.png",
    "date": "2026-09-13",
    "order": 62
  },
  {
    "id": "20260913-037",
    "image": "/photos/pics/20260913-037.png",
    "date": "2026-09-13",
    "order": 63
  },
  {
    "id": "20260913-036",
    "image": "/photos/pics/20260913-036.png",
    "date": "2026-09-13",
    "order": 64
  },
  {
    "id": "20260913-035",
    "image": "/photos/pics/20260913-035.png",
    "date": "2026-09-13",
    "order": 65
  },
  {
    "id": "20260913-034",
    "image": "/photos/pics/20260913-034.png",
    "date": "2026-09-13",
    "order": 66
  },
  {
    "id": "20260913-033",
    "image": "/photos/pics/20260913-033.png",
    "date": "2026-09-13",
    "order": 67
  },
  {
    "id": "20260913-032",
    "image": "/photos/pics/20260913-032.png",
    "date": "2026-09-13",
    "order": 68
  },
  {
    "id": "20260913-031",
    "image": "/photos/pics/20260913-031.png",
    "date": "2026-09-13",
    "order": 69
  },
  {
    "id": "20260913-030",
    "image": "/photos/pics/20260913-030.png",
    "date": "2026-09-13",
    "order": 70
  },
  {
    "id": "20260913-029",
    "image": "/photos/pics/20260913-029.png",
    "date": "2026-09-13",
    "order": 71
  },
  {
    "id": "20260913-028",
    "image": "/photos/pics/20260913-028.png",
    "date": "2026-09-13",
    "order": 72
  },
  {
    "id": "20260913-027",
    "image": "/photos/pics/20260913-027.png",
    "date": "2026-09-13",
    "order": 73
  },
  {
    "id": "20260913-026",
    "image": "/photos/pics/20260913-026.png",
    "date": "2026-09-13",
    "order": 74
  },
  {
    "id": "20260913-025",
    "image": "/photos/pics/20260913-025.png",
    "date": "2026-09-13",
    "order": 75
  },
  {
    "id": "20260913-024",
    "image": "/photos/pics/20260913-024.png",
    "date": "2026-09-13",
    "order": 76
  },
  {
    "id": "20260913-023",
    "image": "/photos/pics/20260913-023.png",
    "date": "2026-09-13",
    "order": 77
  },
  {
    "id": "20260913-022",
    "image": "/photos/pics/20260913-022.png",
    "date": "2026-09-13",
    "order": 78
  },
  {
    "id": "20260913-021",
    "image": "/photos/pics/20260913-021.png",
    "date": "2026-09-13",
    "order": 79
  },
  {
    "id": "20260913-020",
    "image": "/photos/pics/20260913-020.png",
    "date": "2026-09-13",
    "order": 80
  },
  {
    "id": "20260913-019",
    "image": "/photos/pics/20260913-019.png",
    "date": "2026-09-13",
    "order": 81
  },
  {
    "id": "20260913-018",
    "image": "/photos/pics/20260913-018.png",
    "date": "2026-09-13",
    "order": 82
  },
  {
    "id": "20260913-017",
    "image": "/photos/pics/20260913-017.png",
    "date": "2026-09-13",
    "order": 83
  },
  {
    "id": "20260913-016",
    "image": "/photos/pics/20260913-016.png",
    "date": "2026-09-13",
    "order": 84
  },
  {
    "id": "20260913-015",
    "image": "/photos/pics/20260913-015.png",
    "date": "2026-09-13",
    "order": 85
  },
  {
    "id": "20260913-014",
    "image": "/photos/pics/20260913-014.png",
    "date": "2026-09-13",
    "order": 86
  },
  {
    "id": "20260913-013",
    "image": "/photos/pics/20260913-013.png",
    "date": "2026-09-13",
    "order": 87
  },
  {
    "id": "20260913-012",
    "image": "/photos/pics/20260913-012.png",
    "date": "2026-09-13",
    "order": 88
  },
  {
    "id": "20260913-011",
    "image": "/photos/pics/20260913-011.png",
    "date": "2026-09-13",
    "order": 89
  },
  {
    "id": "20260913-010",
    "image": "/photos/pics/20260913-010.png",
    "date": "2026-09-13",
    "order": 90
  },
  {
    "id": "20260913-009",
    "image": "/photos/pics/20260913-009.png",
    "date": "2026-09-13",
    "order": 91
  },
  {
    "id": "20260913-008",
    "image": "/photos/pics/20260913-008.png",
    "date": "2026-09-13",
    "order": 92
  },
  {
    "id": "20260913-007",
    "image": "/photos/pics/20260913-007.png",
    "date": "2026-09-13",
    "order": 93
  },
  {
    "id": "20260913-006",
    "image": "/photos/pics/20260913-006.png",
    "date": "2026-09-13",
    "order": 94
  },
  {
    "id": "20260913-005",
    "image": "/photos/pics/20260913-005.png",
    "date": "2026-09-13",
    "order": 95
  },
  {
    "id": "20260913-004",
    "image": "/photos/pics/20260913-004.png",
    "date": "2026-09-13",
    "order": 96
  },
  {
    "id": "20260913-003",
    "image": "/photos/pics/20260913-003.png",
    "date": "2026-09-13",
    "order": 97
  },
  {
    "id": "20260913-002",
    "image": "/photos/pics/20260913-002.png",
    "date": "2026-09-13",
    "order": 98
  },
  {
    "id": "20260913-001",
    "image": "/photos/pics/20260913-001.png",
    "date": "2026-09-13",
    "order": 99
  },
  {
    "id": "20260912-053",
    "image": "/photos/pics/20260912-053.png",
    "date": "2026-09-12",
    "order": 100
  },
  {
    "id": "20260912-052",
    "image": "/photos/pics/20260912-052.png",
    "date": "2026-09-12",
    "order": 101
  },
  {
    "id": "20260912-051",
    "image": "/photos/pics/20260912-051.png",
    "date": "2026-09-12",
    "order": 102
  },
  {
    "id": "20260912-050",
    "image": "/photos/pics/20260912-050.png",
    "date": "2026-09-12",
    "order": 103
  },
  {
    "id": "20260912-049",
    "image": "/photos/pics/20260912-049.png",
    "date": "2026-09-12",
    "order": 104
  },
  {
    "id": "20260912-048",
    "image": "/photos/pics/20260912-048.png",
    "date": "2026-09-12",
    "order": 105
  },
  {
    "id": "20260912-047",
    "image": "/photos/pics/20260912-047.png",
    "date": "2026-09-12",
    "order": 106
  },
  {
    "id": "20260912-046",
    "image": "/photos/pics/20260912-046.png",
    "date": "2026-09-12",
    "order": 107
  },
  {
    "id": "20260912-045",
    "image": "/photos/pics/20260912-045.png",
    "date": "2026-09-12",
    "order": 108
  },
  {
    "id": "20260912-044",
    "image": "/photos/pics/20260912-044.png",
    "date": "2026-09-12",
    "order": 109
  },
  {
    "id": "20260912-043",
    "image": "/photos/pics/20260912-043.png",
    "date": "2026-09-12",
    "order": 110
  },
  {
    "id": "20260912-042",
    "image": "/photos/pics/20260912-042.png",
    "date": "2026-09-12",
    "order": 111
  },
  {
    "id": "20260912-041",
    "image": "/photos/pics/20260912-041.png",
    "date": "2026-09-12",
    "order": 112
  },
  {
    "id": "20260912-040",
    "image": "/photos/pics/20260912-040.png",
    "date": "2026-09-12",
    "order": 113
  },
  {
    "id": "20260912-039",
    "image": "/photos/pics/20260912-039.png",
    "date": "2026-09-12",
    "order": 114
  },
  {
    "id": "20260912-038",
    "image": "/photos/pics/20260912-038.png",
    "date": "2026-09-12",
    "order": 115
  },
  {
    "id": "20260912-037",
    "image": "/photos/pics/20260912-037.png",
    "date": "2026-09-12",
    "order": 116
  },
  {
    "id": "20260912-036",
    "image": "/photos/pics/20260912-036.png",
    "date": "2026-09-12",
    "order": 117
  },
  {
    "id": "20260912-035",
    "image": "/photos/pics/20260912-035.png",
    "date": "2026-09-12",
    "order": 118
  },
  {
    "id": "20260912-034",
    "image": "/photos/pics/20260912-034.png",
    "date": "2026-09-12",
    "order": 119
  },
  {
    "id": "20260912-033",
    "image": "/photos/pics/20260912-033.png",
    "date": "2026-09-12",
    "order": 120
  },
  {
    "id": "20260912-032",
    "image": "/photos/pics/20260912-032.png",
    "date": "2026-09-12",
    "order": 121
  },
  {
    "id": "20260912-031",
    "image": "/photos/pics/20260912-031.png",
    "date": "2026-09-12",
    "order": 122
  },
  {
    "id": "20260912-030",
    "image": "/photos/pics/20260912-030.png",
    "date": "2026-09-12",
    "order": 123
  },
  {
    "id": "20260912-029",
    "image": "/photos/pics/20260912-029.png",
    "date": "2026-09-12",
    "order": 124
  },
  {
    "id": "20260912-028",
    "image": "/photos/pics/20260912-028.png",
    "date": "2026-09-12",
    "order": 125
  },
  {
    "id": "20260912-027",
    "image": "/photos/pics/20260912-027.png",
    "date": "2026-09-12",
    "order": 126
  },
  {
    "id": "20260912-026",
    "image": "/photos/pics/20260912-026.png",
    "date": "2026-09-12",
    "order": 127
  },
  {
    "id": "20260912-025",
    "image": "/photos/pics/20260912-025.png",
    "date": "2026-09-12",
    "order": 128
  },
  {
    "id": "20260912-024",
    "image": "/photos/pics/20260912-024.png",
    "date": "2026-09-12",
    "order": 129
  },
  {
    "id": "20260912-023",
    "image": "/photos/pics/20260912-023.png",
    "date": "2026-09-12",
    "order": 130
  },
  {
    "id": "20260912-022",
    "image": "/photos/pics/20260912-022.png",
    "date": "2026-09-12",
    "order": 131
  },
  {
    "id": "20260912-021",
    "image": "/photos/pics/20260912-021.png",
    "date": "2026-09-12",
    "order": 132
  },
  {
    "id": "20260912-020",
    "image": "/photos/pics/20260912-020.png",
    "date": "2026-09-12",
    "order": 133
  },
  {
    "id": "20260912-019",
    "image": "/photos/pics/20260912-019.png",
    "date": "2026-09-12",
    "order": 134
  },
  {
    "id": "20260912-018",
    "image": "/photos/pics/20260912-018.png",
    "date": "2026-09-12",
    "order": 135
  },
  {
    "id": "20260912-017",
    "image": "/photos/pics/20260912-017.png",
    "date": "2026-09-12",
    "order": 136
  },
  {
    "id": "20260912-016",
    "image": "/photos/pics/20260912-016.png",
    "date": "2026-09-12",
    "order": 137
  },
  {
    "id": "20260912-015",
    "image": "/photos/pics/20260912-015.png",
    "date": "2026-09-12",
    "order": 138
  },
  {
    "id": "20260912-014",
    "image": "/photos/pics/20260912-014.png",
    "date": "2026-09-12",
    "order": 139
  },
  {
    "id": "20260912-013",
    "image": "/photos/pics/20260912-013.png",
    "date": "2026-09-12",
    "order": 140
  },
  {
    "id": "20260912-012",
    "image": "/photos/pics/20260912-012.png",
    "date": "2026-09-12",
    "order": 141
  },
  {
    "id": "20260912-011",
    "image": "/photos/pics/20260912-011.png",
    "date": "2026-09-12",
    "order": 142
  },
  {
    "id": "20260912-010",
    "image": "/photos/pics/20260912-010.png",
    "date": "2026-09-12",
    "order": 143
  },
  {
    "id": "20260912-009",
    "image": "/photos/pics/20260912-009.png",
    "date": "2026-09-12",
    "order": 144
  },
  {
    "id": "20260912-008",
    "image": "/photos/pics/20260912-008.png",
    "date": "2026-09-12",
    "order": 145
  },
  {
    "id": "20260912-007",
    "image": "/photos/pics/20260912-007.png",
    "date": "2026-09-12",
    "order": 146
  },
  {
    "id": "20260912-006",
    "image": "/photos/pics/20260912-006.png",
    "date": "2026-09-12",
    "order": 147
  },
  {
    "id": "20260912-005",
    "image": "/photos/pics/20260912-005.png",
    "date": "2026-09-12",
    "order": 148
  },
  {
    "id": "20260912-004",
    "image": "/photos/pics/20260912-004.png",
    "date": "2026-09-12",
    "order": 149
  },
  {
    "id": "20260912-003",
    "image": "/photos/pics/20260912-003.png",
    "date": "2026-09-12",
    "order": 150
  },
  {
    "id": "20260912-002",
    "image": "/photos/pics/20260912-002.png",
    "date": "2026-09-12",
    "order": 151
  },
  {
    "id": "20260912-001",
    "image": "/photos/pics/20260912-001.png",
    "date": "2026-09-12",
    "order": 152
  },
  {
    "id": "20260911-003",
    "image": "/photos/pics/20260911-003.png",
    "date": "2026-09-11",
    "order": 153
  },
  {
    "id": "20260911-002",
    "image": "/photos/pics/20260911-002.png",
    "date": "2026-09-11",
    "order": 154
  }
];
