/** 
 * AUTO-GENERATED FILE.
 *
 * Do not edit this file manually.
 *
 * Generated by:
 * scripts/generate-photo-data.mjs
 */

export type GeneratedPhotoWork = {
	id: string;
	image: string;
	imageSmall: string;
	imageMedium: string;
	imageLarge: string;
	date: string;
	order: number;
};

export const generatedPhotoWorks: GeneratedPhotoWork[] = [
  {
    "id": "20260915-075",
    "image": "/photos/pics/20260915-075.png",
    "imageSmall": "/photos/optimized/20260915-075-small.webp",
    "imageMedium": "/photos/optimized/20260915-075-medium.webp",
    "imageLarge": "/photos/optimized/20260915-075-large.webp",
    "date": "2026-09-15",
    "order": 1
  },
  {
    "id": "20260915-074",
    "image": "/photos/pics/20260915-074.png",
    "imageSmall": "/photos/optimized/20260915-074-small.webp",
    "imageMedium": "/photos/optimized/20260915-074-medium.webp",
    "imageLarge": "/photos/optimized/20260915-074-large.webp",
    "date": "2026-09-15",
    "order": 2
  },
  {
    "id": "20260915-073",
    "image": "/photos/pics/20260915-073.png",
    "imageSmall": "/photos/optimized/20260915-073-small.webp",
    "imageMedium": "/photos/optimized/20260915-073-medium.webp",
    "imageLarge": "/photos/optimized/20260915-073-large.webp",
    "date": "2026-09-15",
    "order": 3
  },
  {
    "id": "20260915-072",
    "image": "/photos/pics/20260915-072.png",
    "imageSmall": "/photos/optimized/20260915-072-small.webp",
    "imageMedium": "/photos/optimized/20260915-072-medium.webp",
    "imageLarge": "/photos/optimized/20260915-072-large.webp",
    "date": "2026-09-15",
    "order": 4
  },
  {
    "id": "20260915-071",
    "image": "/photos/pics/20260915-071.png",
    "imageSmall": "/photos/optimized/20260915-071-small.webp",
    "imageMedium": "/photos/optimized/20260915-071-medium.webp",
    "imageLarge": "/photos/optimized/20260915-071-large.webp",
    "date": "2026-09-15",
    "order": 5
  },
  {
    "id": "20260915-070",
    "image": "/photos/pics/20260915-070.png",
    "imageSmall": "/photos/optimized/20260915-070-small.webp",
    "imageMedium": "/photos/optimized/20260915-070-medium.webp",
    "imageLarge": "/photos/optimized/20260915-070-large.webp",
    "date": "2026-09-15",
    "order": 6
  },
  {
    "id": "20260915-069",
    "image": "/photos/pics/20260915-069.png",
    "imageSmall": "/photos/optimized/20260915-069-small.webp",
    "imageMedium": "/photos/optimized/20260915-069-medium.webp",
    "imageLarge": "/photos/optimized/20260915-069-large.webp",
    "date": "2026-09-15",
    "order": 7
  },
  {
    "id": "20260915-068",
    "image": "/photos/pics/20260915-068.png",
    "imageSmall": "/photos/optimized/20260915-068-small.webp",
    "imageMedium": "/photos/optimized/20260915-068-medium.webp",
    "imageLarge": "/photos/optimized/20260915-068-large.webp",
    "date": "2026-09-15",
    "order": 8
  },
  {
    "id": "20260915-067",
    "image": "/photos/pics/20260915-067.png",
    "imageSmall": "/photos/optimized/20260915-067-small.webp",
    "imageMedium": "/photos/optimized/20260915-067-medium.webp",
    "imageLarge": "/photos/optimized/20260915-067-large.webp",
    "date": "2026-09-15",
    "order": 9
  },
  {
    "id": "20260915-066",
    "image": "/photos/pics/20260915-066.png",
    "imageSmall": "/photos/optimized/20260915-066-small.webp",
    "imageMedium": "/photos/optimized/20260915-066-medium.webp",
    "imageLarge": "/photos/optimized/20260915-066-large.webp",
    "date": "2026-09-15",
    "order": 10
  },
  {
    "id": "20260915-065",
    "image": "/photos/pics/20260915-065.png",
    "imageSmall": "/photos/optimized/20260915-065-small.webp",
    "imageMedium": "/photos/optimized/20260915-065-medium.webp",
    "imageLarge": "/photos/optimized/20260915-065-large.webp",
    "date": "2026-09-15",
    "order": 11
  },
  {
    "id": "20260915-064",
    "image": "/photos/pics/20260915-064.png",
    "imageSmall": "/photos/optimized/20260915-064-small.webp",
    "imageMedium": "/photos/optimized/20260915-064-medium.webp",
    "imageLarge": "/photos/optimized/20260915-064-large.webp",
    "date": "2026-09-15",
    "order": 12
  },
  {
    "id": "20260915-063",
    "image": "/photos/pics/20260915-063.png",
    "imageSmall": "/photos/optimized/20260915-063-small.webp",
    "imageMedium": "/photos/optimized/20260915-063-medium.webp",
    "imageLarge": "/photos/optimized/20260915-063-large.webp",
    "date": "2026-09-15",
    "order": 13
  },
  {
    "id": "20260915-062",
    "image": "/photos/pics/20260915-062.png",
    "imageSmall": "/photos/optimized/20260915-062-small.webp",
    "imageMedium": "/photos/optimized/20260915-062-medium.webp",
    "imageLarge": "/photos/optimized/20260915-062-large.webp",
    "date": "2026-09-15",
    "order": 14
  },
  {
    "id": "20260915-061",
    "image": "/photos/pics/20260915-061.png",
    "imageSmall": "/photos/optimized/20260915-061-small.webp",
    "imageMedium": "/photos/optimized/20260915-061-medium.webp",
    "imageLarge": "/photos/optimized/20260915-061-large.webp",
    "date": "2026-09-15",
    "order": 15
  },
  {
    "id": "20260915-060",
    "image": "/photos/pics/20260915-060.png",
    "imageSmall": "/photos/optimized/20260915-060-small.webp",
    "imageMedium": "/photos/optimized/20260915-060-medium.webp",
    "imageLarge": "/photos/optimized/20260915-060-large.webp",
    "date": "2026-09-15",
    "order": 16
  },
  {
    "id": "20260915-059",
    "image": "/photos/pics/20260915-059.png",
    "imageSmall": "/photos/optimized/20260915-059-small.webp",
    "imageMedium": "/photos/optimized/20260915-059-medium.webp",
    "imageLarge": "/photos/optimized/20260915-059-large.webp",
    "date": "2026-09-15",
    "order": 17
  },
  {
    "id": "20260915-058",
    "image": "/photos/pics/20260915-058.png",
    "imageSmall": "/photos/optimized/20260915-058-small.webp",
    "imageMedium": "/photos/optimized/20260915-058-medium.webp",
    "imageLarge": "/photos/optimized/20260915-058-large.webp",
    "date": "2026-09-15",
    "order": 18
  },
  {
    "id": "20260915-057",
    "image": "/photos/pics/20260915-057.png",
    "imageSmall": "/photos/optimized/20260915-057-small.webp",
    "imageMedium": "/photos/optimized/20260915-057-medium.webp",
    "imageLarge": "/photos/optimized/20260915-057-large.webp",
    "date": "2026-09-15",
    "order": 19
  },
  {
    "id": "20260915-056",
    "image": "/photos/pics/20260915-056.png",
    "imageSmall": "/photos/optimized/20260915-056-small.webp",
    "imageMedium": "/photos/optimized/20260915-056-medium.webp",
    "imageLarge": "/photos/optimized/20260915-056-large.webp",
    "date": "2026-09-15",
    "order": 20
  },
  {
    "id": "20260915-055",
    "image": "/photos/pics/20260915-055.png",
    "imageSmall": "/photos/optimized/20260915-055-small.webp",
    "imageMedium": "/photos/optimized/20260915-055-medium.webp",
    "imageLarge": "/photos/optimized/20260915-055-large.webp",
    "date": "2026-09-15",
    "order": 21
  },
  {
    "id": "20260915-054",
    "image": "/photos/pics/20260915-054.png",
    "imageSmall": "/photos/optimized/20260915-054-small.webp",
    "imageMedium": "/photos/optimized/20260915-054-medium.webp",
    "imageLarge": "/photos/optimized/20260915-054-large.webp",
    "date": "2026-09-15",
    "order": 22
  },
  {
    "id": "20260915-053",
    "image": "/photos/pics/20260915-053.png",
    "imageSmall": "/photos/optimized/20260915-053-small.webp",
    "imageMedium": "/photos/optimized/20260915-053-medium.webp",
    "imageLarge": "/photos/optimized/20260915-053-large.webp",
    "date": "2026-09-15",
    "order": 23
  },
  {
    "id": "20260915-052",
    "image": "/photos/pics/20260915-052.png",
    "imageSmall": "/photos/optimized/20260915-052-small.webp",
    "imageMedium": "/photos/optimized/20260915-052-medium.webp",
    "imageLarge": "/photos/optimized/20260915-052-large.webp",
    "date": "2026-09-15",
    "order": 24
  },
  {
    "id": "20260915-051",
    "image": "/photos/pics/20260915-051.png",
    "imageSmall": "/photos/optimized/20260915-051-small.webp",
    "imageMedium": "/photos/optimized/20260915-051-medium.webp",
    "imageLarge": "/photos/optimized/20260915-051-large.webp",
    "date": "2026-09-15",
    "order": 25
  },
  {
    "id": "20260915-050",
    "image": "/photos/pics/20260915-050.png",
    "imageSmall": "/photos/optimized/20260915-050-small.webp",
    "imageMedium": "/photos/optimized/20260915-050-medium.webp",
    "imageLarge": "/photos/optimized/20260915-050-large.webp",
    "date": "2026-09-15",
    "order": 26
  },
  {
    "id": "20260915-049",
    "image": "/photos/pics/20260915-049.png",
    "imageSmall": "/photos/optimized/20260915-049-small.webp",
    "imageMedium": "/photos/optimized/20260915-049-medium.webp",
    "imageLarge": "/photos/optimized/20260915-049-large.webp",
    "date": "2026-09-15",
    "order": 27
  },
  {
    "id": "20260915-048",
    "image": "/photos/pics/20260915-048.png",
    "imageSmall": "/photos/optimized/20260915-048-small.webp",
    "imageMedium": "/photos/optimized/20260915-048-medium.webp",
    "imageLarge": "/photos/optimized/20260915-048-large.webp",
    "date": "2026-09-15",
    "order": 28
  },
  {
    "id": "20260915-047",
    "image": "/photos/pics/20260915-047.png",
    "imageSmall": "/photos/optimized/20260915-047-small.webp",
    "imageMedium": "/photos/optimized/20260915-047-medium.webp",
    "imageLarge": "/photos/optimized/20260915-047-large.webp",
    "date": "2026-09-15",
    "order": 29
  },
  {
    "id": "20260915-046",
    "image": "/photos/pics/20260915-046.png",
    "imageSmall": "/photos/optimized/20260915-046-small.webp",
    "imageMedium": "/photos/optimized/20260915-046-medium.webp",
    "imageLarge": "/photos/optimized/20260915-046-large.webp",
    "date": "2026-09-15",
    "order": 30
  },
  {
    "id": "20260915-045",
    "image": "/photos/pics/20260915-045.png",
    "imageSmall": "/photos/optimized/20260915-045-small.webp",
    "imageMedium": "/photos/optimized/20260915-045-medium.webp",
    "imageLarge": "/photos/optimized/20260915-045-large.webp",
    "date": "2026-09-15",
    "order": 31
  },
  {
    "id": "20260915-044",
    "image": "/photos/pics/20260915-044.png",
    "imageSmall": "/photos/optimized/20260915-044-small.webp",
    "imageMedium": "/photos/optimized/20260915-044-medium.webp",
    "imageLarge": "/photos/optimized/20260915-044-large.webp",
    "date": "2026-09-15",
    "order": 32
  },
  {
    "id": "20260915-043",
    "image": "/photos/pics/20260915-043.png",
    "imageSmall": "/photos/optimized/20260915-043-small.webp",
    "imageMedium": "/photos/optimized/20260915-043-medium.webp",
    "imageLarge": "/photos/optimized/20260915-043-large.webp",
    "date": "2026-09-15",
    "order": 33
  },
  {
    "id": "20260915-042",
    "image": "/photos/pics/20260915-042.png",
    "imageSmall": "/photos/optimized/20260915-042-small.webp",
    "imageMedium": "/photos/optimized/20260915-042-medium.webp",
    "imageLarge": "/photos/optimized/20260915-042-large.webp",
    "date": "2026-09-15",
    "order": 34
  },
  {
    "id": "20260915-041",
    "image": "/photos/pics/20260915-041.png",
    "imageSmall": "/photos/optimized/20260915-041-small.webp",
    "imageMedium": "/photos/optimized/20260915-041-medium.webp",
    "imageLarge": "/photos/optimized/20260915-041-large.webp",
    "date": "2026-09-15",
    "order": 35
  },
  {
    "id": "20260915-040",
    "image": "/photos/pics/20260915-040.png",
    "imageSmall": "/photos/optimized/20260915-040-small.webp",
    "imageMedium": "/photos/optimized/20260915-040-medium.webp",
    "imageLarge": "/photos/optimized/20260915-040-large.webp",
    "date": "2026-09-15",
    "order": 36
  },
  {
    "id": "20260915-039",
    "image": "/photos/pics/20260915-039.png",
    "imageSmall": "/photos/optimized/20260915-039-small.webp",
    "imageMedium": "/photos/optimized/20260915-039-medium.webp",
    "imageLarge": "/photos/optimized/20260915-039-large.webp",
    "date": "2026-09-15",
    "order": 37
  },
  {
    "id": "20260915-038",
    "image": "/photos/pics/20260915-038.png",
    "imageSmall": "/photos/optimized/20260915-038-small.webp",
    "imageMedium": "/photos/optimized/20260915-038-medium.webp",
    "imageLarge": "/photos/optimized/20260915-038-large.webp",
    "date": "2026-09-15",
    "order": 38
  },
  {
    "id": "20260915-037",
    "image": "/photos/pics/20260915-037.png",
    "imageSmall": "/photos/optimized/20260915-037-small.webp",
    "imageMedium": "/photos/optimized/20260915-037-medium.webp",
    "imageLarge": "/photos/optimized/20260915-037-large.webp",
    "date": "2026-09-15",
    "order": 39
  },
  {
    "id": "20260915-036",
    "image": "/photos/pics/20260915-036.png",
    "imageSmall": "/photos/optimized/20260915-036-small.webp",
    "imageMedium": "/photos/optimized/20260915-036-medium.webp",
    "imageLarge": "/photos/optimized/20260915-036-large.webp",
    "date": "2026-09-15",
    "order": 40
  },
  {
    "id": "20260915-035",
    "image": "/photos/pics/20260915-035.png",
    "imageSmall": "/photos/optimized/20260915-035-small.webp",
    "imageMedium": "/photos/optimized/20260915-035-medium.webp",
    "imageLarge": "/photos/optimized/20260915-035-large.webp",
    "date": "2026-09-15",
    "order": 41
  },
  {
    "id": "20260915-034",
    "image": "/photos/pics/20260915-034.png",
    "imageSmall": "/photos/optimized/20260915-034-small.webp",
    "imageMedium": "/photos/optimized/20260915-034-medium.webp",
    "imageLarge": "/photos/optimized/20260915-034-large.webp",
    "date": "2026-09-15",
    "order": 42
  },
  {
    "id": "20260915-033",
    "image": "/photos/pics/20260915-033.png",
    "imageSmall": "/photos/optimized/20260915-033-small.webp",
    "imageMedium": "/photos/optimized/20260915-033-medium.webp",
    "imageLarge": "/photos/optimized/20260915-033-large.webp",
    "date": "2026-09-15",
    "order": 43
  },
  {
    "id": "20260915-032",
    "image": "/photos/pics/20260915-032.png",
    "imageSmall": "/photos/optimized/20260915-032-small.webp",
    "imageMedium": "/photos/optimized/20260915-032-medium.webp",
    "imageLarge": "/photos/optimized/20260915-032-large.webp",
    "date": "2026-09-15",
    "order": 44
  },
  {
    "id": "20260915-031",
    "image": "/photos/pics/20260915-031.png",
    "imageSmall": "/photos/optimized/20260915-031-small.webp",
    "imageMedium": "/photos/optimized/20260915-031-medium.webp",
    "imageLarge": "/photos/optimized/20260915-031-large.webp",
    "date": "2026-09-15",
    "order": 45
  },
  {
    "id": "20260915-030",
    "image": "/photos/pics/20260915-030.png",
    "imageSmall": "/photos/optimized/20260915-030-small.webp",
    "imageMedium": "/photos/optimized/20260915-030-medium.webp",
    "imageLarge": "/photos/optimized/20260915-030-large.webp",
    "date": "2026-09-15",
    "order": 46
  },
  {
    "id": "20260915-029",
    "image": "/photos/pics/20260915-029.png",
    "imageSmall": "/photos/optimized/20260915-029-small.webp",
    "imageMedium": "/photos/optimized/20260915-029-medium.webp",
    "imageLarge": "/photos/optimized/20260915-029-large.webp",
    "date": "2026-09-15",
    "order": 47
  },
  {
    "id": "20260915-028",
    "image": "/photos/pics/20260915-028.png",
    "imageSmall": "/photos/optimized/20260915-028-small.webp",
    "imageMedium": "/photos/optimized/20260915-028-medium.webp",
    "imageLarge": "/photos/optimized/20260915-028-large.webp",
    "date": "2026-09-15",
    "order": 48
  },
  {
    "id": "20260915-027",
    "image": "/photos/pics/20260915-027.png",
    "imageSmall": "/photos/optimized/20260915-027-small.webp",
    "imageMedium": "/photos/optimized/20260915-027-medium.webp",
    "imageLarge": "/photos/optimized/20260915-027-large.webp",
    "date": "2026-09-15",
    "order": 49
  },
  {
    "id": "20260915-026",
    "image": "/photos/pics/20260915-026.png",
    "imageSmall": "/photos/optimized/20260915-026-small.webp",
    "imageMedium": "/photos/optimized/20260915-026-medium.webp",
    "imageLarge": "/photos/optimized/20260915-026-large.webp",
    "date": "2026-09-15",
    "order": 50
  },
  {
    "id": "20260915-025",
    "image": "/photos/pics/20260915-025.png",
    "imageSmall": "/photos/optimized/20260915-025-small.webp",
    "imageMedium": "/photos/optimized/20260915-025-medium.webp",
    "imageLarge": "/photos/optimized/20260915-025-large.webp",
    "date": "2026-09-15",
    "order": 51
  },
  {
    "id": "20260915-024",
    "image": "/photos/pics/20260915-024.png",
    "imageSmall": "/photos/optimized/20260915-024-small.webp",
    "imageMedium": "/photos/optimized/20260915-024-medium.webp",
    "imageLarge": "/photos/optimized/20260915-024-large.webp",
    "date": "2026-09-15",
    "order": 52
  },
  {
    "id": "20260915-023",
    "image": "/photos/pics/20260915-023.png",
    "imageSmall": "/photos/optimized/20260915-023-small.webp",
    "imageMedium": "/photos/optimized/20260915-023-medium.webp",
    "imageLarge": "/photos/optimized/20260915-023-large.webp",
    "date": "2026-09-15",
    "order": 53
  },
  {
    "id": "20260915-022",
    "image": "/photos/pics/20260915-022.png",
    "imageSmall": "/photos/optimized/20260915-022-small.webp",
    "imageMedium": "/photos/optimized/20260915-022-medium.webp",
    "imageLarge": "/photos/optimized/20260915-022-large.webp",
    "date": "2026-09-15",
    "order": 54
  },
  {
    "id": "20260915-021",
    "image": "/photos/pics/20260915-021.png",
    "imageSmall": "/photos/optimized/20260915-021-small.webp",
    "imageMedium": "/photos/optimized/20260915-021-medium.webp",
    "imageLarge": "/photos/optimized/20260915-021-large.webp",
    "date": "2026-09-15",
    "order": 55
  },
  {
    "id": "20260915-020",
    "image": "/photos/pics/20260915-020.png",
    "imageSmall": "/photos/optimized/20260915-020-small.webp",
    "imageMedium": "/photos/optimized/20260915-020-medium.webp",
    "imageLarge": "/photos/optimized/20260915-020-large.webp",
    "date": "2026-09-15",
    "order": 56
  },
  {
    "id": "20260915-019",
    "image": "/photos/pics/20260915-019.png",
    "imageSmall": "/photos/optimized/20260915-019-small.webp",
    "imageMedium": "/photos/optimized/20260915-019-medium.webp",
    "imageLarge": "/photos/optimized/20260915-019-large.webp",
    "date": "2026-09-15",
    "order": 57
  },
  {
    "id": "20260915-018",
    "image": "/photos/pics/20260915-018.png",
    "imageSmall": "/photos/optimized/20260915-018-small.webp",
    "imageMedium": "/photos/optimized/20260915-018-medium.webp",
    "imageLarge": "/photos/optimized/20260915-018-large.webp",
    "date": "2026-09-15",
    "order": 58
  },
  {
    "id": "20260915-017",
    "image": "/photos/pics/20260915-017.png",
    "imageSmall": "/photos/optimized/20260915-017-small.webp",
    "imageMedium": "/photos/optimized/20260915-017-medium.webp",
    "imageLarge": "/photos/optimized/20260915-017-large.webp",
    "date": "2026-09-15",
    "order": 59
  },
  {
    "id": "20260915-016",
    "image": "/photos/pics/20260915-016.png",
    "imageSmall": "/photos/optimized/20260915-016-small.webp",
    "imageMedium": "/photos/optimized/20260915-016-medium.webp",
    "imageLarge": "/photos/optimized/20260915-016-large.webp",
    "date": "2026-09-15",
    "order": 60
  },
  {
    "id": "20260915-015",
    "image": "/photos/pics/20260915-015.png",
    "imageSmall": "/photos/optimized/20260915-015-small.webp",
    "imageMedium": "/photos/optimized/20260915-015-medium.webp",
    "imageLarge": "/photos/optimized/20260915-015-large.webp",
    "date": "2026-09-15",
    "order": 61
  },
  {
    "id": "20260915-014",
    "image": "/photos/pics/20260915-014.png",
    "imageSmall": "/photos/optimized/20260915-014-small.webp",
    "imageMedium": "/photos/optimized/20260915-014-medium.webp",
    "imageLarge": "/photos/optimized/20260915-014-large.webp",
    "date": "2026-09-15",
    "order": 62
  },
  {
    "id": "20260915-013",
    "image": "/photos/pics/20260915-013.png",
    "imageSmall": "/photos/optimized/20260915-013-small.webp",
    "imageMedium": "/photos/optimized/20260915-013-medium.webp",
    "imageLarge": "/photos/optimized/20260915-013-large.webp",
    "date": "2026-09-15",
    "order": 63
  },
  {
    "id": "20260915-012",
    "image": "/photos/pics/20260915-012.png",
    "imageSmall": "/photos/optimized/20260915-012-small.webp",
    "imageMedium": "/photos/optimized/20260915-012-medium.webp",
    "imageLarge": "/photos/optimized/20260915-012-large.webp",
    "date": "2026-09-15",
    "order": 64
  },
  {
    "id": "20260915-011",
    "image": "/photos/pics/20260915-011.png",
    "imageSmall": "/photos/optimized/20260915-011-small.webp",
    "imageMedium": "/photos/optimized/20260915-011-medium.webp",
    "imageLarge": "/photos/optimized/20260915-011-large.webp",
    "date": "2026-09-15",
    "order": 65
  },
  {
    "id": "20260915-010",
    "image": "/photos/pics/20260915-010.png",
    "imageSmall": "/photos/optimized/20260915-010-small.webp",
    "imageMedium": "/photos/optimized/20260915-010-medium.webp",
    "imageLarge": "/photos/optimized/20260915-010-large.webp",
    "date": "2026-09-15",
    "order": 66
  },
  {
    "id": "20260915-009",
    "image": "/photos/pics/20260915-009.png",
    "imageSmall": "/photos/optimized/20260915-009-small.webp",
    "imageMedium": "/photos/optimized/20260915-009-medium.webp",
    "imageLarge": "/photos/optimized/20260915-009-large.webp",
    "date": "2026-09-15",
    "order": 67
  },
  {
    "id": "20260915-008",
    "image": "/photos/pics/20260915-008.png",
    "imageSmall": "/photos/optimized/20260915-008-small.webp",
    "imageMedium": "/photos/optimized/20260915-008-medium.webp",
    "imageLarge": "/photos/optimized/20260915-008-large.webp",
    "date": "2026-09-15",
    "order": 68
  },
  {
    "id": "20260915-007",
    "image": "/photos/pics/20260915-007.png",
    "imageSmall": "/photos/optimized/20260915-007-small.webp",
    "imageMedium": "/photos/optimized/20260915-007-medium.webp",
    "imageLarge": "/photos/optimized/20260915-007-large.webp",
    "date": "2026-09-15",
    "order": 69
  },
  {
    "id": "20260915-006",
    "image": "/photos/pics/20260915-006.png",
    "imageSmall": "/photos/optimized/20260915-006-small.webp",
    "imageMedium": "/photos/optimized/20260915-006-medium.webp",
    "imageLarge": "/photos/optimized/20260915-006-large.webp",
    "date": "2026-09-15",
    "order": 70
  },
  {
    "id": "20260915-005",
    "image": "/photos/pics/20260915-005.png",
    "imageSmall": "/photos/optimized/20260915-005-small.webp",
    "imageMedium": "/photos/optimized/20260915-005-medium.webp",
    "imageLarge": "/photos/optimized/20260915-005-large.webp",
    "date": "2026-09-15",
    "order": 71
  },
  {
    "id": "20260915-004",
    "image": "/photos/pics/20260915-004.png",
    "imageSmall": "/photos/optimized/20260915-004-small.webp",
    "imageMedium": "/photos/optimized/20260915-004-medium.webp",
    "imageLarge": "/photos/optimized/20260915-004-large.webp",
    "date": "2026-09-15",
    "order": 72
  },
  {
    "id": "20260915-003",
    "image": "/photos/pics/20260915-003.png",
    "imageSmall": "/photos/optimized/20260915-003-small.webp",
    "imageMedium": "/photos/optimized/20260915-003-medium.webp",
    "imageLarge": "/photos/optimized/20260915-003-large.webp",
    "date": "2026-09-15",
    "order": 73
  },
  {
    "id": "20260915-002",
    "image": "/photos/pics/20260915-002.png",
    "imageSmall": "/photos/optimized/20260915-002-small.webp",
    "imageMedium": "/photos/optimized/20260915-002-medium.webp",
    "imageLarge": "/photos/optimized/20260915-002-large.webp",
    "date": "2026-09-15",
    "order": 74
  },
  {
    "id": "20260915-001",
    "image": "/photos/pics/20260915-001.png",
    "imageSmall": "/photos/optimized/20260915-001-small.webp",
    "imageMedium": "/photos/optimized/20260915-001-medium.webp",
    "imageLarge": "/photos/optimized/20260915-001-large.webp",
    "date": "2026-09-15",
    "order": 75
  },
  {
    "id": "20260914-036",
    "image": "/photos/pics/20260914-036.png",
    "imageSmall": "/photos/optimized/20260914-036-small.webp",
    "imageMedium": "/photos/optimized/20260914-036-medium.webp",
    "imageLarge": "/photos/optimized/20260914-036-large.webp",
    "date": "2026-09-14",
    "order": 76
  },
  {
    "id": "20260914-035",
    "image": "/photos/pics/20260914-035.png",
    "imageSmall": "/photos/optimized/20260914-035-small.webp",
    "imageMedium": "/photos/optimized/20260914-035-medium.webp",
    "imageLarge": "/photos/optimized/20260914-035-large.webp",
    "date": "2026-09-14",
    "order": 77
  },
  {
    "id": "20260914-034",
    "image": "/photos/pics/20260914-034.png",
    "imageSmall": "/photos/optimized/20260914-034-small.webp",
    "imageMedium": "/photos/optimized/20260914-034-medium.webp",
    "imageLarge": "/photos/optimized/20260914-034-large.webp",
    "date": "2026-09-14",
    "order": 78
  },
  {
    "id": "20260914-033",
    "image": "/photos/pics/20260914-033.png",
    "imageSmall": "/photos/optimized/20260914-033-small.webp",
    "imageMedium": "/photos/optimized/20260914-033-medium.webp",
    "imageLarge": "/photos/optimized/20260914-033-large.webp",
    "date": "2026-09-14",
    "order": 79
  },
  {
    "id": "20260914-032",
    "image": "/photos/pics/20260914-032.png",
    "imageSmall": "/photos/optimized/20260914-032-small.webp",
    "imageMedium": "/photos/optimized/20260914-032-medium.webp",
    "imageLarge": "/photos/optimized/20260914-032-large.webp",
    "date": "2026-09-14",
    "order": 80
  },
  {
    "id": "20260914-031",
    "image": "/photos/pics/20260914-031.png",
    "imageSmall": "/photos/optimized/20260914-031-small.webp",
    "imageMedium": "/photos/optimized/20260914-031-medium.webp",
    "imageLarge": "/photos/optimized/20260914-031-large.webp",
    "date": "2026-09-14",
    "order": 81
  },
  {
    "id": "20260914-030",
    "image": "/photos/pics/20260914-030.png",
    "imageSmall": "/photos/optimized/20260914-030-small.webp",
    "imageMedium": "/photos/optimized/20260914-030-medium.webp",
    "imageLarge": "/photos/optimized/20260914-030-large.webp",
    "date": "2026-09-14",
    "order": 82
  },
  {
    "id": "20260914-029",
    "image": "/photos/pics/20260914-029.png",
    "imageSmall": "/photos/optimized/20260914-029-small.webp",
    "imageMedium": "/photos/optimized/20260914-029-medium.webp",
    "imageLarge": "/photos/optimized/20260914-029-large.webp",
    "date": "2026-09-14",
    "order": 83
  },
  {
    "id": "20260914-028",
    "image": "/photos/pics/20260914-028.png",
    "imageSmall": "/photos/optimized/20260914-028-small.webp",
    "imageMedium": "/photos/optimized/20260914-028-medium.webp",
    "imageLarge": "/photos/optimized/20260914-028-large.webp",
    "date": "2026-09-14",
    "order": 84
  },
  {
    "id": "20260914-027",
    "image": "/photos/pics/20260914-027.png",
    "imageSmall": "/photos/optimized/20260914-027-small.webp",
    "imageMedium": "/photos/optimized/20260914-027-medium.webp",
    "imageLarge": "/photos/optimized/20260914-027-large.webp",
    "date": "2026-09-14",
    "order": 85
  },
  {
    "id": "20260914-026",
    "image": "/photos/pics/20260914-026.png",
    "imageSmall": "/photos/optimized/20260914-026-small.webp",
    "imageMedium": "/photos/optimized/20260914-026-medium.webp",
    "imageLarge": "/photos/optimized/20260914-026-large.webp",
    "date": "2026-09-14",
    "order": 86
  },
  {
    "id": "20260914-025",
    "image": "/photos/pics/20260914-025.png",
    "imageSmall": "/photos/optimized/20260914-025-small.webp",
    "imageMedium": "/photos/optimized/20260914-025-medium.webp",
    "imageLarge": "/photos/optimized/20260914-025-large.webp",
    "date": "2026-09-14",
    "order": 87
  },
  {
    "id": "20260914-024",
    "image": "/photos/pics/20260914-024.png",
    "imageSmall": "/photos/optimized/20260914-024-small.webp",
    "imageMedium": "/photos/optimized/20260914-024-medium.webp",
    "imageLarge": "/photos/optimized/20260914-024-large.webp",
    "date": "2026-09-14",
    "order": 88
  },
  {
    "id": "20260914-023",
    "image": "/photos/pics/20260914-023.png",
    "imageSmall": "/photos/optimized/20260914-023-small.webp",
    "imageMedium": "/photos/optimized/20260914-023-medium.webp",
    "imageLarge": "/photos/optimized/20260914-023-large.webp",
    "date": "2026-09-14",
    "order": 89
  },
  {
    "id": "20260914-022",
    "image": "/photos/pics/20260914-022.png",
    "imageSmall": "/photos/optimized/20260914-022-small.webp",
    "imageMedium": "/photos/optimized/20260914-022-medium.webp",
    "imageLarge": "/photos/optimized/20260914-022-large.webp",
    "date": "2026-09-14",
    "order": 90
  },
  {
    "id": "20260914-021",
    "image": "/photos/pics/20260914-021.png",
    "imageSmall": "/photos/optimized/20260914-021-small.webp",
    "imageMedium": "/photos/optimized/20260914-021-medium.webp",
    "imageLarge": "/photos/optimized/20260914-021-large.webp",
    "date": "2026-09-14",
    "order": 91
  },
  {
    "id": "20260914-020",
    "image": "/photos/pics/20260914-020.png",
    "imageSmall": "/photos/optimized/20260914-020-small.webp",
    "imageMedium": "/photos/optimized/20260914-020-medium.webp",
    "imageLarge": "/photos/optimized/20260914-020-large.webp",
    "date": "2026-09-14",
    "order": 92
  },
  {
    "id": "20260914-019",
    "image": "/photos/pics/20260914-019.png",
    "imageSmall": "/photos/optimized/20260914-019-small.webp",
    "imageMedium": "/photos/optimized/20260914-019-medium.webp",
    "imageLarge": "/photos/optimized/20260914-019-large.webp",
    "date": "2026-09-14",
    "order": 93
  },
  {
    "id": "20260914-018",
    "image": "/photos/pics/20260914-018.png",
    "imageSmall": "/photos/optimized/20260914-018-small.webp",
    "imageMedium": "/photos/optimized/20260914-018-medium.webp",
    "imageLarge": "/photos/optimized/20260914-018-large.webp",
    "date": "2026-09-14",
    "order": 94
  },
  {
    "id": "20260914-017",
    "image": "/photos/pics/20260914-017.png",
    "imageSmall": "/photos/optimized/20260914-017-small.webp",
    "imageMedium": "/photos/optimized/20260914-017-medium.webp",
    "imageLarge": "/photos/optimized/20260914-017-large.webp",
    "date": "2026-09-14",
    "order": 95
  },
  {
    "id": "20260914-016",
    "image": "/photos/pics/20260914-016.png",
    "imageSmall": "/photos/optimized/20260914-016-small.webp",
    "imageMedium": "/photos/optimized/20260914-016-medium.webp",
    "imageLarge": "/photos/optimized/20260914-016-large.webp",
    "date": "2026-09-14",
    "order": 96
  },
  {
    "id": "20260914-015",
    "image": "/photos/pics/20260914-015.png",
    "imageSmall": "/photos/optimized/20260914-015-small.webp",
    "imageMedium": "/photos/optimized/20260914-015-medium.webp",
    "imageLarge": "/photos/optimized/20260914-015-large.webp",
    "date": "2026-09-14",
    "order": 97
  },
  {
    "id": "20260914-014",
    "image": "/photos/pics/20260914-014.png",
    "imageSmall": "/photos/optimized/20260914-014-small.webp",
    "imageMedium": "/photos/optimized/20260914-014-medium.webp",
    "imageLarge": "/photos/optimized/20260914-014-large.webp",
    "date": "2026-09-14",
    "order": 98
  },
  {
    "id": "20260914-013",
    "image": "/photos/pics/20260914-013.png",
    "imageSmall": "/photos/optimized/20260914-013-small.webp",
    "imageMedium": "/photos/optimized/20260914-013-medium.webp",
    "imageLarge": "/photos/optimized/20260914-013-large.webp",
    "date": "2026-09-14",
    "order": 99
  },
  {
    "id": "20260914-012",
    "image": "/photos/pics/20260914-012.png",
    "imageSmall": "/photos/optimized/20260914-012-small.webp",
    "imageMedium": "/photos/optimized/20260914-012-medium.webp",
    "imageLarge": "/photos/optimized/20260914-012-large.webp",
    "date": "2026-09-14",
    "order": 100
  },
  {
    "id": "20260914-011",
    "image": "/photos/pics/20260914-011.png",
    "imageSmall": "/photos/optimized/20260914-011-small.webp",
    "imageMedium": "/photos/optimized/20260914-011-medium.webp",
    "imageLarge": "/photos/optimized/20260914-011-large.webp",
    "date": "2026-09-14",
    "order": 101
  },
  {
    "id": "20260914-010",
    "image": "/photos/pics/20260914-010.png",
    "imageSmall": "/photos/optimized/20260914-010-small.webp",
    "imageMedium": "/photos/optimized/20260914-010-medium.webp",
    "imageLarge": "/photos/optimized/20260914-010-large.webp",
    "date": "2026-09-14",
    "order": 102
  },
  {
    "id": "20260914-009",
    "image": "/photos/pics/20260914-009.png",
    "imageSmall": "/photos/optimized/20260914-009-small.webp",
    "imageMedium": "/photos/optimized/20260914-009-medium.webp",
    "imageLarge": "/photos/optimized/20260914-009-large.webp",
    "date": "2026-09-14",
    "order": 103
  },
  {
    "id": "20260914-008",
    "image": "/photos/pics/20260914-008.png",
    "imageSmall": "/photos/optimized/20260914-008-small.webp",
    "imageMedium": "/photos/optimized/20260914-008-medium.webp",
    "imageLarge": "/photos/optimized/20260914-008-large.webp",
    "date": "2026-09-14",
    "order": 104
  },
  {
    "id": "20260914-007",
    "image": "/photos/pics/20260914-007.png",
    "imageSmall": "/photos/optimized/20260914-007-small.webp",
    "imageMedium": "/photos/optimized/20260914-007-medium.webp",
    "imageLarge": "/photos/optimized/20260914-007-large.webp",
    "date": "2026-09-14",
    "order": 105
  },
  {
    "id": "20260914-006",
    "image": "/photos/pics/20260914-006.png",
    "imageSmall": "/photos/optimized/20260914-006-small.webp",
    "imageMedium": "/photos/optimized/20260914-006-medium.webp",
    "imageLarge": "/photos/optimized/20260914-006-large.webp",
    "date": "2026-09-14",
    "order": 106
  },
  {
    "id": "20260914-005",
    "image": "/photos/pics/20260914-005.png",
    "imageSmall": "/photos/optimized/20260914-005-small.webp",
    "imageMedium": "/photos/optimized/20260914-005-medium.webp",
    "imageLarge": "/photos/optimized/20260914-005-large.webp",
    "date": "2026-09-14",
    "order": 107
  },
  {
    "id": "20260914-004",
    "image": "/photos/pics/20260914-004.png",
    "imageSmall": "/photos/optimized/20260914-004-small.webp",
    "imageMedium": "/photos/optimized/20260914-004-medium.webp",
    "imageLarge": "/photos/optimized/20260914-004-large.webp",
    "date": "2026-09-14",
    "order": 108
  },
  {
    "id": "20260914-003",
    "image": "/photos/pics/20260914-003.png",
    "imageSmall": "/photos/optimized/20260914-003-small.webp",
    "imageMedium": "/photos/optimized/20260914-003-medium.webp",
    "imageLarge": "/photos/optimized/20260914-003-large.webp",
    "date": "2026-09-14",
    "order": 109
  },
  {
    "id": "20260914-002",
    "image": "/photos/pics/20260914-002.png",
    "imageSmall": "/photos/optimized/20260914-002-small.webp",
    "imageMedium": "/photos/optimized/20260914-002-medium.webp",
    "imageLarge": "/photos/optimized/20260914-002-large.webp",
    "date": "2026-09-14",
    "order": 110
  },
  {
    "id": "20260914-001",
    "image": "/photos/pics/20260914-001.png",
    "imageSmall": "/photos/optimized/20260914-001-small.webp",
    "imageMedium": "/photos/optimized/20260914-001-medium.webp",
    "imageLarge": "/photos/optimized/20260914-001-large.webp",
    "date": "2026-09-14",
    "order": 111
  },
  {
    "id": "20260913-047",
    "image": "/photos/pics/20260913-047.png",
    "imageSmall": "/photos/optimized/20260913-047-small.webp",
    "imageMedium": "/photos/optimized/20260913-047-medium.webp",
    "imageLarge": "/photos/optimized/20260913-047-large.webp",
    "date": "2026-09-13",
    "order": 112
  },
  {
    "id": "20260913-046",
    "image": "/photos/pics/20260913-046.png",
    "imageSmall": "/photos/optimized/20260913-046-small.webp",
    "imageMedium": "/photos/optimized/20260913-046-medium.webp",
    "imageLarge": "/photos/optimized/20260913-046-large.webp",
    "date": "2026-09-13",
    "order": 113
  },
  {
    "id": "20260913-045",
    "image": "/photos/pics/20260913-045.png",
    "imageSmall": "/photos/optimized/20260913-045-small.webp",
    "imageMedium": "/photos/optimized/20260913-045-medium.webp",
    "imageLarge": "/photos/optimized/20260913-045-large.webp",
    "date": "2026-09-13",
    "order": 114
  },
  {
    "id": "20260913-044",
    "image": "/photos/pics/20260913-044.png",
    "imageSmall": "/photos/optimized/20260913-044-small.webp",
    "imageMedium": "/photos/optimized/20260913-044-medium.webp",
    "imageLarge": "/photos/optimized/20260913-044-large.webp",
    "date": "2026-09-13",
    "order": 115
  },
  {
    "id": "20260913-043",
    "image": "/photos/pics/20260913-043.png",
    "imageSmall": "/photos/optimized/20260913-043-small.webp",
    "imageMedium": "/photos/optimized/20260913-043-medium.webp",
    "imageLarge": "/photos/optimized/20260913-043-large.webp",
    "date": "2026-09-13",
    "order": 116
  },
  {
    "id": "20260913-042",
    "image": "/photos/pics/20260913-042.png",
    "imageSmall": "/photos/optimized/20260913-042-small.webp",
    "imageMedium": "/photos/optimized/20260913-042-medium.webp",
    "imageLarge": "/photos/optimized/20260913-042-large.webp",
    "date": "2026-09-13",
    "order": 117
  },
  {
    "id": "20260913-041",
    "image": "/photos/pics/20260913-041.png",
    "imageSmall": "/photos/optimized/20260913-041-small.webp",
    "imageMedium": "/photos/optimized/20260913-041-medium.webp",
    "imageLarge": "/photos/optimized/20260913-041-large.webp",
    "date": "2026-09-13",
    "order": 118
  },
  {
    "id": "20260913-040",
    "image": "/photos/pics/20260913-040.png",
    "imageSmall": "/photos/optimized/20260913-040-small.webp",
    "imageMedium": "/photos/optimized/20260913-040-medium.webp",
    "imageLarge": "/photos/optimized/20260913-040-large.webp",
    "date": "2026-09-13",
    "order": 119
  },
  {
    "id": "20260913-039",
    "image": "/photos/pics/20260913-039.png",
    "imageSmall": "/photos/optimized/20260913-039-small.webp",
    "imageMedium": "/photos/optimized/20260913-039-medium.webp",
    "imageLarge": "/photos/optimized/20260913-039-large.webp",
    "date": "2026-09-13",
    "order": 120
  },
  {
    "id": "20260913-038",
    "image": "/photos/pics/20260913-038.png",
    "imageSmall": "/photos/optimized/20260913-038-small.webp",
    "imageMedium": "/photos/optimized/20260913-038-medium.webp",
    "imageLarge": "/photos/optimized/20260913-038-large.webp",
    "date": "2026-09-13",
    "order": 121
  },
  {
    "id": "20260913-037",
    "image": "/photos/pics/20260913-037.png",
    "imageSmall": "/photos/optimized/20260913-037-small.webp",
    "imageMedium": "/photos/optimized/20260913-037-medium.webp",
    "imageLarge": "/photos/optimized/20260913-037-large.webp",
    "date": "2026-09-13",
    "order": 122
  },
  {
    "id": "20260913-036",
    "image": "/photos/pics/20260913-036.png",
    "imageSmall": "/photos/optimized/20260913-036-small.webp",
    "imageMedium": "/photos/optimized/20260913-036-medium.webp",
    "imageLarge": "/photos/optimized/20260913-036-large.webp",
    "date": "2026-09-13",
    "order": 123
  },
  {
    "id": "20260913-035",
    "image": "/photos/pics/20260913-035.png",
    "imageSmall": "/photos/optimized/20260913-035-small.webp",
    "imageMedium": "/photos/optimized/20260913-035-medium.webp",
    "imageLarge": "/photos/optimized/20260913-035-large.webp",
    "date": "2026-09-13",
    "order": 124
  },
  {
    "id": "20260913-034",
    "image": "/photos/pics/20260913-034.png",
    "imageSmall": "/photos/optimized/20260913-034-small.webp",
    "imageMedium": "/photos/optimized/20260913-034-medium.webp",
    "imageLarge": "/photos/optimized/20260913-034-large.webp",
    "date": "2026-09-13",
    "order": 125
  },
  {
    "id": "20260913-033",
    "image": "/photos/pics/20260913-033.png",
    "imageSmall": "/photos/optimized/20260913-033-small.webp",
    "imageMedium": "/photos/optimized/20260913-033-medium.webp",
    "imageLarge": "/photos/optimized/20260913-033-large.webp",
    "date": "2026-09-13",
    "order": 126
  },
  {
    "id": "20260913-032",
    "image": "/photos/pics/20260913-032.png",
    "imageSmall": "/photos/optimized/20260913-032-small.webp",
    "imageMedium": "/photos/optimized/20260913-032-medium.webp",
    "imageLarge": "/photos/optimized/20260913-032-large.webp",
    "date": "2026-09-13",
    "order": 127
  },
  {
    "id": "20260913-031",
    "image": "/photos/pics/20260913-031.png",
    "imageSmall": "/photos/optimized/20260913-031-small.webp",
    "imageMedium": "/photos/optimized/20260913-031-medium.webp",
    "imageLarge": "/photos/optimized/20260913-031-large.webp",
    "date": "2026-09-13",
    "order": 128
  },
  {
    "id": "20260913-030",
    "image": "/photos/pics/20260913-030.png",
    "imageSmall": "/photos/optimized/20260913-030-small.webp",
    "imageMedium": "/photos/optimized/20260913-030-medium.webp",
    "imageLarge": "/photos/optimized/20260913-030-large.webp",
    "date": "2026-09-13",
    "order": 129
  },
  {
    "id": "20260913-029",
    "image": "/photos/pics/20260913-029.png",
    "imageSmall": "/photos/optimized/20260913-029-small.webp",
    "imageMedium": "/photos/optimized/20260913-029-medium.webp",
    "imageLarge": "/photos/optimized/20260913-029-large.webp",
    "date": "2026-09-13",
    "order": 130
  },
  {
    "id": "20260913-028",
    "image": "/photos/pics/20260913-028.png",
    "imageSmall": "/photos/optimized/20260913-028-small.webp",
    "imageMedium": "/photos/optimized/20260913-028-medium.webp",
    "imageLarge": "/photos/optimized/20260913-028-large.webp",
    "date": "2026-09-13",
    "order": 131
  },
  {
    "id": "20260913-027",
    "image": "/photos/pics/20260913-027.png",
    "imageSmall": "/photos/optimized/20260913-027-small.webp",
    "imageMedium": "/photos/optimized/20260913-027-medium.webp",
    "imageLarge": "/photos/optimized/20260913-027-large.webp",
    "date": "2026-09-13",
    "order": 132
  },
  {
    "id": "20260913-026",
    "image": "/photos/pics/20260913-026.png",
    "imageSmall": "/photos/optimized/20260913-026-small.webp",
    "imageMedium": "/photos/optimized/20260913-026-medium.webp",
    "imageLarge": "/photos/optimized/20260913-026-large.webp",
    "date": "2026-09-13",
    "order": 133
  },
  {
    "id": "20260913-025",
    "image": "/photos/pics/20260913-025.png",
    "imageSmall": "/photos/optimized/20260913-025-small.webp",
    "imageMedium": "/photos/optimized/20260913-025-medium.webp",
    "imageLarge": "/photos/optimized/20260913-025-large.webp",
    "date": "2026-09-13",
    "order": 134
  },
  {
    "id": "20260913-024",
    "image": "/photos/pics/20260913-024.png",
    "imageSmall": "/photos/optimized/20260913-024-small.webp",
    "imageMedium": "/photos/optimized/20260913-024-medium.webp",
    "imageLarge": "/photos/optimized/20260913-024-large.webp",
    "date": "2026-09-13",
    "order": 135
  },
  {
    "id": "20260913-023",
    "image": "/photos/pics/20260913-023.png",
    "imageSmall": "/photos/optimized/20260913-023-small.webp",
    "imageMedium": "/photos/optimized/20260913-023-medium.webp",
    "imageLarge": "/photos/optimized/20260913-023-large.webp",
    "date": "2026-09-13",
    "order": 136
  },
  {
    "id": "20260913-022",
    "image": "/photos/pics/20260913-022.png",
    "imageSmall": "/photos/optimized/20260913-022-small.webp",
    "imageMedium": "/photos/optimized/20260913-022-medium.webp",
    "imageLarge": "/photos/optimized/20260913-022-large.webp",
    "date": "2026-09-13",
    "order": 137
  },
  {
    "id": "20260913-021",
    "image": "/photos/pics/20260913-021.png",
    "imageSmall": "/photos/optimized/20260913-021-small.webp",
    "imageMedium": "/photos/optimized/20260913-021-medium.webp",
    "imageLarge": "/photos/optimized/20260913-021-large.webp",
    "date": "2026-09-13",
    "order": 138
  },
  {
    "id": "20260913-020",
    "image": "/photos/pics/20260913-020.png",
    "imageSmall": "/photos/optimized/20260913-020-small.webp",
    "imageMedium": "/photos/optimized/20260913-020-medium.webp",
    "imageLarge": "/photos/optimized/20260913-020-large.webp",
    "date": "2026-09-13",
    "order": 139
  },
  {
    "id": "20260913-019",
    "image": "/photos/pics/20260913-019.png",
    "imageSmall": "/photos/optimized/20260913-019-small.webp",
    "imageMedium": "/photos/optimized/20260913-019-medium.webp",
    "imageLarge": "/photos/optimized/20260913-019-large.webp",
    "date": "2026-09-13",
    "order": 140
  },
  {
    "id": "20260913-018",
    "image": "/photos/pics/20260913-018.png",
    "imageSmall": "/photos/optimized/20260913-018-small.webp",
    "imageMedium": "/photos/optimized/20260913-018-medium.webp",
    "imageLarge": "/photos/optimized/20260913-018-large.webp",
    "date": "2026-09-13",
    "order": 141
  },
  {
    "id": "20260913-017",
    "image": "/photos/pics/20260913-017.png",
    "imageSmall": "/photos/optimized/20260913-017-small.webp",
    "imageMedium": "/photos/optimized/20260913-017-medium.webp",
    "imageLarge": "/photos/optimized/20260913-017-large.webp",
    "date": "2026-09-13",
    "order": 142
  },
  {
    "id": "20260913-016",
    "image": "/photos/pics/20260913-016.png",
    "imageSmall": "/photos/optimized/20260913-016-small.webp",
    "imageMedium": "/photos/optimized/20260913-016-medium.webp",
    "imageLarge": "/photos/optimized/20260913-016-large.webp",
    "date": "2026-09-13",
    "order": 143
  },
  {
    "id": "20260913-015",
    "image": "/photos/pics/20260913-015.png",
    "imageSmall": "/photos/optimized/20260913-015-small.webp",
    "imageMedium": "/photos/optimized/20260913-015-medium.webp",
    "imageLarge": "/photos/optimized/20260913-015-large.webp",
    "date": "2026-09-13",
    "order": 144
  },
  {
    "id": "20260913-014",
    "image": "/photos/pics/20260913-014.png",
    "imageSmall": "/photos/optimized/20260913-014-small.webp",
    "imageMedium": "/photos/optimized/20260913-014-medium.webp",
    "imageLarge": "/photos/optimized/20260913-014-large.webp",
    "date": "2026-09-13",
    "order": 145
  },
  {
    "id": "20260913-013",
    "image": "/photos/pics/20260913-013.png",
    "imageSmall": "/photos/optimized/20260913-013-small.webp",
    "imageMedium": "/photos/optimized/20260913-013-medium.webp",
    "imageLarge": "/photos/optimized/20260913-013-large.webp",
    "date": "2026-09-13",
    "order": 146
  },
  {
    "id": "20260913-012",
    "image": "/photos/pics/20260913-012.png",
    "imageSmall": "/photos/optimized/20260913-012-small.webp",
    "imageMedium": "/photos/optimized/20260913-012-medium.webp",
    "imageLarge": "/photos/optimized/20260913-012-large.webp",
    "date": "2026-09-13",
    "order": 147
  },
  {
    "id": "20260913-011",
    "image": "/photos/pics/20260913-011.png",
    "imageSmall": "/photos/optimized/20260913-011-small.webp",
    "imageMedium": "/photos/optimized/20260913-011-medium.webp",
    "imageLarge": "/photos/optimized/20260913-011-large.webp",
    "date": "2026-09-13",
    "order": 148
  },
  {
    "id": "20260913-010",
    "image": "/photos/pics/20260913-010.png",
    "imageSmall": "/photos/optimized/20260913-010-small.webp",
    "imageMedium": "/photos/optimized/20260913-010-medium.webp",
    "imageLarge": "/photos/optimized/20260913-010-large.webp",
    "date": "2026-09-13",
    "order": 149
  },
  {
    "id": "20260913-009",
    "image": "/photos/pics/20260913-009.png",
    "imageSmall": "/photos/optimized/20260913-009-small.webp",
    "imageMedium": "/photos/optimized/20260913-009-medium.webp",
    "imageLarge": "/photos/optimized/20260913-009-large.webp",
    "date": "2026-09-13",
    "order": 150
  },
  {
    "id": "20260913-008",
    "image": "/photos/pics/20260913-008.png",
    "imageSmall": "/photos/optimized/20260913-008-small.webp",
    "imageMedium": "/photos/optimized/20260913-008-medium.webp",
    "imageLarge": "/photos/optimized/20260913-008-large.webp",
    "date": "2026-09-13",
    "order": 151
  },
  {
    "id": "20260913-007",
    "image": "/photos/pics/20260913-007.png",
    "imageSmall": "/photos/optimized/20260913-007-small.webp",
    "imageMedium": "/photos/optimized/20260913-007-medium.webp",
    "imageLarge": "/photos/optimized/20260913-007-large.webp",
    "date": "2026-09-13",
    "order": 152
  },
  {
    "id": "20260913-006",
    "image": "/photos/pics/20260913-006.png",
    "imageSmall": "/photos/optimized/20260913-006-small.webp",
    "imageMedium": "/photos/optimized/20260913-006-medium.webp",
    "imageLarge": "/photos/optimized/20260913-006-large.webp",
    "date": "2026-09-13",
    "order": 153
  },
  {
    "id": "20260913-005",
    "image": "/photos/pics/20260913-005.png",
    "imageSmall": "/photos/optimized/20260913-005-small.webp",
    "imageMedium": "/photos/optimized/20260913-005-medium.webp",
    "imageLarge": "/photos/optimized/20260913-005-large.webp",
    "date": "2026-09-13",
    "order": 154
  },
  {
    "id": "20260913-004",
    "image": "/photos/pics/20260913-004.png",
    "imageSmall": "/photos/optimized/20260913-004-small.webp",
    "imageMedium": "/photos/optimized/20260913-004-medium.webp",
    "imageLarge": "/photos/optimized/20260913-004-large.webp",
    "date": "2026-09-13",
    "order": 155
  },
  {
    "id": "20260913-003",
    "image": "/photos/pics/20260913-003.png",
    "imageSmall": "/photos/optimized/20260913-003-small.webp",
    "imageMedium": "/photos/optimized/20260913-003-medium.webp",
    "imageLarge": "/photos/optimized/20260913-003-large.webp",
    "date": "2026-09-13",
    "order": 156
  },
  {
    "id": "20260913-002",
    "image": "/photos/pics/20260913-002.png",
    "imageSmall": "/photos/optimized/20260913-002-small.webp",
    "imageMedium": "/photos/optimized/20260913-002-medium.webp",
    "imageLarge": "/photos/optimized/20260913-002-large.webp",
    "date": "2026-09-13",
    "order": 157
  },
  {
    "id": "20260913-001",
    "image": "/photos/pics/20260913-001.png",
    "imageSmall": "/photos/optimized/20260913-001-small.webp",
    "imageMedium": "/photos/optimized/20260913-001-medium.webp",
    "imageLarge": "/photos/optimized/20260913-001-large.webp",
    "date": "2026-09-13",
    "order": 158
  },
  {
    "id": "20260912-053",
    "image": "/photos/pics/20260912-053.png",
    "imageSmall": "/photos/optimized/20260912-053-small.webp",
    "imageMedium": "/photos/optimized/20260912-053-medium.webp",
    "imageLarge": "/photos/optimized/20260912-053-large.webp",
    "date": "2026-09-12",
    "order": 159
  },
  {
    "id": "20260912-052",
    "image": "/photos/pics/20260912-052.png",
    "imageSmall": "/photos/optimized/20260912-052-small.webp",
    "imageMedium": "/photos/optimized/20260912-052-medium.webp",
    "imageLarge": "/photos/optimized/20260912-052-large.webp",
    "date": "2026-09-12",
    "order": 160
  },
  {
    "id": "20260912-051",
    "image": "/photos/pics/20260912-051.png",
    "imageSmall": "/photos/optimized/20260912-051-small.webp",
    "imageMedium": "/photos/optimized/20260912-051-medium.webp",
    "imageLarge": "/photos/optimized/20260912-051-large.webp",
    "date": "2026-09-12",
    "order": 161
  },
  {
    "id": "20260912-050",
    "image": "/photos/pics/20260912-050.png",
    "imageSmall": "/photos/optimized/20260912-050-small.webp",
    "imageMedium": "/photos/optimized/20260912-050-medium.webp",
    "imageLarge": "/photos/optimized/20260912-050-large.webp",
    "date": "2026-09-12",
    "order": 162
  },
  {
    "id": "20260912-049",
    "image": "/photos/pics/20260912-049.png",
    "imageSmall": "/photos/optimized/20260912-049-small.webp",
    "imageMedium": "/photos/optimized/20260912-049-medium.webp",
    "imageLarge": "/photos/optimized/20260912-049-large.webp",
    "date": "2026-09-12",
    "order": 163
  },
  {
    "id": "20260912-048",
    "image": "/photos/pics/20260912-048.png",
    "imageSmall": "/photos/optimized/20260912-048-small.webp",
    "imageMedium": "/photos/optimized/20260912-048-medium.webp",
    "imageLarge": "/photos/optimized/20260912-048-large.webp",
    "date": "2026-09-12",
    "order": 164
  },
  {
    "id": "20260912-047",
    "image": "/photos/pics/20260912-047.png",
    "imageSmall": "/photos/optimized/20260912-047-small.webp",
    "imageMedium": "/photos/optimized/20260912-047-medium.webp",
    "imageLarge": "/photos/optimized/20260912-047-large.webp",
    "date": "2026-09-12",
    "order": 165
  },
  {
    "id": "20260912-046",
    "image": "/photos/pics/20260912-046.png",
    "imageSmall": "/photos/optimized/20260912-046-small.webp",
    "imageMedium": "/photos/optimized/20260912-046-medium.webp",
    "imageLarge": "/photos/optimized/20260912-046-large.webp",
    "date": "2026-09-12",
    "order": 166
  },
  {
    "id": "20260912-045",
    "image": "/photos/pics/20260912-045.png",
    "imageSmall": "/photos/optimized/20260912-045-small.webp",
    "imageMedium": "/photos/optimized/20260912-045-medium.webp",
    "imageLarge": "/photos/optimized/20260912-045-large.webp",
    "date": "2026-09-12",
    "order": 167
  },
  {
    "id": "20260912-044",
    "image": "/photos/pics/20260912-044.png",
    "imageSmall": "/photos/optimized/20260912-044-small.webp",
    "imageMedium": "/photos/optimized/20260912-044-medium.webp",
    "imageLarge": "/photos/optimized/20260912-044-large.webp",
    "date": "2026-09-12",
    "order": 168
  },
  {
    "id": "20260912-043",
    "image": "/photos/pics/20260912-043.png",
    "imageSmall": "/photos/optimized/20260912-043-small.webp",
    "imageMedium": "/photos/optimized/20260912-043-medium.webp",
    "imageLarge": "/photos/optimized/20260912-043-large.webp",
    "date": "2026-09-12",
    "order": 169
  },
  {
    "id": "20260912-042",
    "image": "/photos/pics/20260912-042.png",
    "imageSmall": "/photos/optimized/20260912-042-small.webp",
    "imageMedium": "/photos/optimized/20260912-042-medium.webp",
    "imageLarge": "/photos/optimized/20260912-042-large.webp",
    "date": "2026-09-12",
    "order": 170
  },
  {
    "id": "20260912-041",
    "image": "/photos/pics/20260912-041.png",
    "imageSmall": "/photos/optimized/20260912-041-small.webp",
    "imageMedium": "/photos/optimized/20260912-041-medium.webp",
    "imageLarge": "/photos/optimized/20260912-041-large.webp",
    "date": "2026-09-12",
    "order": 171
  },
  {
    "id": "20260912-040",
    "image": "/photos/pics/20260912-040.png",
    "imageSmall": "/photos/optimized/20260912-040-small.webp",
    "imageMedium": "/photos/optimized/20260912-040-medium.webp",
    "imageLarge": "/photos/optimized/20260912-040-large.webp",
    "date": "2026-09-12",
    "order": 172
  },
  {
    "id": "20260912-039",
    "image": "/photos/pics/20260912-039.png",
    "imageSmall": "/photos/optimized/20260912-039-small.webp",
    "imageMedium": "/photos/optimized/20260912-039-medium.webp",
    "imageLarge": "/photos/optimized/20260912-039-large.webp",
    "date": "2026-09-12",
    "order": 173
  },
  {
    "id": "20260912-038",
    "image": "/photos/pics/20260912-038.png",
    "imageSmall": "/photos/optimized/20260912-038-small.webp",
    "imageMedium": "/photos/optimized/20260912-038-medium.webp",
    "imageLarge": "/photos/optimized/20260912-038-large.webp",
    "date": "2026-09-12",
    "order": 174
  },
  {
    "id": "20260912-037",
    "image": "/photos/pics/20260912-037.png",
    "imageSmall": "/photos/optimized/20260912-037-small.webp",
    "imageMedium": "/photos/optimized/20260912-037-medium.webp",
    "imageLarge": "/photos/optimized/20260912-037-large.webp",
    "date": "2026-09-12",
    "order": 175
  },
  {
    "id": "20260912-036",
    "image": "/photos/pics/20260912-036.png",
    "imageSmall": "/photos/optimized/20260912-036-small.webp",
    "imageMedium": "/photos/optimized/20260912-036-medium.webp",
    "imageLarge": "/photos/optimized/20260912-036-large.webp",
    "date": "2026-09-12",
    "order": 176
  },
  {
    "id": "20260912-035",
    "image": "/photos/pics/20260912-035.png",
    "imageSmall": "/photos/optimized/20260912-035-small.webp",
    "imageMedium": "/photos/optimized/20260912-035-medium.webp",
    "imageLarge": "/photos/optimized/20260912-035-large.webp",
    "date": "2026-09-12",
    "order": 177
  },
  {
    "id": "20260912-034",
    "image": "/photos/pics/20260912-034.png",
    "imageSmall": "/photos/optimized/20260912-034-small.webp",
    "imageMedium": "/photos/optimized/20260912-034-medium.webp",
    "imageLarge": "/photos/optimized/20260912-034-large.webp",
    "date": "2026-09-12",
    "order": 178
  },
  {
    "id": "20260912-033",
    "image": "/photos/pics/20260912-033.png",
    "imageSmall": "/photos/optimized/20260912-033-small.webp",
    "imageMedium": "/photos/optimized/20260912-033-medium.webp",
    "imageLarge": "/photos/optimized/20260912-033-large.webp",
    "date": "2026-09-12",
    "order": 179
  },
  {
    "id": "20260912-032",
    "image": "/photos/pics/20260912-032.png",
    "imageSmall": "/photos/optimized/20260912-032-small.webp",
    "imageMedium": "/photos/optimized/20260912-032-medium.webp",
    "imageLarge": "/photos/optimized/20260912-032-large.webp",
    "date": "2026-09-12",
    "order": 180
  },
  {
    "id": "20260912-031",
    "image": "/photos/pics/20260912-031.png",
    "imageSmall": "/photos/optimized/20260912-031-small.webp",
    "imageMedium": "/photos/optimized/20260912-031-medium.webp",
    "imageLarge": "/photos/optimized/20260912-031-large.webp",
    "date": "2026-09-12",
    "order": 181
  },
  {
    "id": "20260912-030",
    "image": "/photos/pics/20260912-030.png",
    "imageSmall": "/photos/optimized/20260912-030-small.webp",
    "imageMedium": "/photos/optimized/20260912-030-medium.webp",
    "imageLarge": "/photos/optimized/20260912-030-large.webp",
    "date": "2026-09-12",
    "order": 182
  },
  {
    "id": "20260912-029",
    "image": "/photos/pics/20260912-029.png",
    "imageSmall": "/photos/optimized/20260912-029-small.webp",
    "imageMedium": "/photos/optimized/20260912-029-medium.webp",
    "imageLarge": "/photos/optimized/20260912-029-large.webp",
    "date": "2026-09-12",
    "order": 183
  },
  {
    "id": "20260912-028",
    "image": "/photos/pics/20260912-028.png",
    "imageSmall": "/photos/optimized/20260912-028-small.webp",
    "imageMedium": "/photos/optimized/20260912-028-medium.webp",
    "imageLarge": "/photos/optimized/20260912-028-large.webp",
    "date": "2026-09-12",
    "order": 184
  },
  {
    "id": "20260912-027",
    "image": "/photos/pics/20260912-027.png",
    "imageSmall": "/photos/optimized/20260912-027-small.webp",
    "imageMedium": "/photos/optimized/20260912-027-medium.webp",
    "imageLarge": "/photos/optimized/20260912-027-large.webp",
    "date": "2026-09-12",
    "order": 185
  },
  {
    "id": "20260912-026",
    "image": "/photos/pics/20260912-026.png",
    "imageSmall": "/photos/optimized/20260912-026-small.webp",
    "imageMedium": "/photos/optimized/20260912-026-medium.webp",
    "imageLarge": "/photos/optimized/20260912-026-large.webp",
    "date": "2026-09-12",
    "order": 186
  },
  {
    "id": "20260912-025",
    "image": "/photos/pics/20260912-025.png",
    "imageSmall": "/photos/optimized/20260912-025-small.webp",
    "imageMedium": "/photos/optimized/20260912-025-medium.webp",
    "imageLarge": "/photos/optimized/20260912-025-large.webp",
    "date": "2026-09-12",
    "order": 187
  },
  {
    "id": "20260912-024",
    "image": "/photos/pics/20260912-024.png",
    "imageSmall": "/photos/optimized/20260912-024-small.webp",
    "imageMedium": "/photos/optimized/20260912-024-medium.webp",
    "imageLarge": "/photos/optimized/20260912-024-large.webp",
    "date": "2026-09-12",
    "order": 188
  },
  {
    "id": "20260912-023",
    "image": "/photos/pics/20260912-023.png",
    "imageSmall": "/photos/optimized/20260912-023-small.webp",
    "imageMedium": "/photos/optimized/20260912-023-medium.webp",
    "imageLarge": "/photos/optimized/20260912-023-large.webp",
    "date": "2026-09-12",
    "order": 189
  },
  {
    "id": "20260912-022",
    "image": "/photos/pics/20260912-022.png",
    "imageSmall": "/photos/optimized/20260912-022-small.webp",
    "imageMedium": "/photos/optimized/20260912-022-medium.webp",
    "imageLarge": "/photos/optimized/20260912-022-large.webp",
    "date": "2026-09-12",
    "order": 190
  },
  {
    "id": "20260912-021",
    "image": "/photos/pics/20260912-021.png",
    "imageSmall": "/photos/optimized/20260912-021-small.webp",
    "imageMedium": "/photos/optimized/20260912-021-medium.webp",
    "imageLarge": "/photos/optimized/20260912-021-large.webp",
    "date": "2026-09-12",
    "order": 191
  },
  {
    "id": "20260912-020",
    "image": "/photos/pics/20260912-020.png",
    "imageSmall": "/photos/optimized/20260912-020-small.webp",
    "imageMedium": "/photos/optimized/20260912-020-medium.webp",
    "imageLarge": "/photos/optimized/20260912-020-large.webp",
    "date": "2026-09-12",
    "order": 192
  },
  {
    "id": "20260912-019",
    "image": "/photos/pics/20260912-019.png",
    "imageSmall": "/photos/optimized/20260912-019-small.webp",
    "imageMedium": "/photos/optimized/20260912-019-medium.webp",
    "imageLarge": "/photos/optimized/20260912-019-large.webp",
    "date": "2026-09-12",
    "order": 193
  },
  {
    "id": "20260912-018",
    "image": "/photos/pics/20260912-018.png",
    "imageSmall": "/photos/optimized/20260912-018-small.webp",
    "imageMedium": "/photos/optimized/20260912-018-medium.webp",
    "imageLarge": "/photos/optimized/20260912-018-large.webp",
    "date": "2026-09-12",
    "order": 194
  },
  {
    "id": "20260912-017",
    "image": "/photos/pics/20260912-017.png",
    "imageSmall": "/photos/optimized/20260912-017-small.webp",
    "imageMedium": "/photos/optimized/20260912-017-medium.webp",
    "imageLarge": "/photos/optimized/20260912-017-large.webp",
    "date": "2026-09-12",
    "order": 195
  },
  {
    "id": "20260912-016",
    "image": "/photos/pics/20260912-016.png",
    "imageSmall": "/photos/optimized/20260912-016-small.webp",
    "imageMedium": "/photos/optimized/20260912-016-medium.webp",
    "imageLarge": "/photos/optimized/20260912-016-large.webp",
    "date": "2026-09-12",
    "order": 196
  },
  {
    "id": "20260912-015",
    "image": "/photos/pics/20260912-015.png",
    "imageSmall": "/photos/optimized/20260912-015-small.webp",
    "imageMedium": "/photos/optimized/20260912-015-medium.webp",
    "imageLarge": "/photos/optimized/20260912-015-large.webp",
    "date": "2026-09-12",
    "order": 197
  },
  {
    "id": "20260912-014",
    "image": "/photos/pics/20260912-014.png",
    "imageSmall": "/photos/optimized/20260912-014-small.webp",
    "imageMedium": "/photos/optimized/20260912-014-medium.webp",
    "imageLarge": "/photos/optimized/20260912-014-large.webp",
    "date": "2026-09-12",
    "order": 198
  },
  {
    "id": "20260912-013",
    "image": "/photos/pics/20260912-013.png",
    "imageSmall": "/photos/optimized/20260912-013-small.webp",
    "imageMedium": "/photos/optimized/20260912-013-medium.webp",
    "imageLarge": "/photos/optimized/20260912-013-large.webp",
    "date": "2026-09-12",
    "order": 199
  },
  {
    "id": "20260912-012",
    "image": "/photos/pics/20260912-012.png",
    "imageSmall": "/photos/optimized/20260912-012-small.webp",
    "imageMedium": "/photos/optimized/20260912-012-medium.webp",
    "imageLarge": "/photos/optimized/20260912-012-large.webp",
    "date": "2026-09-12",
    "order": 200
  },
  {
    "id": "20260912-011",
    "image": "/photos/pics/20260912-011.png",
    "imageSmall": "/photos/optimized/20260912-011-small.webp",
    "imageMedium": "/photos/optimized/20260912-011-medium.webp",
    "imageLarge": "/photos/optimized/20260912-011-large.webp",
    "date": "2026-09-12",
    "order": 201
  },
  {
    "id": "20260912-010",
    "image": "/photos/pics/20260912-010.png",
    "imageSmall": "/photos/optimized/20260912-010-small.webp",
    "imageMedium": "/photos/optimized/20260912-010-medium.webp",
    "imageLarge": "/photos/optimized/20260912-010-large.webp",
    "date": "2026-09-12",
    "order": 202
  },
  {
    "id": "20260912-009",
    "image": "/photos/pics/20260912-009.png",
    "imageSmall": "/photos/optimized/20260912-009-small.webp",
    "imageMedium": "/photos/optimized/20260912-009-medium.webp",
    "imageLarge": "/photos/optimized/20260912-009-large.webp",
    "date": "2026-09-12",
    "order": 203
  },
  {
    "id": "20260912-008",
    "image": "/photos/pics/20260912-008.png",
    "imageSmall": "/photos/optimized/20260912-008-small.webp",
    "imageMedium": "/photos/optimized/20260912-008-medium.webp",
    "imageLarge": "/photos/optimized/20260912-008-large.webp",
    "date": "2026-09-12",
    "order": 204
  },
  {
    "id": "20260912-007",
    "image": "/photos/pics/20260912-007.png",
    "imageSmall": "/photos/optimized/20260912-007-small.webp",
    "imageMedium": "/photos/optimized/20260912-007-medium.webp",
    "imageLarge": "/photos/optimized/20260912-007-large.webp",
    "date": "2026-09-12",
    "order": 205
  },
  {
    "id": "20260912-006",
    "image": "/photos/pics/20260912-006.png",
    "imageSmall": "/photos/optimized/20260912-006-small.webp",
    "imageMedium": "/photos/optimized/20260912-006-medium.webp",
    "imageLarge": "/photos/optimized/20260912-006-large.webp",
    "date": "2026-09-12",
    "order": 206
  },
  {
    "id": "20260912-005",
    "image": "/photos/pics/20260912-005.png",
    "imageSmall": "/photos/optimized/20260912-005-small.webp",
    "imageMedium": "/photos/optimized/20260912-005-medium.webp",
    "imageLarge": "/photos/optimized/20260912-005-large.webp",
    "date": "2026-09-12",
    "order": 207
  },
  {
    "id": "20260912-004",
    "image": "/photos/pics/20260912-004.png",
    "imageSmall": "/photos/optimized/20260912-004-small.webp",
    "imageMedium": "/photos/optimized/20260912-004-medium.webp",
    "imageLarge": "/photos/optimized/20260912-004-large.webp",
    "date": "2026-09-12",
    "order": 208
  },
  {
    "id": "20260912-003",
    "image": "/photos/pics/20260912-003.png",
    "imageSmall": "/photos/optimized/20260912-003-small.webp",
    "imageMedium": "/photos/optimized/20260912-003-medium.webp",
    "imageLarge": "/photos/optimized/20260912-003-large.webp",
    "date": "2026-09-12",
    "order": 209
  },
  {
    "id": "20260912-002",
    "image": "/photos/pics/20260912-002.png",
    "imageSmall": "/photos/optimized/20260912-002-small.webp",
    "imageMedium": "/photos/optimized/20260912-002-medium.webp",
    "imageLarge": "/photos/optimized/20260912-002-large.webp",
    "date": "2026-09-12",
    "order": 210
  },
  {
    "id": "20260912-001",
    "image": "/photos/pics/20260912-001.png",
    "imageSmall": "/photos/optimized/20260912-001-small.webp",
    "imageMedium": "/photos/optimized/20260912-001-medium.webp",
    "imageLarge": "/photos/optimized/20260912-001-large.webp",
    "date": "2026-09-12",
    "order": 211
  },
  {
    "id": "20260911-003",
    "image": "/photos/pics/20260911-003.png",
    "imageSmall": "/photos/optimized/20260911-003-small.webp",
    "imageMedium": "/photos/optimized/20260911-003-medium.webp",
    "imageLarge": "/photos/optimized/20260911-003-large.webp",
    "date": "2026-09-11",
    "order": 212
  },
  {
    "id": "20260911-002",
    "image": "/photos/pics/20260911-002.png",
    "imageSmall": "/photos/optimized/20260911-002-small.webp",
    "imageMedium": "/photos/optimized/20260911-002-medium.webp",
    "imageLarge": "/photos/optimized/20260911-002-large.webp",
    "date": "2026-09-11",
    "order": 213
  }
];
